components/Tooltip/Tooltip.js
components/Tooltip/position.js

1. бывают ситуации, когда getComputedStyle.width выдаёт NaN и срёт в консоль - я такую словил по крайней мере....
2. ещё крайне захотелось иметь возможность прокидывтаь класс на контейнер, который содержит тултип, чтоб не оборачивать ручками в ещё один и иметь там внутри тупо ещё один <span>

tooltip fix

---

components/Button/Button.less

Обнаружил некорректное отображение кнопки в IE8, когда для нее установлен атрибут disabled.
Это когда просто задизейблена:
Это при наведении:
Такое поведение не правильно, задизейбленная кнопка всегда должна отображаться серой и при наведении, и без. По крайней мере, именно так она себя ведет в более новых браузерах.
Собственно, эти правки должны поправить такое поведение.

[Button] Fixed bug with incorrect displaying of disabled button in ie8

---

components/Button/Button.js
components/Link/Link.js

Иногда в document.activeElement оказывается не сама кнопка, а какой-нибудь другой элемент, например document.body. А в IE<=10 document.body.blur() убирает окно браузера за предыдущее открытое окно.
Поэтому получалось, что иногда браузер "сворачивается" при клике на ссылку или кнопку.

[Button] [Link] Do not blur document.body

---

components/DatePicker/DateInput.js
components/DatePicker/DateInput.less
components/DatePicker/DatePicker.js
components/DatePicker/Picker.js
components/DatePicker/dateParser.js
docs/src/snippets/DatePicker-snip.js

Стилевые: 
- увеличила область кликабельности кнопки открытия календаря
- поправила позиционирование календаря относительно инпута
Логика:
- Компонент может получать на вход не только дату, но и строку
- Возвращает по-прежнему дату или null, но есть возможность получить строку, если не удалось распарсить дату
- Больше не хранит значение инпута в state, зависит только от пропсов
+ поправила сниппет с учетом новых возможностей

Правки для календаря

---

lib/listenFocusOutside.js

Во время выполнения скрипта document.body еще может не быть, что обрушит бандл.

Add focusin event listener only after document load

---

components/Modal/Modal.less

IE8 не умеет в rgba, поэтому цвет крестика был синий.

[Modal] Fallback for close cross's color

---

testing/ReactTesting.js

Когда map[id] undefined, и мы пытаемся получить map[id].node, начинают происходить страшные вещи

Ошибка в ReactTesting

---

components/Textarea/Textarea.less

[Textarea] [IE8] Fix разноцветного border при фокусе

---

components/Checkbox/Checkbox.js
components/Checkbox/Checkbox.less

Изменила немного разметку и стили у Checkbox.
Сейчас, если у описания Checkbox много текста, текст попадает под чекбокс, что не очень красиво. 
В контур.гайдах тоже описание не попадает под сам чекбокс
https://guides.kontur.ru/controls/checkbox/

fixed markup in Checkbox

---

components/Checkbox/Checkbox.less

В ие8 чекбокс очень плохо видно, поменял цвет границы и фона. (Возможно стоит взять другие, брал пипеткой из гайдов)
Для hover ie8-9 заменил градиент на обычный цвет.
В ie8 при клике появлялась область фокусировки.

[Checkbox] Fix color in ie8

---

components/Spinner/Spinner.js

и перезаписывает их инлайном и тем самым ломает контрол. все вполне замечательно работает через класс. strokeWidth на всякий случай оставил - вдруг будет кружок побольше.
Откуда тут эти аттрибуты, если честн обыло лень раскапывать :)

[Spinner] React 15.x начал корректно работать с svg аттрибутами 

---

components/Loader/Loader.less
components/Spinner/Spinner.less

Для ускорения билда я использую css-loader@0.14.5, в котором composes не работает. Разбираться не стал, ибо в библиотеке чаще используют less миксины, а composes всего в двух местах. Предлагаю заменить composes на использование миксина.

Убрал использование 'composes' в стилях

---

components/Button/Button.less
components/variables.less

У кнопки в состоянии checked в IE8 срабатывает ховер и убирает выделение.
https://monosnap.com/file/hIKHPPJJKz9vF9oYkS5KKYb8cwnMZa
https://monosnap.com/file/ZIlN6FLuSxYJK2Ra0I6ikfLEPnangx
Пофиксил, добавив кнопке в состоянии checked свой ховер.

fix ie8 hover on checked button

---

components/Select/Select.js
components/Select/__tests__/Select-test.js
components/Select/__tests__/Select.stories.js

Фикс issue #263. Shallow-сравнение значений фиксит этот баг в 90% случаев, а для остальных 10%, когда "неглубокого" сравнения недостаточно, введен новый пропс "compareValues".

[Select] новый пропс "areValuesEqual" с shallow-сравнением значений по умолчанию

---

components/MenuItem/MenuItem.less
components/RenderContainer/RenderContainer.js
components/variables.less

специфичность увеличивается за счет добавления к селекторам класса `react-ui` с несколькими повторениями - повторения и увеличивают специфичность
количество повторений класса `retail-ui` в селекторе задается переопределением переменной `@specificity-level` с умолчательного значения `0` на любое другое разумное неотрицательно число
класс `react-ui` всегда добавляется к контейнеру `Portal` - так как пользователь библиотеки не может оказывать на него никакого влияния
к остальным контейнерам, в которых рендерятся контролы retail-ui необходимо явно добавить класс `react-ui`.
если все будет ок, то аналогичный миксин нужно будет добавить во все остальные less файлы

добавлена возможноть увеличивать специфичность селекторов контролов

---

components/Select/Select.less

В ие8 некорректно обрезается label дропдауна, из-за того, что не указана ширина явно.

fix clipping a dropdown label in ie8

---

lib/dom/getComputedStyle.js

Из-за особенности бандлера, нативная функция getComputedStyle, которая является частью экспортируемого по дефолту модуля, может вызываться в контексте кастомного объекта, что может приводить вот к такой ошибке:
Добавили явную привязку контекста.

Явная привязка контекста для getComputedStyle

---

components/Textarea/Textarea.less

**Повторный пулл реквест из-за реорганизации форка. [Первый](https://github.com/skbkontur/retail-ui/pull/305)**
Если верить интернету, это пробел под `inline` и `inline-block` элементами - это задел для букв с нижними выносными элементами (descender), например _у_ или _р_. Он влияет на вертикальный ритм и отлично заметен, когда среди нескольких `<Input />` вставлена `<Textarea />`.
В разных браузерах он разный:
- 2 пикселя в Фаерфоксе на Виндоуз 10
- 4 пикселя в Фаерфоксе на Линуксе
- 5 пикселей в Хроме и ему подобных браузерах на Виндоуз 10
- в IE9 на удивление десцендера нет :-)
[Живое демо](https://sashasushko.github.io/retail-ui-form/), измерьте в инспекторе высоту обёртки и самой текстарии.
Убирается этот отступ указанием `vertical-align` для строчного или блочно-строчного элемента.

Fixed gap between textarea and her wrapper

---

components/Center/Center.js
components/DropdownContainer/DropdownContainer.js
components/Hint/Hint.d.ts
components/Hint/Hint.js
components/Hint/HintBox.js
components/Loader/Loader.less
components/Modal/Modal.js
components/Modal/Modal.less
components/Popup/Popup.js
components/Popup/Popup.less
components/Toast/Toast.less
components/Toast/ToastView.js
components/Tooltip/Box.js
components/ZIndex/ZIndex.d.ts
components/ZIndex/ZIndex.js
components/ZIndex/__tests__/ZIndex.stories.js
components/ZIndex/index.d.ts
components/ZIndex/index.js
package.json

Добавил компонент ZIndex - это механизм для работы с z-index
-- по умолчанию рисует div и проставляет ему z-index в style, а также запоминает все нарисованные z-index
-- можно отключить отрисовку div, тогда компонент только увеличит текущее значение z-index на дельту в хранилище - это нужно чтобы задать начальное смещение для компонент из retail-ui если они должны отображаться поверх каких-то элементов окружения нарисованных другими средствами
#302 [Loader] [Popup] (Kebab) z-index
#304 [Loader] in Modal.Body
#334 [TopBar] Выпадающее меню под лоадером

z-index synchronization

---

components/Spinner/Spinner.js
components/Spinner/__stories__/Spinner.stories.js
components/Spinner/__tests__/Spinner-test.js
preprocessor.js

Теперь в этом случае рендерится спиннер с дефолтным типом

Если передать невалидный type (например: 'small') в Spinner — приложение ломается

---

components/Spinner/Spinner.js
components/Spinner/__stories__/Spinner.stories.js
components/Spinner/__tests__/Spinner-test.js
package.json
preprocessor.js

Если передать невалидный type (например: 'small') в Spinner — приложение ломается.
Теперь в этом случае рендерится спиннер с дефолтным типом.

Spinner wrong type fix

---

components/Popup/Popup.js
components/Popup/PopupHelper.js

**Повышение специфичности селекторов**
Если библиотека контролов используется в проекте с собственными глобальными стилями, которые влияют на контролы из библиотеки и при этом такие стили никак нельзя переделать, то можно использовать повышение специфичности селекторов с за счет класса retail-ui. Popup при предварительно отрисовке не добавлял на контейнер спец класс и при увеличенной специфичности стили просто не применялись на его внутренности, поэтому размер в пререндере мог отличаться от реальных размеров
Popup вправо - нормально:
Popup влево - имеет неправильное позиционирвоание:
**Позиционирование с учетом скролов**
Фикс проблемы: скроллбар не учитывался и Popup мог показаться под ним, теперь скроллбар учитывается

Fix popup positioning

---

components/Input/Input.less
components/Input/Input.styles.js

При size = medium сейчас размер шрифта в полях ввода равен 14px, хотя Саша Храмцов говорит, что правильнее было бы сделать 16px как в size = large.
Не уверен, что этот pull request будет работать во всех случаях и во всех контролах, так как там есть флаги process.env.EXPERIMENTAL_CSS_IN_JS и войти во весь код который там есть достаточно не легко. 
Но в моем случае в DatePicker эти правки выглядят хорошо:

Размер шрифта в размере Medium для Input должен быть 16px

---

components/RenderLayer/index.js
components/SidePage/SidePage.d.ts
components/SidePage/SidePage.js
components/SidePage/SidePage.less
components/SidePage/__tests__/SidePage.stories.js
components/internal/withFocusOutside.js

Порешал 2 проблемы:
1. Footer не был прижат к нижней части сайдпейджа, если весь контент в него влазил.
2. Сайдпейдж закрывался на событие FocusOut у RanderLayer. Хочется иметь поведение, при котором клик на фоне бы закрывал сайдпейдж, а переход на другую вкладку или другое окно операционной системы не закрывал бы его

Сайдпейдж Footer и поведение

---

components/Popup/Popup.js
components/ZIndex/ZIndex.js
components/ZIndex/__tests__/ZIndex.stories.js

У попапа есть метода `_prerender`. Он нужен для анимации и рендерит компонент где-то вне поля видимости пользователя, чтобы рассчитать размеры этого компонента. Проблема в том, что у этого компонента есть ZIndex, который глобально увеличивается. Компонент, который нарендерили не удаляется нормально, из-а чего глобальная переменная ZIndex-а не уменьшается и происходит страшное

Когда рендерим Popup в пререндере не создаем ZIndex

---

testing/ReactTesting.js

PR fixing `ReactTesting.call(datePicker, 'setStringValue', '07.03.2018')` arguments passing.
Without fix only first character of string was passed to `setStringValue` function of DatePicker-adapter.

fix ReactTesting.call() arguments passing

---

testing/ReactTesting.js

Sorry, but Select's adapter becomes broken and unusable. We need to revert changes from #457

Reverting "fix ReactTesting.call() arguments passing (#457)"

---

components/Input/Input.flat.less
components/Input/Input.less

Кажется, что размер шрифта placeholder должен совпадать с тем что он замещает?

placeholder-in-medium-size-16px

---

components/Modal/Modal.js
components/ModalStack/ModalStack.js.flow
components/ModalStack/ModalStack.ts
components/ModalStack/index.js.flow
components/ModalStack/index.ts
components/SidePage/SidePage.js
components/SidePage/__tests__/SidePage.stories.js
package.json

До этого момента Modal и SidePage создавали каждый свой стек. В некоторых сценариях нужно, чтобы они находились в одном стеке, например, нажате кнопки Esc должно закрывать только верхний сайдпейдж или модалку, а не сразу две.
Вот списочек кейсов, которые нужно было поддержать при смердживании стеков:
- Клик на фон. Клик на фон должен обрабатывать только верхний элемент стека. Остальные его игнорируют.
- Сдвиг сайдпейджа влево на 20 пикслей. Если открыто больше одного сайдпеджа, самый первый сайдпейдж должен сдвинуться влево на 20 пикселей. Он не должен сдвигаться, когда по верх него открылась модалка.
- Тени у сайпейджей. Начиная со второго, сайдпеджи открываются друг над другом. Это суммирует тень, которую они отбрасывают. Поэтому тень должна появляться только у первого (который …

Общий стек для Modal и SidePage

---

components/Checkbox/Checkbox.flat.less
components/Checkbox/Checkbox.less

Если у родительского элемента переопределен, например `font-size: 20px;`. Стиль текет вниз на чекбокс и ломает отображение иконки.

fix-font-size-leak Переопределяем font-size в корне компонента Checkbox

---

components/Menu/Menu.less
components/Tooltip/Tooltip.less

Используем retail-ui в виджете. На странице, куда его встраиваем заданы стили через звездочку 
* {
box-sizing: border-box;
margin: 0;
padding: 0;
}
box-sizing: border-box; ломает верстку в Tooltip и ComboBox. Поэтому для некоторых элементов пришлось добавить значение по умолчанию.

default box-sizing value for some elements

---

components/Hint/Hint.js

При обертке элемента с шириной 100% хинтом, элемент схлопывается по ширине. Например, проявляется на combobox'e.

Cange display to inline

---

packages/retail-ui/components/Popup/Popup.tsx

react@<16.x.x calls `componentDidUpdate` after setState(() => null).
It caused recursive updates in Popup

fix(popup): fixed recursive updates for older react

---

packages/retail-ui/components/Tabs/Tab.tsx

- 'component' не попадает в в рендер
- Fixed #605

fix(Tab): исправлено попадание лишнего пропа в разметку

---

packages/retail-ui/components/DatePicker/DatePicker.tsx
packages/retail-ui/components/DatePicker/Picker.tsx
packages/retail-ui/components/DatePicker/__tests__/DatePicker-test.tsx

- Если передана минимальная или максимальная дата, календарь открывается на ближайшем к сегодняшнему дню доступном месяце
- Испрвлены PropTypes, не позволяющие передать null в value
- Closed #658

feat(retail-ui Calendar): открывается ближайший доступный месяц

---

packages/retail-ui/components/Kebab/README.md
packages/retail-ui/styleguide.config.js

Лечит проблему при которой **styleguidist** в первую очередь использует файлы с расширением `.js`. Для нас важно, чтобы первыми в приоритете были `.ts, .tsx` файлы. Иначе возникали проблемы, что в бандж документации могли попасть неактуальные компоненты.
По умолчанию, **styleguidist** вмерживает `webpackConfig` при помощи утилитки [webpack-merge](https://github.com/survivejs/webpack-merge). Из-за этого свойство `resolve.extensions` не подменялось, а конкатилось к существующему. Для его замены заиспользован параметр `dangerouslyUpdateWebpackConfig`

docs(reatil-ui): tune styleguidist config

---

packages/retail-ui/components/Tooltip/Tooltip.tsx

- Правильный порядок позиций в `Tooltip.defaultProps.allowedPositions`
- [Гайд](https://guides.kontur.ru/controls/tooltip/#09)
- Убран костыль `!` для работы с `defaultProps`
- Close #178

fix(Tooltip): порядок позиций по гайду

---

packages/retail-ui/components/Modal/Modal.less
packages/retail-ui/components/variables.less

Чтобы можно было переопределить в проекте.
Откуда вообще взялось это значение?  
У нас (на основание данных о пользователях) это 460px

425px теперь живет в variables.less

---

packages/retail-ui/components/Textarea/Textarea.flat.less
packages/retail-ui/components/Textarea/Textarea.less
packages/retail-ui/components/Textarea/Textarea.tsx

- Теперь ширина передается врапперу
- У самой `textarea` в стилях `width: 100%;`  и `max-width: 100%;`
- Стили поправлены в дефолтной и flat-темах
- Fixed #724

fix(Textarea): fix % width

---

packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx

14 реакт не поддерживает `PureComponent`, пришлось использовать `shouldComponentUpdate` с `shallow`-сравнением.
Кажется пора отказаться от поддержки 14 реакта.

fix(ComboBox): PureComponent заменен на shouldComponentUpdate

---

packages/retail-ui/components/Autocomplete/Autocomplete.tsx
packages/retail-ui/components/Autocomplete/__tests__/Autocomplete-test.tsx
packages/retail-ui/components/Center/Center.tsx
packages/retail-ui/components/Checkbox/Checkbox.tsx
packages/retail-ui/components/CurrencyInput/CurrencyInput.tsx
packages/retail-ui/components/FxInput/FxInput.tsx
packages/retail-ui/components/Input/Input.tsx
packages/retail-ui/components/Link/Link.tsx
packages/retail-ui/components/Radio/Radio.tsx
packages/retail-ui/styleguide.config.js

Сделал фильтрацию пропсов для документации средствами `react-docgen-typescript`.
Фильтруются все пропсы без описания компонентов:
- Autocomplete
- Center
- Checkbox
- CurrencyInput
- FxInput
- Input
- Link
- Radio

docs(retail-ui): почищена дока в styleguidist

---

packages/retail-ui/components/internal/ResizeDetector/ResizeDetector.tsx

`removeEventListener` ломал iphone 5s, поэтому убрали удаление слушателя.
Это не должно ни на что повлять, т.к. событие было повешено на `window`
iFrame'а который удалется при unmount'е

fix(ResizeDetector): удален `removeEventListener` :green_apple:

---

packages/react-ui-testing/SeleniumTesting.sln
packages/react-ui-testing/SeleniumTesting/SeleniumTesting.csproj
packages/react-ui-testing/Tests/Tests.csproj

> Before bringing existing .NET Framework code to a .NET Core project, we recommend you first add the Windows Compatibility Pack by installing the NuGet package Microsoft.Windows.Compatibility. This maximizes the number of APIs you have at your disposal.
https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/

Dotnet core

---

packages/retail-ui/components/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx
packages/retail-ui/components/SidePage/__stories__/SidePage.stories.tsx
yarn.lock

После пересчета скролла на каждый `didUpdate` сломалась очистка добавленных стилей. Из-за этого страница не скроллилась после удаления компонента с `HBVS`.
- Добавлена очистка стилей перед пересчетом скролла
- Добавлена очистка на `willUnmount`
- Починен флаг `allowScrolling`, который давно ни на что не влиял

fix(HBVS): окончательно отремонтирован

---

packages/retail-ui/components/SidePage/SidePage.tsx
packages/retail-ui/components/SidePage/__stories__/SidePage.stories.tsx

При `blockBackground === false`, `HideBodyVerticalScroll` не рэндерится.
Нет элемента - нет проблем.
Fix #822

fix(SidePage): fix blockBackground=false

---

packages/retail-ui/components/Sticky/Sticky.less
packages/retail-ui/components/Sticky/Sticky.tsx

Добавлен флаг `allowMaximumUpdateDepthExceeded`

fix(Sticky): вернули старое поведение с бесконечной рекурсией

---

packages/retail-ui/components/Modal/ModalFooter.tsx
packages/retail-ui/components/Modal/ModalHeader.tsx

После срочного ремонта `Sticky` немного развалились `Modal.Header` и `Modal.Footer`.
Этот фикс включает `allowChildWithMargins` у `Sticky` в вышеозначенных компонентах.

fix(Modal): fix after Sticky hotfix

---

packages/retail-ui/components/Modal/Modal.less

Change `centerContainer` mobile padding to margin to match actual styles
Closes #847

fix(Modal): not adaptive

---

packages/retail-ui/components/Button/Button.flat.less

- Починено позиционирование красной подложки у кнопки-ссылки во flat-теме
в сосотоянии `error === true`;
- Для `use="link"` в сосотоянии `error === true` убрана красная рамка во
flat-теме
Fix #856

fix(Button): fix flat styles

---

packages/retail-ui/components/Paging/NavigationHelper.tsx
packages/retail-ui/components/Paging/Paging.less
packages/retail-ui/components/Paging/Paging.tsx
packages/retail-ui/components/Paging/README.md
packages/retail-ui/components/Paging/__stories__/Paging.stories.tsx
packages/retail-ui/components/Paging/__tests__/Paging-test.tsx

- Добавлен проп `globalListener`, для добавления слушателя **keydown** на `window`
- Навигационные подсказки появляются только когда доступно управление клавиатурой (`globalListener === true` или фокус)
- Избавление от `_` в названии приватных методов
- Небольшой рефакторинг
- Close #321

feat[Paging]: управление клавиатурой без фокуса

---

packages/react-ui-screenshot-tests/gemini/Checkbox.js
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/hovered/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/hovered/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/hovered/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/plain/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/plain/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/plain/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/tabPress/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/tabPress/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Checkbox indeterminate/tabPress/ie11.png
packages/retail-ui/components/Checkbox/Checkbox.flat.less
packages/retail-ui/components/Checkbox/Checkbox.less
packages/retail-ui/components/Checkbox/Checkbox.tsx
packages/retail-ui/components/Checkbox/__stories__/Checkbox.stories.tsx

**Состояние `Checkbox` "частично выбранный"**
Включается передачей свойства `partialChecked`;
Если `partialChecked === true`, то свойство `checked` игнорируется и разработчику нужно самому позаботиться о выключении такого состояния.
Пока выглядит так: темный прямоугольник `#333` размером 8 * 8 px и границей `1px solid #202020;`

feat(Checkbox): новое состояние WIP

---

packages/retail-ui/components/CurrencyInput/CurrencyInput.tsx
packages/retail-ui/components/FxInput/FxInput.adapter.ts

- Плэйсхолдер исчезает при фокусе (как в гайде написано)
- Переименованы методы: без **_**
- Состояние фокуса хранится в стэйте, а не в поле класса
- Fixed #413

fix(CurrencyInput): починено поведение плэйсхолдера

---

packages/retail-ui/components/ComboBox/ComboBox.tsx
packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx
packages/retail-ui/components/CustomComboBox/ComboBoxView.tsx
packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx

BREAKING CHANGE: second argument of renderItem not used and replaced by MenuItemState

feat(ComboBox): allow use hover state in renderItem

---

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/retail-ui/components/CustomComboBox/reducer/autocomplete.tsx

В режиме `autocomplete={true}`, после редактирования инпута и удаления `value` комбобокса "извне", при следующем фокусе инпут покажет старый текст.
```
let delay = ms => v => new Promise(resolve => setTimeout(resolve, ms, v));
let getItems = q =>
Promise.resolve(
[
{ value: 1, label: 'First' },
{ value: 2, label: 'Second' },
{ value: 3, label: 'Third' },
{ value: 4, label: 'Fourth' },
{ value: 5, label: 'Fifth' },
{ value: 6, label: 'Sixth' }
].filter(
x =>
x.label.toLowerCase().includes(q.toLowerCase()) ||
x.value.toString(10) === q
)
)
.then(delay(500));
let initialState = {
selected: null,
error: false
};
let handleChange = (_, item) => setState({ selected: item, error: false });
let handleUnexpectedInput = () => setState({ error: true, selected: null });
let handleFocus = () => …
```

fix(ComboBox): update textValue even if empty (autocomplete mode)

---

packages/react-ui-testing/README.md
packages/react-ui-testing/Tests/TestEnvironment/Browser.cs
packages/react-ui-testing/Tests/TestEnvironmentFixture.cs
packages/react-ui-testing/Tests/Tests.csproj

Изменения для 2 тикетов.
Fix #891  
Убрал dotenv.net из зависимостей.  
Казалось сначала, что нативней всего использовать App.config, но это xml и будет не так удобно, как .env. Да и не встраивается это легко (https://github.com/dotnet/corefx/issues/22101).
Еще один вариант - это хранить логин/пароль в json-файле, который отлично встраивается в sauce.js, а в .net воспользоваться JsonConvert, но опять же json - это не так удобно.
В итоге решил просто попарсить файл в .net.
Fix #873
Убрал цикл с попытками поднять туннель. Теперь просто жду, что sauce.js после запуска выводит сообщение об успехе в stdout.
Структуру не стал переделывать, потому что в будущем тесты надо будет распараллеливать, а Саус не даст этого сделать из-за ограничения по браузерам. Это значит, придется искать …

SC cleaning

---

packages/retail-ui/components/ComboBox/ComboBox.tsx
packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx
packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx
packages/retail-ui/components/CustomComboBox/reducer/autocomplete.tsx
packages/retail-ui/components/CustomComboBox/reducer/default.tsx

В #967 был добавлен метод `open`. Оказалось, что он довольно бесполезен, т.к. всегда открывает пустой список, без запуска поиска (получения списка элементов). 
Здесь я предлагаю дополнить его возможностью попутно запустить поиск по пустому (получить все элементы) или текущему значению инпута. Как происходит на onFocus в режиме не-автокомплита.
Пришлось ввести постоянную синхронизацию между `textValue` и `value`, что вроде бы и так логично.
Напомню, все это я затеял после того, как ComboBox в режиме autocomplete перестал открываться на фокус. Но иногда, хочется это делать руками (#957 ).
Close #991

 feat(ComboBox): add search method

---

packages/react-ui-screenshot-tests/gemini/dropdownContainer.js
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/inner scroll/shot/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/inner scroll/shot/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/items/shot/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/items/shot/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/items/shot/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/page scroll/shot/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/page scroll/shot/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/long Items/page scroll/shot/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/inner scroll/shot/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/inner scroll/shot/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/items/shot/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/items/shot/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/items/shot/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/page scroll/shot/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/page scroll/shot/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/DropdownContainer/short Items/page scroll/shot/ie11.png
packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx
packages/retail-ui/components/DropdownContainer/__stories__/DropdownContainer.stories.tsx

Дополнение к #1001. fix #590 
DropdownContainer в режиме `disablePortal: true` никак не учитывает prop `align?: 'left' | 'right'`.  Это не позволяет полностью покрыть кейс #590 (второй скрин), где выпадашку следует вытащить из портала и выровнять по правому краю.
Добавил story для тестирования всех положений выпадахи:
-  было:
- стало:
- разница:

 fix(DropdownContainer): align dropdown in disablePortal mode

---

packages/react-ui-screenshot-tests/gemini/logotype.js
packages/react-ui-screenshot-tests/gemini/screens/Logotype/with widget/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Logotype/with widget/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Logotype/with widget/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/Logotype/without widget/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Logotype/without widget/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Logotype/without widget/ie11.png
packages/retail-ui/components/Logotype/Logotype.less
packages/retail-ui/components/Logotype/Logotype.tsx
packages/retail-ui/components/Logotype/__stories__/Logotype.stories.tsx

Раньше компонент рендерил блочный или строчный элемент взависимости от флага `withWidget`, и это странным образом никому ничего не ломало. По этому можно предположить, что будет безопасно оставить только один из них (блочный).
Поломки возможны у тех, кто использует Logotype отдельно от TopBar и без виджета (т.е. строчный вариант). Но их будет легко исправить.
Что думаете?
fix #631

 fix(Logotype): keep the widget working after props update

---

packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx

После моих последних изменений стал сыпаться warning по открытию выпадашек:
> Warning: DropdownContainer is accessing findDOMNode inside its render().
Из-за вызова `this.props.getParent()` в процессе рендера, в который пользователи обычно передают `() => findDOMNode(this)`. 
Перенес `minWidth` в state, а её вычисление в `position()`.

refactor(DropdownContainer): render warning fix

---

packages/retail-ui/components/Select/Select.tsx

Проблема: у Select не было публичного focus() метода - соответственно он не отображал тултип с валидацией react-ui-validations, которая дергает публичный фокус метод компонента.
Решение: прокинул фокус наружу и добавил tabIndex=0 для span, который не умеет фокуситься из коробки.

fix(Select): public focus 

---

packages/retail-ui/components/Popup/Popup.tsx
packages/retail-ui/components/Popup/__tests__/__snapshots__/Popup-test.tsx.snap
packages/retail-ui/components/RenderLayer/RenderLayer.tsx
packages/retail-ui/components/Tooltip/Tooltip.tsx

Сломалась отключение обработки событий для Tootip и Hint.
В RenderLayer prop active по умолчанию был равен true.
Tooltip при "close" не передавал active=false, из-за чего события продолжали обрабатываться.
В Popup active={this.props.onCloseRequest && this.props.opened}, если onCloseRequest не передавался, то был равен undefined и active брался из defaultProps и был равен true.

fix(RenderLayer) не отключает обработку событий

---

packages/retail-ui/components/Fias/Form/FiasForm.tsx

В элементах комбобокса не стоит вырезать скрытые поля адреса. Они дают возможность различать одноименные города и т.д.

chore(Fias): allow to display invisible fields in combobox items

---

packages/retail-ui/styleguide.config.js

Styleguidist должен заработать на хосте `localhost.dev.kontur`, чтобы компоненты могли ходить с него на `api.dev.kontur` .

build(retail-ui): add public url for styleguide dev-server

---

packages/retail-ui/components/Popup/Popup.less
packages/retail-ui/components/Popup/Popup.tsx
packages/retail-ui/components/Tooltip/Tooltip.tsx

fix #973
Добавил новый флаг для Popup - `ignoreHover: boolean`.
Использую этот флаг в тултипе при условии `props.trigger === 'hoverAnchor'`

fix(Tooltip): fixed closing for `hoverAnchor` 

---

packages/retail-ui/components/SidePage/SidePage.tsx

Поправил генерацию `d.ts` для пакета @skbkontur/react-ui.
Генерировались типы имеющие `require()` со ссылкой на `retail-ui`

fix(SidePage): dynamic resolved types `Body` and `Footer` with context

---

packages/retail-ui/components/PasswordInput/PasswordInput.tsx

```javascript
warning.js:33 Warning: React does not recognize the `detectCapsLock` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `detectcapslock` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in input (created by Input)
in span (created by Input)
in label (created by Input)
in Input (created by PasswordInput)
in div (created by PasswordInput)
in PasswordInput (created by Component)
in div (created by Component)
in Component
in div
```

fix(PasswordInput): remove not DOM prop `detectCapsLock`

---

packages/retail-ui/.eslintignore

Теперь можно не делать `clean` перед запуском eslint'а

build(retail-ui): use eslint for only old js components

---

packages/retail-ui/components/Hint/Hint.tsx
packages/retail-ui/components/Popup/Popup.tsx
packages/retail-ui/components/Tooltip/Tooltip.tsx
packages/retail-ui/typings/event-types.d.ts
packages/retail-ui/typings/opaque-helper-types.d.ts

When consumer does not skipLibCheck, typescript compiler has no way to find ambient types of
dependant @skbkontur/react-ui package, so one must specify path to those types in 'include' section
of his tsconfig. To overcome this complexity, we replace ambient types (IMosueEvent/IFocusEvent)
with concrete ones and import them explicitly.

fix(Popup): remove ambient types

---

packages/retail-ui/components/Autocomplete/Autocomplete.js.flow
packages/retail-ui/components/ComboBox/ComboBox.js.flow
packages/retail-ui/components/ComboBox/index.js.flow
packages/retail-ui/components/DropdownMenu/DropdownMenu.js.flow
packages/retail-ui/components/Hint/Hint.js.flow
packages/retail-ui/components/Kebab/Kebab.js.flow
packages/retail-ui/components/Tooltip/Tooltip.js.flow

Эти props необязательные, так как у компонентов есть дефолтные значения. 
А Flow ругается.
У комбобокса есть дефолтное определение типа item'а, почему бы его не указать в дефолтном типе дженерика.

fix(retail-ui): add optional for some props and default for generic

---

packages/retail-ui/components/Tooltip/Tooltip.tsx

fix problem where children is plain string, that render without popup on react@15

fix(Tooltip): correct render invalid react element

---

packages/retail-ui/components/Popup/Popup.tsx
packages/retail-ui/components/Popup/__tests__/__snapshots__/Popup-test.tsx.snap
packages/retail-ui/components/internal/LifeCycleProxy.ts

Добавил компонент `LifeCycleProxy` у которого можно подписаться на вызовы lifecycle методов. Сам компонент рендерится внутри портала, что обеспечивает правильный порядок вызовов `popup render -> portal render -> did update`
fix #1257

fix(Popup): call `onOpen` prop in right moment for react@15

---

packages/retail-ui/package.json
yarn.lock

В общем эта херня (свойство `resolutions`) триггерит переустановку зависимости `wd` при добавлении/удалении пакетов в retail-ui, в результате генерируется некорректный yarn.lock.
semver зацепился, потому что ключ `semver@^5.6.0` уже корректно резолвится в нужный пакет чуть выше, поэтому это просто удаление дубля.

build(retail-ui): remove unused resolutions for gemini/wd deps

---

packages/retail-ui/components/CurrencyLabel/CurrencyLabel.tsx
packages/retail-ui/components/Token/Token.tsx

По каким-то причинам в 0.44.2 в документации сломались CurrencyLabel и Token

docs(retail-ui): fix export components for styleguidist

---

packages/retail-ui/components/Logotype/ProductWidget.tsx

В некоторых случаях скрипт может загружаться очень долго. Из-за этого появляется проблема когда страница находится в состоянии загрузки пока не загрузится скрипт виджета.

fix(Logotype): async load products widget script

---

packages/retail-ui/components/Tooltip/README.md

docs(Tooltip): add example with `anchorElement`

---

packages/react-ui-validations/typings/console.d.ts
packages/retail-ui/typings/console.d.ts

Some `@types/*` depend on `@types/node`, that has declared `console` module and vscode try autoimport not existed `console` module.
For more info see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015

chore: add workaround to fix console autoimport issue

---

packages/retail-ui/components/Paging/Paging.tsx

Исправляет https://github.com/skbkontur/retail-ui/issues/1351
По какой-то причине, в ie11 при нажатии клавиш влево/вправо у event.key лежит не "ArrowLeft"/"ArrowRight", а просто "Left"/"Right". Заменил на использование event.key, кажется, это более правильно.

fix(Paging): changed detecting of pressed key

---

packages/retail-ui/components/internal/ComponentStatesTable.tsx

- удален стиль Таблицы width: 100%.
При ```width: 100%``` содержимое таблицы растягивалось по всему экрану, между элементами в таблице оставалось много места, что создавало неудобства при просмотре сториса.

refactor(Table): deleted table width = 100%

---

packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/move focus backward/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/move focus backward/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/move focus backward/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/move focus forward/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/move focus forward/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/move focus forward/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/reset focus after click/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/reset focus after click/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/Tabs keyboard control/reset focus after click/ie11.png
packages/react-ui-screenshot-tests/gemini/tabs.js
packages/retail-ui/components/Button/Button.tsx
packages/retail-ui/components/Checkbox/Checkbox.tsx
packages/retail-ui/components/Kebab/Kebab.tsx
packages/retail-ui/components/Link/Link.tsx
packages/retail-ui/components/Paging/Paging.tsx
packages/retail-ui/components/Tabs/Tab.tsx
packages/retail-ui/components/Tabs/Tabs.tsx
packages/retail-ui/components/Toggle/Toggle.tsx
packages/retail-ui/lib/events/tabListener.ts

- добавил флаг `isFirefox47` для скриншотных тестов
- вернул старую проверку существования свойства `focus`, чтобы завести управление стрелками
- добавил тестов для проверки управления с клавиатуры
fix https://github.com/skbkontur/retail-ui/issues/1424
close https://github.com/skbkontur/retail-ui/issues/1410
---
Есть мыль вынести все проверки типа `event.keyCode === 32` в отдельную либу.
По сути я её почти доделал в этой ветке, но вовремя остановился и откатил)

 refactor(Tab): use global tabListener

---

packages/retail-ui/components/RenderLayer/RenderLayer.tsx

По мотивам #1439 
`mousedown` ивент всплывает не всегда, подробнее — [по ссылке](https://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html)
Дополнительно к `mousedown` добавил `touchstart`

fix(RenderLayer): add touchstart handling

---

packages/react-ui-screenshot-tests/gemini/screens/button/Button states/different visual states/page - 2/chromeFlat.png
packages/react-ui-screenshot-tests/gemini/screens/button/Button states/different visual states/page - 2/firefoxFlat.png
packages/react-ui-screenshot-tests/gemini/screens/button/Button states/different visual states/page - 2/ie11Flat.png
packages/react-ui-screenshot-tests/gemini/screens/button/Button states/different visual states/page - 4/chromeFlat.png
packages/react-ui-screenshot-tests/gemini/screens/button/Button states/different visual states/page - 4/firefoxFlat.png
packages/react-ui-screenshot-tests/gemini/screens/button/Button states/different visual states/page - 4/ie11Flat.png
packages/retail-ui/components/Button/Button.common.less

В плоской теме класс `.DEPRECATED_sizeMedium` у средней кнопки перебивал общие стили, и не давал пропам `__noPadding`, `__noPaddingRight` и `narrow` делать свое дело.
| Было | Стало | Diff |
|-|-|-|
| ![image](https://user-images.githubusercontent.com/4607770/59249424-264dba80-8c3e-11e9-9203-a4ba8c279600.png) |![image](https://user-images.githubusercontent.com/4607770/59249380-074f2880-8c3e-11e9-8aaa-e4c5e3dbdb49.png)| ![image](https://user-images.githubusercontent.com/4607770/59249435-32397c80-8c3e-11e9-92aa-8256e6e5faff.png) |
fix #1451 
[comment из #1309](https://github.com/skbkontur/retail-ui/issues/1309#issuecomment-478968843)

fix(Button): fix paddings for medium size in flat theme

---

packages/retail-ui/scripts/git/index.js
packages/retail-ui/scripts/package/__tests__/package.test.js
packages/retail-ui/scripts/package/index.js

Обновил механизм определения ветки и тега при выпуске релизов.
Старый метод не работал, когда происходил checkout тега на TeamCity. В таком состоянии HEAD уже не указывает ни на одну из веток. Более надежно смотреть на ссылки на текущую ревизию в upstream-репозитории.

chore: branch and tag determination

---

packages/retail-ui/components/Modal/Modal.tsx
packages/retail-ui/components/Modal/__tests__/Modal-test.tsx

Убрал нежелательное закрытие модалки после клика по скроллбару.
История вопроса. 
- Изначально, для закрытия модалки по клику на фоне, просто слушался клик на контейнере, с проверкой на `target === currentTarget`, пока не обнаружили #757. 
- После чего добавили другой элемент `сlickTrap`, на котором стали слушать клики, пытаясь его растянуть по размеру контейнера, но работало плохо #810, #1352.
- Потом отказались от `сlickTrap`, вернулись на контейнер и стали слушать `mouseDown` , чтобы обойти #757. Но возникла проблема #1456.
- Наконец, вернул самый простой клик на контейнере с проверкой на то, что он начался и закончился на нем же, для обхода #757.
fix #1456

fix(Modal): don't close by click on scrollbar

---

packages/retail-ui/components/Input/Input.tsx
packages/retail-ui/components/Input/__tests__/Input-test.tsx

Причина https://github.com/facebook/react/issues/7769
Fix #1413

fix(Input): add calling 'selectAll' via 'setTimeout'

---

packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/clicked/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/clicked/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/clicked/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/enterPress/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/enterPress/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/enterPress/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/focused/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/focused/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/focused/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/hovered/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/hovered/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/hovered/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/mouseLeave/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/mouseLeave/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/mouseLeave/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/plain/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/plain/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/plain/ie11.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/tabPress/chrome.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/tabPress/firefox.png
packages/react-ui-screenshot-tests/gemini/screens/tabs disabled/tabPress/ie11.png
packages/react-ui-screenshot-tests/gemini/tabs.js
packages/retail-ui/components/Tabs/Tab.less
packages/retail-ui/components/Tabs/Tab.styles.ts
packages/retail-ui/components/Tabs/__stories__/Tabs.stories.tsx

1. Убрал ховер на `disabled` вкладках 
2. Добавил скриншотов
3. Добавил цветных бордеров для вертикальных вкладок, как у горизонтальных
fix #1504

fix(Tab): remove hover border from disabled tabs

---

packages/retail-ui/components/Radio/Radio.tsx

Typescript очень долго обрабатывает компонент Radio (~ 1 мин). Самое безболезненное и простое решение, которое нашел - избавиться от propTypes. Они используются только для дополнительной проверки пропов в рантайме (в dev режиме).
Как воспроизвести проблему:
```
mkdir test-radio && cd test-radio
yarn init -y
yarn add @types/react @types/react-dom typescript @skbkontur/react-ui
echo "import React from 'react'; import Radio from '@skbkontur/react-ui/Radio'; <Radio value='' />" > index.tsx
yarn tsc index.tsx --skipLibCheck --jsx react --module commonJs --esModuleInterop
```
fix #1518

fix(Radio): decrease types checking time

---

packages/retail-ui/components/Group/Group.less

Убрала `vertical-aling: bottom` у `Group`, чтобы нормально работало выравнивание. Раньше это было нужно для поддержки IE8, сейчас уже не требуется.
Fix https://github.com/skbkontur/retail-ui/issues/1537

fix(Group): removed vertical-align

---

packages/react-ui-selenium/images/Button/disabled combinations/page - 1/chromeFlat/page - 1.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 1/firefoxFlat/page - 1.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 1/ie11Flat/page - 1.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 2/chromeFlat/page - 2.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 2/firefoxFlat/page - 2.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 2/ie11Flat/page - 2.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 3/chromeFlat/page - 3.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 3/firefoxFlat/page - 3.png
packages/react-ui-selenium/images/Button/disabled combinations/page - 3/ie11Flat/page - 3.png
packages/react-ui-selenium/images/Button/loading combinations/page - 1/chromeFlat/page - 1.png
packages/react-ui-selenium/images/Button/loading combinations/page - 1/firefoxFlat/page - 1.png
packages/react-ui-selenium/images/Button/loading combinations/page - 1/ie11Flat/page - 1.png
packages/react-ui-selenium/images/Button/loading combinations/page - 2/chromeFlat/page - 2.png
packages/react-ui-selenium/images/Button/loading combinations/page - 2/firefoxFlat/page - 2.png
packages/react-ui-selenium/images/Button/loading combinations/page - 2/ie11Flat/page - 2.png
packages/react-ui-selenium/images/Button/loading combinations/page - 3/chromeFlat/page - 3.png
packages/react-ui-selenium/images/Button/loading combinations/page - 3/firefoxFlat/page - 3.png
packages/react-ui-selenium/images/Button/loading combinations/page - 3/ie11Flat/page - 3.png
packages/retail-ui/components/variables.flat.less

У плоской кнопки фон и тень стрелки в состоянии `disabled` отличаются от [фигмы](https://www.figma.com/file/FTSaUIW3EUjCzOwZfP7II9/Kontur-UI-Flat?node-id=1450%3A9). Неверные значения `@btn-flat-disabled-bg` и `@btn-flat-disabled-shadow-color`, по факту, применяются [только к стрелке](https://github.com/skbkontur/retail-ui/blob/7481e502cae1dd3cef8a2ef8dc05151d9b67881e/packages/retail-ui/components/Button/Button.styles.ts#L176-L177), с самой кнопкой все норм.

fix(Button): change disabled bg & shadow for the FlatTheme

---

packages/retail-ui/components/Button/Button.module.less
packages/retail-ui/components/Button/Button.styles.ts
packages/retail-ui/components/Modal/Modal.module.less
packages/retail-ui/components/Modal/Modal.styles.ts
packages/retail-ui/components/Radio/Radio.module.less
packages/retail-ui/components/Tabs/Tab.module.less
packages/retail-ui/components/Tabs/Tab.styles.ts
packages/retail-ui/components/Textarea/Textarea.module.less
packages/retail-ui/components/Textarea/Textarea.styles.ts
packages/retail-ui/components/Toast/ToastView.module.less
packages/retail-ui/components/Toggle/Toggle.module.less
packages/retail-ui/components/variables.flat.less
packages/retail-ui/components/variables.less

Перенес все стили, которые ломаются code-splitting'ом, в JS.
#1625

chore(retail-ui): move critical styles from less to js

---

packages/retail-ui/components/Input/Input.styles.ts
packages/retail-ui/components/ThemeShowcase/ThemeShowcaseHelpers/FormatSourceCode.tsx

Усилили регулярку, чтобы корректно обрабатывать несколько шаблонных строк в одном наборе стилей. Например, в таком:
```
blink(t: ITheme) {
const blinkAnimation = keyframes`
0% {
background-color: ${t.blinkColor};
}
`;
return css`
.${classes.root}& {
animation: ${blinkAnimation} 0.15s ease-in;
}
`;
},
```
Также, пофиксили рендер имен классов после #1572 и #1629

fix(docs): fix code formatter of the ThemeShowcase

---

packages/retail-ui/components/ThemeProvider/Playground/darkTheme.ts
packages/retail-ui/components/variables.flat.less
packages/retail-ui/components/variables.less

Закрывает https://github.com/skbkontur/retail-ui/issues/1646
Чисто на глаз `0088FF` с 20% прозрачности для светлой и 40% для темной выглядит лучше всего.

fix(ThemeProvider): 'blinkColor' fix for darkTheme

---

packages/retail-ui/components/internal/InternalMenu/InternalMenu.tsx
packages/retail-ui/components/internal/InternalMenu/__tests__/InternalMenu-test.tsx

У `MenuItem` расположенного в `Menu` не вызывались пиропы `onMouseEnter/Leave`

fix(MenuItem): call onMouseEnter/Leave in cloned element

---

.vscode/settings.json

Опции устарели, рекомендуют использовать `fixAll` https://github.com/prettier/prettier-vscode#linter-integration

chore: replace deprecated prettier options

---

packages/retail-ui/components/Modal/Modal.module.less

Добавил css word-break: break-word  для Modal.Header, чтобы избегать проблем с оченьДлиннымиЗагловкамиМодалкиБезПробелов, которые ломают хедер при фиксированой ширине модалки

fix(Modal): added word-break: break-word to Modal.Header

---

packages/retail-ui/components/PasswordInput/PasswordInput.tsx

При использовании контролов с typescript 3.7 вываливается ошибка:
```
node_modules/@skbkontur/react-ui/components/PasswordInput/PasswordInput.d.ts:3:10 - error TS2440: Import declaration conflicts with local declaration of 'InputProps'.
3 import { InputProps } from '../Input/Input';
~~~~~~~~~~
Found 1 error.
```

refactor(PasswordInput): remove unused type declaration

---

packages/retail-ui/components/TokenInput/TextWidthHelper.tsx

Importing from the 'all.ts' causes all the components from it to be included in the bundle.

fix(TokenInput): fix module import

---

packages/react-ui-validations/package.json
packages/retail-ui/package.json
yarn.lock

close #1769 
Прогнал `yarn-deduplicate -s fewer` и синхронизировал версии между retail-ui и react-ui-validations.
Сбросили 128 MB зависимостей!
До:
```
737M	node_modules
1008K	packages/retail-ui/node_modules
28K	packages/react-ui-validations/node_modules
```
После:
```
609M	node_modules
1.1M	packages/retail-ui/node_modules
28K	packages/react-ui-validations/node_modules
```
PS: ветка основана на #1817. После его влития нужно будет отребэйзить на next.

build: deduplicate and sync deps versions

---

packages/retail-ui/.creevey/images/Gapped/Dont Cover Other Elements/click/chrome.png
packages/retail-ui/.creevey/images/Gapped/Dont Cover Other Elements/click/firefox.png
packages/retail-ui/.creevey/images/Gapped/Dont Cover Other Elements/click/ie11.png
packages/retail-ui/.creevey/images/Gapped/Horizontal/chrome.png
packages/retail-ui/.creevey/images/Gapped/Horizontal/firefox.png
packages/retail-ui/.creevey/images/Gapped/Horizontal/ie11.png
packages/retail-ui/.creevey/images/Gapped/Vertical/chrome.png
packages/retail-ui/.creevey/images/Gapped/Vertical/firefox.png
packages/retail-ui/.creevey/images/Gapped/Vertical/ie11.png
packages/retail-ui/.storybook/webpack.config.js
packages/retail-ui/components/Gapped/Gapped.tsx
packages/retail-ui/components/Gapped/__stories__/Gapped.stories.tsx
packages/retail-ui/components/ThemeProvider/Playground/ThemeEditor.tsx
packages/retail-ui/components/ThemeProvider/Playground/VariableValue.tsx
packages/retail-ui/lib/theming/Emotion.ts
packages/retail-ui/package.json
packages/retail-ui/prod.tsconfig.json
packages/retail-ui/tsconfig.json
packages/retail-ui/typings/mocha/index.d.ts
packages/retail-ui/typings/stylis-plugin-extra-scope.d.ts
yarn.lock

- Заинлайнил код пакета `stylis-plugin-extra-scope`, так как на него не было тайпингов, а Creevey по какой-то причине не могу подгрузить тайпинги описанные в typings директории контролов
- Обновил Creevey до 0.2.4, были баги связанные с сериализацией skip опции вебдрайверами и за одно поправил загрузку тестов из стори по правильному имени стори
- Добавил тестов на Gapped
- Удалил `margin-top` при использовании горизонтального лейаута

fix(Gapped): don't cover other elements with horizontal layout

---

packages/react-ui-testing/react-selenium-testing.js
packages/retail-ui/components/Button/Button.tsx
packages/retail-ui/components/Radio/Radio.tsx
packages/retail-ui/components/RadioGroup/RadioGroup.tsx

Подробности в #1866.
Выяснилось, что поля `_node` в Fiber'е нет. Оно использовалось до 16.0.0, но уже мертвый код был выпилен только в [16.1.0](https://github.com/facebook/react/pull/10794).
Кроме этого, отрефакторил компоненты для порядка и чтобы работало со старым react-selenium-testing.
PR #1480 про то же, но решение не работает.
fix #1866 
close #1480

fix(react-selenium-testing): attributes on wrong element

---

packages/react-ui-validations/loaders/markdown-loader.js

Обновили raw-loader с 0.5.1 до 4.0.0. А он c 1.0.0 стал возвращать es-модули.
На сайте доку я уже передеплоил.
fix #1975

docs(react-ui-validations): fix source code examples

---

packages/react-ui-smoke-test/package.json
packages/react-ui-smoke-test/smoke.test.ts
yarn.lock

Починка смок-тестов.
На TeamCity стали завершаться процессы, ранее подвешиваемые инструкцией `process.stdin.resume()`. Из-за чего WebpackDevServer стал вырубаться [сразу после запуска](https://github.com/react-workspaces/create-react-app/blob/473b8200f5fa3c57920533622a2fabd401e2dc75/packages/react-scripts/scripts/start.js#L175).
Причину до конца выяснить пока не удалось. Единственное отличие с локальным запуском в том, что на TC в stdin процессу приходит Socket, а не TTY. Видимо, что-то кроется в этом. Девопсы говорят, что на агентах обновился только .net core sdk 3.1.200.
Как вариант, можно перейти на запуск сбилженного приложения пакетом `serve`. Но CRA из коробки позволяет билдить только для прода. Соответственно, в ходе смок-теста мы теряем варнинги, которые выводятся только в …

fix(smoke-test): fix server launch on ci

---

packages/react-ui/components/Textarea/Textarea.tsx

```code
Warning: Unknown event handler property `onValueChange`. It will be ignored.
in textarea (created by Context.Consumer)
in label (created by Context.Consumer)
in Textarea
```

fix(textarea): fix react warning

---

packages/react-ui/MIGRATION.md
packages/react-ui/components/Fias/Fias.tsx
packages/react-ui/components/Fias/FiasSearch/FiasSearch.tsx
packages/react-ui/components/Loader/Loader.tsx
packages/react-ui/components/Logotype/Logotype.tsx
packages/react-ui/components/Spinner/Spinner.tsx
packages/react-ui/components/TopBar/TopBar.tsx
packages/react-ui/internal/SpinnerOld/SpinnerOld.tsx
packages/react-ui/lib/theming/ThemeContext.md

Поправил ссылки на migration guide и дополнил его. Поправил примерчики про ThemeContext.
fix #1978

docs(react-ui): migration guide and customization docs fixes

---

packages/retail-ui/components/TokenInput/TokenInput.tsx

В проп "renderAddButton" прокинул метод для добавления элемента для сохранения общего поведения инпута
Очень нужны эти изменения в 0.53 версии, по возможности добавьте
close #2003

feat(TokenInput): new parameter 'onAddItem' in 'renderAddButton' prop

---

packages/react-ui/.creevey/images/SidePage/Simple/open side-page/chrome/open side-page.png
packages/react-ui/.creevey/images/SidePage/Simple/open side-page/firefox/open side-page.png
packages/react-ui/components/SidePage/SidePage.styles.ts
packages/react-ui/components/SidePage/SidePage.tsx
packages/react-ui/internal/ZIndex/__stories__/ZIndex.stories.tsx

Поменял элемент, который управлял шириной SidePage, на самый корневой. Теперь он не блокирует страницу.
Контейнер тени рисуется только при необходимости, чтобы тоже не блокировал.
Немного отрефакторил стили оверлея.
fix #1949

fix(SidePage): don't block the page

---

packages/react-ui/components/Tooltip/Tooltip.styles.ts

fix(Tooltip): set default value for `box-sizing`, due to `reset.css`

---

packages/react-ui/internal/MaskedInput/MaskedInput.tsx

`Edge` пытался создать ссылку из набора цифр, похожих на номер телефона.
Отключил такое поведение специальным атрибутом - [`x-ms-format-detection`](https://docs.microsoft.com/en-us/previous-versions/dn337007(v=vs.85)
).
Fixes #1911

fix(MaskedInput): add specific property of the IE/Edge

---

packages/react-ui/components/Input/Input.tsx
packages/react-ui/internal/MaskedInput/MaskedInput.tsx

Проблема в том, что в инпуте, при наличии маски, подключается `MaskedInput`, и вырезается обработчик `onKeyDown`.
Перенёс обработчик горячих клавиш с инпута на его обёртку.
Fixes #1938

fix(Autocomplete): move `onKeyDown` on `span`, instead of `Input`

---

packages/react-ui/components/SidePage/SidePage.tsx

Не рискнул менять `mousedown` на `click`. А ну как прорвёт где-нибудь...
Оставил решение только для одного случая.
Fixes #1934
---
<details><summary>Старое решение</summary>
Поэтому вкинул хелпер для вычисления клика по скроллбару, если он есть.
В разных браузерах и системах(`win10`/`macOS`) есть существенные отличия, касательно скроллбара, что не позволяет реализовать единое решение.
Все проблемы касаются `macOS` и браузеров `safari`, `chrome` и `firefox` (другие не проверял).
Уже реализованным способом, можно определить клик по скроллбару только на `html`/`body` и только при дефолтном значении `dir` - `ltr`.  В других `html`-элементах практически невозможно идентифицировать место клика.
Однако, в `firefox` не работает и этот сценарий.
| Detect...\OS(browser) | win10(all) | mac(safari) | …

fix(SidePage): add ignore clicks on scrollbars

---

packages/react-ui/components/Tooltip/Tooltip.tsx

Раскопал проблему производительности с Tooltip-ом.
- Tooltip рендерит RenderLayer и в зависимости от `props.trigger` передает (или не передает) ему пропсы
- Если RenderLayer-у Tooltip не передает пропсы, то ему передается `{ active: true }`, если передает пропсы, но там нет `props.active`, то RenderLayer берет значение из `defaultProps.active = true`
- RenderLayer, когда `props.active = true` делает 3 глобальные подписки: на fous, blur и click на `document` (клик в любое место поджигает обработчик click)
- Проблема всплывает в ValidationWrapper, который рендерит Tooltip c `props.trigger = "hover&focuse"`. Раньше `active` не заполнялось Tooltip-ом, поэтому бралось из `dafualProps.active = true`. Получается, что даже если Tooltip валидации не появлялся, он все равно обрабатывает 3 эвента, …

Производительность Tooltip

---

packages/react-ui/package.json
packages/react-ui/scripts/build/index.js

1. Сделал полное копирование `package.json` при паблише. Чтобы избежать такого, что, например, забыли скопировать `sideEffects: false` и tree-shaking не работал.
2. Добавил в паблиш традиционные файлы `LICENSE` и `CHANGELOG.md`.

build(react-ui): revise publishing files

---

.gitignore
.npmrc
.yarnrc
packages/react-ui/.yarnrc

На агентах TeamCity кто-то проставил кривоватый registry в конфиг yarn:
```
registry: '\'https://nexus.kontur.host/repository/kontur-npm-group/\''
```
Привело к тому, что перестала корректно работать команда `npx create-react-app@next ...` в smoke-тестах.
Явная установка регистра в наших конфигах должна оградить нас от такого в будущем.

build: explicitly set npm registry

---

packages/retail-ui/components/Gapped/Gapped.tsx
packages/retail-ui/components/Gapped/__stories__/Gapped.stories.tsx
packages/retail-ui/components/Gapped/__tests__/Gapped-test.tsx

Убрал добавление margin-left если в children должен отображаться один элемент
close #2036

fix(Gapped): fix left margin for single child

---

packages/retail-ui/components/Kladr/KladrAPI.js

С сервера могут приходить полностью `null`-евые объекты.
Добавил фильтр на уровне апи для таких пустышек.
|  `null`-евой объект с сервера |
| --- |
| ![image](https://user-images.githubusercontent.com/2708211/86314942-5f3e4000-bc42-11ea-83a7-250690f70588.png) |
---
Fixes https://yt.skbkontur.ru/issue/keforms-4079

fix(Kladr): add filter for "empty" addresses from backend

---

.teamcity/settings.kts
packages/react-ui-testing/SeleniumTesting.sln
packages/react-ui-testing/SeleniumTesting/SeleniumTesting.csproj
packages/react-ui-testing/Tests/Helpers/AssertionExtensions.cs
packages/react-ui-testing/Tests/KebabTests/KebabTest.cs
packages/react-ui-testing/Tests/ListTests/ListTest.cs
packages/react-ui-testing/Tests/Tests.csproj
packages/react-ui-testing/package.json

Хочется иметь возможность подключать SeleniumTesting в netstandard-сборку с тестовыми хелперами, сейчас возникают нелепые ворнинги если так делать
fixes #2085

fix(react-ui-testing): target netstandard2.0 instead of netcoreapp2.1

---

packages/react-ui-validations/src/ValidationContainer.tsx
packages/react-ui-validations/src/ValidationContext.tsx
packages/react-ui-validations/src/ValidationWrapperInternal.tsx

Проблема: падают e2e тесты, при проверке валидаций.
Поведение:
1) есть большая форма в модальном окне на несколько экранов, в самом низу, соответственно, `submit`;
2) вводим невалидные данные в инпуты, нажимаем на `submit`, проверяем валидацию;
3) вьюпорт плавно скроллится наверх к невалидному полю;
4) тест падает, потому что пытается сразу проверить валидацию в тултипе, а вьюпорт еще не поднялся до нужного поля. Сейчас, в проекте, это костыльно решено при помощи ожидания в секунду-две;
Что сделал в этом PR: добавил проп в `ValidationContainer`, который позволяет отключить плавный скролл. На основании пропа и переменной окружения `NODE_ENV` определяем, юзать плавный скролл или нет. Это необходимо, чтобы не собирать отдельную сборку для фронта, при прогоне селениумных тестов локально. …

feat(ValidationContainer): added new prop disableSmoothScroll

---

packages/react-ui/components/Input/Input.styles.ts
packages/react-ui/components/Switcher/Switcher.styles.ts
packages/react-ui/components/Switcher/Switcher.tsx
packages/react-ui/components/Switcher/switcherTheme.ts
packages/react-ui/components/Tabs/Indicator.tsx
packages/react-ui/components/TokenInput/TokenInput.styles.ts
packages/react-ui/internal/ThemePlayground/constants.ts
packages/react-ui/internal/themes/DefaultTheme.ts
packages/react-ui/internal/themes/Theme8px.ts
packages/react-ui/lib/theming/ThemeContext.md

Общий PR с доработками 8px темы:
- Починен цвет disabled `Input`
- Восстановлена работа переменных `controlHeight*` в старых темах. В новых логика останется измененной.
- Табы в 8px по умолчанию стали `large`. Плюс настроил правильное позиционирование индикатора активного таба.
- В `Switcher` шрифт, высота строки и отступ label стали зависеть от размера. А отступы в кнопках пришли в соответсвие с 8px-макетами.
- В TokenInput заработали `tokenInputFontSize` и `tokenInputLineHeight`. Токены нужно настраивать отдельно.
Обновил ссылки:
| Default  | Default 8px | Flat  | Flat 8px |
| ------------- | ------------- |------------- | ------------- |
| [default-rust.vercel.app](https://default-rust.vercel.app/) | [default8px.vercel.app](https://default8px.vercel.app/)  | …

fix(8px): various bugs

---

packages/react-ui-testing/SeleniumTesting/Controls/ComboBox.cs

PR на [issue](https://github.com/skbkontur/retail-ui/issues/2095)
Убрал ненужный клик в начале, который приводил к нестабильностям в некоторых ситуациях. До PR протестировано на 7 сборках подряд в kontur edi, падений как на скринах в PR замечено не было.

fix(ComboBox, SeleniumTesting): fix combobox methods stability

---

packages/react-ui/components/MenuItem/MenuItem.tsx

Если я пытаюсь кастомизировать `MenuItem` через свойство `component`, то не могу пробросить состояние наведения или выбора.
Мне эта фича нужна в 0.х версии, мы еще не успели перейти на новый lts

Передавать состояние Элемента меню

---

packages/retail-ui/.npmignore

Мы хотим перейти на lts. При этом у нас еще babel6. Если попытаться собрать retail-ui пакет, то бабель смотрит на локальный `babelrc` пакета. Там указаны плагины из babel7. В итоге получаем ошибку: 
```Requires Babel "^7.0.0-0", but was loaded with "6.26.3".```
Даже если это могло бы работать, этих плагинов нет в `dependencies` пакета.
Для babel7 этот файл будет бесполезен, бабел перестал смотреть на конфиги снаружи.

fix: Добавил babelrc в игнор, чтобы он не мешался при сборке

---

packages/react-ui/components/Select/Select.styles.ts

Для тега span указана ширина 100%. Если мы добавляем иконку, то ширина иконки+span(100%) выходят за границы кнопки. Задание with: auto при наличии иконки решает эту проблему

fix(Select.styles): fix span width with left icon

---

packages/react-ui/components/Select/Select.styles.ts

Пересоздано из #2110 
> Для тега span указана ширина 100%. Если мы добавляем иконку, то ширина иконки+span(100%) выходят за границы кнопки. Задание with: auto при наличии иконки решает эту проблему

fix(Select): fix span width with left icon

---

packages/react-ui/internal/Popup/Popup.styles.ts

Пока обновление стилей еще на подходе, это временное решение проблем с наезжающими тултипами/дропдаунами и прочими попапами.
Причина все та же (#1952). Возможны случаи, когда стили `transition-enter-*` вставляются на страницу позже `transitionEnterActive` (например, при открытии попапов с разным значением `positions`). В итоге применяется неправильное смещение. 
На витрине не воспроизводится, потому что там компонент ThemeShowcase заранее вызывает вставку всех стилей всех компонентов на страницу, и порядок их уже не меняется. 
Стоило раньше этот фикс выкатить.
fix #2005

fix(Popup): prevent wrong styles order

---

packages/react-ui-validations/package.json
packages/react-ui-validations/src/ReactUiDetection.ts

Убрал лишний импорт компонентов. Актуализировал версию react-ui в peerDependencies.
Немного повысилась минимальная поддерживаемая версия контролов, но не так, чтобы breaking change. Поэтому пометил как `feat`.
fix #2150

feat(react-ui-validations): optimize ReactUiDetection, inc min react-ui to 0.53.7

---

packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx

Пофиксил два постоянно мигающих теста:
| DatePicker | ComboBox |
| :--- | :--- |
| ![image](https://user-images.githubusercontent.com/4607770/94770281-a8cb3200-03cd-11eb-8290-465268e010e6.png) | ![image](https://user-images.githubusercontent.com/4607770/94770337-d1532c00-03cd-11eb-9673-30fc8a9e68ab.png) |

test(react-ui): fix flacky screenshots

---

packages/react-ui-smoke-test/smoke.test.ts

Стали [падать](https://tc.skbkontur.ru/buildConfiguration/FrontendInfrastructure_Packages_ReactUI_LintTest/19457641) smoke-тесты из-за использования create-react-app@next. Видимо там что-то [сломалось](https://github.com/facebook/create-react-app/issues/9910). Поменял на latest.

test(smoke): use latest cra version

---

packages/retail-ui/components/Modal/Modal.tsx
packages/retail-ui/components/ModalStack/ModalStack.ts
packages/retail-ui/components/SidePage/SidePage.tsx

Fixes #2197
| 1\2 | `0.53.12` | `>1.11.6` | `>2.7` |
| --- | :---: | :---: | :---: |
| `0.53.12` | ✅ | ✅ | ✅ |
| `>1.11.6` | ✅ | ✅ | ✅ |
| `>2.7` | ❌ | ✅ | ✅ |
Сейчас ошибка возникает в единственном случае, когда сначала используется `ModalStack@2.x`, а затем `ModalStack@0.x`.

fix(ModalStack): add fallback for `eventemitter3` from latest versions

---

packages/react-ui/lib/ModalStack.ts

fix(ModalStack): add fallback for `fbemitter` from old versions

---

packages/react-ui-testing/Tests/TestEnvironment/Browser.cs

На гриде перестали проходить селениумные тесты, с ошибкой:
"OpenQA.Selenium.WebDriverException : unsupported browser: chrome-70-Windows 10"
idevops:
> указывайте в качестве платформы "windows", а не "Windows 10"
> раньше у нас были только виндовые ноды потому поле платформа просто игнорилась
но недавно мы стали заводить линуксовые ноды, потому поле стало выполнять свою функцию

fix(SeleniumTesting): set up correct platform for webdriver

---

packages/react-ui/.storybook/preview.tsx
packages/react-ui/lib/styles/HoldSelectionColor.ts

Зафиксировал фоновый цвет выделения текста для скриншотных тестов.
Прогнал скриншоты на разных агентах (на всякий).

chore: hold color of selection for screenshot tests

---

packages/react-ui/components/Sticky/Sticky.tsx

fix #2291
Проверил тест кейсы в сторибуке
Проверил кейсы из комментариев в чате 
> Там ие криво размеры считал когда стики было прижато к низу страницы. Стики доезжал до низа, видел что вроде как он может перестать стикаться, встраивался обратно, размер страницы менялся, он снова стикался, снова менялся размер и так далее
это фиксит [коммит](/skbkontur/retail-ui/pull/1481/commits/0d1b9ef021dee1574bbb284f301ae273de5a4c52)
> Помнится ещё в сафари был баг с очень точным положением элемента. Значение было очень близко в окрестности ноля, но не ноль. Типа 0.00013, это приводило к бесконечному рендеру.
это фиксит [коммит](https://github.com/skbkontur/retail-ui/pull/1481/commits/85180dd741923f548a97a8c71ca47dbd2edc4026)

fix(Sticky): убрал некорректный deltaHeight

---

packages/react-ui/components/TokenInput/TokenInput.tsx

Вдогонку к #2279. Происходят лишние вызовы `onBlur`, в том числе когда фокус в реальности остается в ТокенИнпуте. Это может преждевременно запускать валидацию и также влиять на другие пользовательские сценарии.

fix(TokenInput): don't call onBlur until focus is really lost

---

packages/react-ui/.creevey/images/Toast/complex notification/toastShown/chrome.png
packages/react-ui/.creevey/images/Toast/complex notification/toastShown/firefox.png
packages/react-ui/.creevey/images/Toast/complex notification/toastShown/ie11.png
packages/react-ui/.creevey/images/Toast/simple notification/toastShown/chrome.png
packages/react-ui/.creevey/images/Toast/simple notification/toastShown/firefox.png
packages/react-ui/.creevey/images/Toast/simple notification/toastShown/ie11.png
packages/react-ui/.creevey/images/Toast/static method/toastShown/chrome.png
packages/react-ui/.creevey/images/Toast/static method/toastShown/firefox.png
packages/react-ui/.creevey/images/Toast/static method/toastShown/ie11.png
packages/react-ui/.creevey/images/ToastView/simple toast/chrome.png
packages/react-ui/.creevey/images/ToastView/simple toast/firefox.png
packages/react-ui/.creevey/images/ToastView/simple toast/ie11.png
packages/react-ui/.creevey/images/ToastView/with action/chrome.png
packages/react-ui/.creevey/images/ToastView/with action/firefox.png
packages/react-ui/.creevey/images/ToastView/with action/ie11.png
packages/react-ui/.creevey/images/ZIndex/Modal And Toast/toastShown/chrome.png
packages/react-ui/.creevey/images/ZIndex/Modal And Toast/toastShown/firefox.png
packages/react-ui/.creevey/images/ZIndex/Modal And Toast/toastShown/ie11.png
packages/react-ui/components/Center/Center.tsx
packages/react-ui/components/Toast/Toast.tsx
packages/react-ui/components/Toast/ToastView.tsx
packages/react-ui/components/Toast/__stories__/Toast.stories.tsx
packages/react-ui/components/Toast/__stories__/ToastView.stories.tsx
packages/react-ui/components/TopBar/TopBarDropdown.tsx
packages/react-ui/components/TopBar/TopBarItem.tsx
packages/react-ui/components/TopBar/TopBarLogout.tsx
packages/react-ui/components/TopBar/TopBarOrganizations.tsx
packages/react-ui/internal/ZIndex/__stories__/ZIndex.stories.tsx

Были найдены некоторые проблемы после #2257: 
- Toast 
- Center 
- TopBarDropdown
- TopBarItem 
- TopBarLogout 
- TopBarOrganizations
А именно, в Toast и Center были допущены банальные ошибки, которые позволяли классам, переданным из вне, перезаписывать внутренние. 
А в остальных компонентах при передачи классов из вне, они могли дублироваться на обертке из-за неправильного использования `CommonWrapper` и `CommonWrapperRestProps`. Повод задуматься об удачности получившегося решения. Возможно его стоит упростить и сделать более прозрачным.
В случае Toast мы допустили регресс из-за не совсем полноценного теста, когда скриншотилась только внутрянка, а не Toast целиком. Доработал этот момент. Остальное же пока не очень понятно как можно тестировать. 
fix #2312

fix(react-ui): fix className forwarding

---

packages/react-ui/.creevey/images/Checkbox/indeterminate/clicked/chrome/clicked.png
packages/react-ui/.creevey/images/Checkbox/indeterminate/clicked/chromeFlat/clicked.png
packages/react-ui/.creevey/images/Checkbox/indeterminate/clicked/firefox/clicked.png
packages/react-ui/.creevey/images/Checkbox/indeterminate/clicked/firefoxFlat/clicked.png
packages/react-ui/.creevey/images/Checkbox/indeterminate/clicked/ie11/clicked.png
packages/react-ui/.creevey/images/Checkbox/indeterminate/clicked/ie11Flat/clicked.png
packages/react-ui/components/Checkbox/Checkbox.tsx
packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx

В IE11 и старом Egde есть особенность поведения при выходе из состояния indeterminate, при котором текущее состояние checked не меняется, в отличии от остальных браузеров. 
jquery/jquery#1698
Это приводило в тому, что иконка при первом клике по indeterminate не менялась, т.к. при этом не происходит события onChange.
Починить иконку не проблема, но остается разное поведение в разных браузерах. Это ломает тесты пользователей. Но эмулировать onChange как решение кажется не очень, ведь у нас нет полноценного объекта события (а его могут использовать). Поэтому предлагаю ограничить фикс в рамках нашего кастомного события `onValueChange`.
#2316

fix(Checkbox): fix indeterminate state in IE11/Edge

---

packages/react-ui/components/Autocomplete/Autocomplete.tsx
packages/react-ui/components/Autocomplete/__tests__/Autocomplete-test.tsx

Cherry-picked from #2268
Fix #2267

fix(Autocomplete): use prop `active` from `RenderLayer` [master]

---

packages/react-ui-testing/SeleniumTesting/Controls/Paging.cs
packages/react-ui-testing/SeleniumTesting/Controls/RadioGroup.cs
packages/react-ui-testing/SeleniumTesting/Controls/Select.cs

Версии:
- @skbkontur/react-props2attrs: 0.1.2
- @skbkontur/react-ui: 2.15.0
- react: 16.8.6
`react-props2attrs` закидывает в `data-comp-name`  в Item у Select `"MenuItem CommonWrapper"`, а обвязка ожидает только `'MenuItem"`
+ Заменил `FirstOrDefault` на `First`. Раньше, если хотя бы один item не нашли, то возвращался `null` и по этому `null` делался `.Click()` - получалась ошибка `NullReferenceException`, которая в стектрейсе ничего понятного не содержала. `First` развалится сразу, как только не найдет хотя бы один item - думаю получше будет

fix(seleniumtesting): fix selector for select menu items

---

packages/react-ui-validations/src/ReactUiDetection.ts
packages/react-ui-validations/src/ValidationTooltip.tsx
packages/react-ui-validations/stories/Switcher.stories.tsx

Фикс для https://github.com/skbkontur/retail-ui/issues/2191
- Проблема была в `span`, в который оборачивал `ValidationWrapperInternal` клонированные чайлды. В `switcher` он позиционировался в верхне левом углу, что вызывало проблемы с тултипом
- Проверил, этот спан не влияет на компоненты и работоспоспособность либы валидации

[Switcher] проблемы с валидацией

---

packages/react-ui/.creevey/images/FxInput/different sizes/chrome.png
packages/react-ui/.creevey/images/FxInput/different sizes/chrome8px.png
packages/react-ui/.creevey/images/FxInput/different sizes/firefox.png
packages/react-ui/.creevey/images/FxInput/different sizes/firefox8px.png
packages/react-ui/.creevey/images/FxInput/different sizes/ie11.png
packages/react-ui/.creevey/images/FxInput/different sizes/ie118px.png
packages/react-ui/components/FxInput/FxInput.tsx
packages/react-ui/components/FxInput/__stories__/FxInput.stories.tsx

[#1733](https://github.com/skbkontur/retail-ui/issues/1733)
Фикс для последнего пункта из раздела  _"Проблемы, которые нужно решить параллельно"_

Изменение размера кнопки в FxInput при передаче пропа size

---

packages/retail-ui/.creevey/images/ZIndex/Sticky and Loader/Sticky covers sibling Loader/chrome/Sticky covers sibling Loader.png
packages/retail-ui/.creevey/images/ZIndex/Sticky and Tooltips/Sticky covers outside Popup and DropdownContainer/chrome/Sticky covers outside Popup and DropdownContainer.png
packages/retail-ui/components/Sticky/Sticky.module.less
packages/retail-ui/components/Sticky/Sticky.tsx

В Sticky размеры элемента до и после залипания могут отличаться. Но процесс залипания/отлипания должен происходить без скачков. Поэтому внутри предусмотрен механизм компенсации разницы через margin. Но у margin есть особенность, это возможность их [схлопывания](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) или передачи эффекта на родительские элементы. Это приводило к проблемам из 2291, когда margin ошибочно двигал не только нужный элемент, но и свой родительский контейнер вместе с со stop-элементом.
Проще всего починить через `display: flex` у контейнера, т.к. он в том числе отключает схлопывание.
Выпущена тестовая версия `0.0.0-a8072451c2` на основе 1.11.7 и [codesandbox](https://codesandbox.io/s/adoring-wood-7oiux) с ней. 
Незначительно …

fix(Sticky): avoid margins collapsing

---

packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx

Улучшение производительности в Modal и SidePage.
Есть компонент `HideBodyVerticalScroll`. Он служит для скрытия скроллбара всей страницы на время открытия Modal или SidePage. Для этого он раньше при каждом рендере проверял, есть ли у первоначальной страницы (т.е. у страницы в состоянии до открытия модалки) скролл. Если есть, то он добавлял стили для его скрытия. Таким же образом, он сразу реагировал на пропажу скролла у первоначальной страницы,  удаляя свои добавленные стили. Однако, чтобы определить наличие скролла у первоначальной страницы, необходимо сперва удалить все добавленные стили, влияющие на него, а затем снова добавить, если требуется. Это приводило к постоянному добавлению/удалению стилей на `<html />`, что и сказывалось на производительности. Но зато, так обеспечивалось …

fix(Modal, SidePage, HBVS): performance

---

packages/react-ui-testing/SeleniumTesting/Browser.cs
packages/react-ui-testing/SeleniumTesting/PageBase.cs
packages/react-ui-testing/Tests/AutocompleteTests/AutocompleteTestPage.cs
packages/react-ui-testing/Tests/ButtonTests/ButtonTestPage.cs
packages/react-ui-testing/Tests/CheckBoxTests/CheckBoxTestPage.cs
packages/react-ui-testing/Tests/ComboBoxTests/ComboBoxesTestPage.cs
packages/react-ui-testing/Tests/DatePickerTests/DatePickerTestPage.cs
packages/react-ui-testing/Tests/ExposeTidToDomTests/ExposeTidToDomTestPage.cs
packages/react-ui-testing/Tests/InputTests/InputTestPage.cs
packages/react-ui-testing/Tests/KebabTests/KebabTestPage.cs
packages/react-ui-testing/Tests/LinkTests/LinkTestPage.cs
packages/react-ui-testing/Tests/ListTests/ListsTestPage.cs
packages/react-ui-testing/Tests/ModalTests/ModalsTestPage.cs
packages/react-ui-testing/Tests/PageActionAttributesTests/PageActionAttributes/Base1PageBase.cs
packages/react-ui-testing/Tests/PageActionAttributesTests/PageActionAttributes/Base2PageBase.cs
packages/react-ui-testing/Tests/PageActionAttributesTests/PageActionAttributes/PageActionAttributeTestPage.cs
packages/react-ui-testing/Tests/PagingTests/PagingTestPage.cs
packages/react-ui-testing/Tests/RadioGroupTests/RadioGroupTestPage.cs
packages/react-ui-testing/Tests/RadioTests/RadioTestPage.cs
packages/react-ui-testing/Tests/SelectTests/SelectTest.cs
packages/react-ui-testing/Tests/SidePages/SidePageTestPage.cs
packages/react-ui-testing/Tests/TestEnvironment/Browser.cs
packages/react-ui-testing/Tests/TestEnvironment/BrowserSetUp.cs
packages/react-ui-testing/Tests/TestEnvironmentFixture.cs
packages/react-ui-testing/Tests/TextAreaTests/TextAreaTestPage.cs
packages/react-ui-testing/Tests/ToastTests/ToastTestPage.cs
packages/react-ui-testing/Tests/ToggleTests/ToggleTestPage.cs
packages/react-ui-testing/Tests/TooltipTests/TooltipTestPage.cs

Привет!
Текущая реализация PageBase в конструкторе принимает RemoteWebDriver вместо IWebDriver. Это приводит к нескольким проблемам:
1. Если тестирующая система не использует SeleniumGrid, то в ней не нужно использовать RemoteWebDriver. Но сейчас PageBase привязан к конкретной реализации IWebDriver и требует именно его. Поэтому приходится писать примерно такой код для инициализации драйвера:
```C#
RemoteWebDriver webDriver = new ChromeDriver();
```
Или если в тестирующей системе с драйвером работают как с IWebDriver, но для страницы требуется передать RemoteWebDriver, то делают каст:
```C#
TestPage((RemoteWebDriver) webDriver) : base(webDriver)
{}
```
Сами разработчики Selenium в своих гайдах пишут, что в коде нужно использовать IWebDriver, вместо какой-то конкретной реализации.
2. В …

refactor(react-selenium-testing): using webdriver interface

---

packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx

Фикс регресса после #2450 и падающих скриншотов на история ZIndex. 
В нестабильно падающих скриншотах обнаружился кейс, когда на странице появлялось одновременно несколько HBVS. Но размонтировались они не всегда в порядке, обратном монтированию. Это приводило к тому, что после закрытия Modal/SidePage на странице могли остаться стили для скрытия скролла. Починил.

fix(HBVS): fix styles restoration

---

packages/react-ui/internal/themes/Theme8px.ts
packages/react-ui/lib/theming/ThemeFactory.ts
packages/react-ui/lib/theming/ThemeHelpers.ts
packages/react-ui/lib/theming/themes/DefaultTheme8px.ts
packages/react-ui/lib/theming/themes/FlatTheme.ts
packages/react-ui/lib/theming/themes/FlatTheme8px.ts

Продублировал небходимые правки из #2339 чтобы наладить совместимость `react-ui@2.x` и последних `react-ui-addons` (2.x).
Выпустил `@skbkontur/react-ui@0.0.0-acc8bd836b` на основе `2.17.2`.

fix(react-ui): add compatibility with addons@2.x

---

packages/react-ui/components/Radio/Radio.styles.ts
packages/react-ui/components/Radio/Radio.tsx

Нативная радиокнопка при первом клике сеттит `checked` в `true`, если `checked` не определён.
У нас в компоненте нативный инпут полностью controlled. Мы игнорируем это нативное поведение, но всё должно норм работать. Но мы также оборачиваем нативный инпут в `<label/>`, который всё-таки сеттит ему `checked` в `true`. 
Т.е. если кликнуть по такому `<Radio value="radio" />` контролу, то нативная радиокнопка станет `checked=true`, а наш контрол только рамку фокуса покажет.
Новые стили подвязались на нативный инпут - `&:hover input:checked`. В плоской теме появился артефакт, когда стили думают, что `checked=true`, но на самом деле он не тру =)
<details><summary>💎 Артефакт</summary>
https://user-images.githubusercontent.com/2708211/128408202-f89960ba-579d-4d26-a158-1bc4d9e9854e.mp4
</details> …

refactor(Radio): use prop `checked` instead of `input:checked` style

---

packages/react-ui/internal/ResizeDetector/ResizeDetector.styles.ts

Добавил прозрачности iframe'у в ResizeDetector'е, чтобы скрыть скролбары в IE, которые появлялись при маленькой высоте контейнера.
fix #2500

fix(Tab): fix low height artefact

---

packages/react-ui/components/Checkbox/Checkbox.styles.ts

fix #2517 
Стили наведения перебивали стили фокуса, исправила с помощью !important по аналогии с другими стилями чекбокса

[Checkbox] пропадают стили фокуса при наведении мышью

---

packages/react-ui/.creevey/config.js

Подправил часть скриншотов. [IF-163](https://yt.skbkontur.ru/issue/IF-163)
Чинит мигающие скриншоты в ИЕ (с красными точками):
> На [вики](https://wiki.skbkontur.ru/pages/viewpage.action?pageId=418699157) в основном про линуксовые ноды (у нас пока на нем работает хром).
> И [отдельно](https://git.skbkontur.ru/ke/keweb.front/-/blob/f25788b0c0fce83b762e1b51553683e4d30484bd/.creevey/readme.md#debug) про ноды на Windows (для наших firefox и IE11).
Появилась переменная для активации дебага `process.env.DEBUG_SCREENSHOTS`. Ее можно включать при ручном запуске скриншотов на ТС, и смотреть как гоняются скриншоты.
Дальше по инструкциям.

test(screenshots): disable anti-aliasing detection

---

packages/react-ui-codemod/README.md
packages/react-ui-codemod/addons-3/__tests__/transformThemeVars.test.ts
packages/react-ui-codemod/addons-3/renameThemeVars.ts

Добавил кодмод и тесты для Аддонов 3.0. Конкретно, для переименованных переменных из [122](https://git.skbkontur.ru/ui/ui-parking/-/merge_requests/122).
Выпустил тестовую версию `react-ui-codemod@1.1.0-beta.4`.
Можно проверить так:
```
npx react-ui-codemod@1.1.0-beta.4 addons-3/renameThemeVars.ts FILES
```

feat(react-ui-codemod): add codemod for addons 3.0

---

packages/react-ui/internal/InputLikeText/InputLikeText.tsx
packages/react-ui/internal/InputLikeText/__tests__/InputLikeText-test.tsx

Правка замечания [из чата](https://kontur.slack.com/archives/C013HTCE18Q/p1635754761115000). Когда `value` рендерится в пустую строку, комбобокс перестал отрисовывать плейсхолдер. Это поведение отличается от предыдущего и не соответствует поведению нативного инпута. Поправил.
Причем, при фокусе плейсхолдер появляется.
[Демо](https://codesandbox.io/s/affectionate-dubinsky-ddj69).

fix(ComboBox): render placeholder instead of empty string value

---

packages/react-ui/components/RadioGroup/RadioGroup.tsx

Пользователь обратился с проблемой, что после обновления typescript с 3.7 до 4.4.3 и react-ui с 2.7 до 3.7.1 появились ошибке с типами RadioGroup.
После удаления из propTypes пропов с дженериком проблема пропала. Похоже на пункт 2 из #1814.
Попутно поправил доку пропов, перенеся комментарии из propTypes в интерфейс, где они заработали.

fix(RadioGroup): fix problems with value type inference

---

packages/react-ui/internal/Calendar/Calendar.tsx

Сложно в e2e тесте найти выпадашку с календарем. есть только `Monthview__month`, но их много. Хочется один атрибут для всей выпадашки.
влейте пожалуйста в LTS

Добавить data-tid для календаря

---

packages/react-ui/internal/Popup/Popup.tsx

В Сафари видимо проблемы  с css-свойством `filter: drop-shadow(...)`. Перевел на фолбэк с box-shadow для IE.
fix #2459 fix #1677
Возможно также фиксит #1495, нужно потестить на iOS.

fix(Popup): fix shadow in Safari

---

packages/react-ui/components/TokenInput/TokenInputMenu.tsx
packages/react-ui/components/Tooltip/Tooltip.tsx
packages/react-ui/internal/Popup/Popup.tsx
packages/react-ui/internal/Popup/PopupHelper.tsx

Фикс [проблемы из чата](https://kontur.slack.com/archives/C013HTCE18Q/p1636375441135000). 
До этого момента, Popup не менял позицию автоматически, если он не помещался во вьюпорт, но мог быть в него проскролен. Это специфичное поведение создавалось для Tooltip (#1195). Остальные выпадашки скорее должны менять позицию сразу при выходе за вьюпорт и обратно, по аналогии со старым движком выпадашек DropdownMenu. 
Поменял эту ситуацию, вынеся специфику в отдельный проп и заиспользовав его в Tooltip.
Остальные компоненты, построенные на Popup (TokenInput/Kebab/DropdownMenu/TooltipMenu) теперь будут всегда перестаивать свою позицию, при наличии вариантов в пропе `positions`.

feat(Popup): adjust position to fit viewport automatically

---

packages/react-ui/components/Radio/Radio.md
packages/react-ui/components/Radio/Radio.tsx

Улучшил документацию контрола `Radio`: добавил пример и изменил существующий, изменил и дополнил описание пропов и добавил описание самого контрола.
Пропы `pressed`, `hovered` и `active` существуют в этом контроле только номинально. Нужно либо понять зачем они изначально были добавлены и восстановить заложенное поведение, либо удалить их из `API` контрола. Не вижу особого смысла в этих пропах.

docs(Radio): enhance documentation

---

packages/react-ui/components/Link/Link.mixins.ts
packages/react-ui/components/Link/Link.tsx

Вынес все запреты на действия у ссылки с состояниями `loading` и `disabled` в этот PR, чтобы избежать конфликтов при мёрже и не множить PR'ы.

fix(Link): prohibit actions on link with disabled and loading states

---

packages/react-ui/components/Button/Button.md
packages/react-ui/components/Button/Button.tsx

Улучшил документацию контрола `Button`: добавил новые примеры, дополнил описание старых, добавил описание для пропов.
Проп `focused` передаётся в этот контрол только номинально. Нужно понять нужен ли он и затем восстановить поведение, либо удалить его.
У пропа `arrow` неконсистентное `API`. Сейчас у пропа `arrow` такой тип: `arrow?: boolean | "left"`. Правильно было бы временно изменить тип пропа на `arrow?: boolean | "left" | "right"` и в  одном из мажорных релизов избавиться от `boolean` поменяв тип на `arrow?: "left" | "right"`.
С пропами  `focused`, `warning` и `error` та же проблема, что и в [#2606](https://github.com/skbkontur/retail-ui/pull/2606#discussion_r740847532).

docs(Button): enhance documentation

---

packages/react-ui/lib/forwardRefAndName.ts

Декоратор для проброски `displayName`, `__KONTUR_REACT_UI__` и `ref` в компонент.

chore(forwardRefAndName): decorator for forwarding name and ref to component

---

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx

Из обращения в личке:
> в сочетании с комбобоксом при наличии данных в тултипе - не срабатывает на блюр при смене значения в комбобоксе. В Хроме.
Как воспроизвести:
1. В [первом примере](https://tech.skbkontur.ru/react-ui/#!/Components/ComboBox/ComboBox/1) в доке установить триггер Тултипу в `focus` 
2. Зафокуситься в Комбобокс, выбрать любое значение
3. Сбросить фокус из Комбобокса
4. Тултип не закрывается
Похоже, дело в той же проблеме с событием focusout, что была ранее в firefox (#2485). Распространил прошлый фикс на все браузеры и подправил тесты.

fix(ComboBox): fix blur in Chrome

---

packages/retail-ui/components/Checkbox/Checkbox.tsx
packages/retail-ui/components/Radio/Radio.tsx
packages/retail-ui/lib/events/fixFirefoxModifiedClickOnLabel.ts

Cherry-picked from https://github.com/skbkontur/retail-ui/pull/2686

fix(Checkbox,Radio): firing events onChange manually for Firefox (for 1.12)

---

packages/react-ui/internal/CommonWrapper/CommonWrapper.tsx
packages/react-ui/lib/withClassWrapper.tsx

При использовании `withClassWrapper` и полной деструктуризации объекта `props`, на `DOM` ноду падает `instanceRef="[object object]"`. Проп `instanceRef` приходит из классовой обёртки.
```tsx
<div {...props} />
```
Один из самых простых вариантов решения проблемы: не пускать проп `instanceRef` на `DOM` ноду.
```tsx
const { instanceRef, ...rest } = props;
return <div {...rest}/>
```
Для этого придётся расширить тип `CommonProps`, что вызовет ещё больше путаницы с деструктурированием пропов в `CommonWrapper`, эта проблема может быть решена используя другой механизм слияния пропов из #2669.

chore(InstanceRefType): create InstanceRefType interface

---

packages/react-ui/components/Loader/Loader.tsx

IE11 и старые браузеры не поддерживают `NodeList.prototype.forEach`.
Fix #2697

fix(Loader): use `forEach` from `Array`

---

packages/react-ui/components/RadioGroup/RadioGroup.tsx

Фикс проблемы с типами [из чата](https://kontur.slack.com/archives/C013HTCE18Q/p1637761453189500). Помогло удаление children из интерфейса пропов, который был добавлен в #2607 (@skbkontur/react-ui@3.8.4).

fix(RadioGroup): fix types inference

---

packages/react-ui/components/TokenInput/TokenInput.tsx

fix(TokenInput): add handling Enter for TokenInputType.WithoutReference
Добавила обработку нажатия Enter в handleInputKeyDown для TokenInputType.WithoutReference.
https://github.com/skbkontur/retail-ui/issues/2527

fix(TokenInput): add handling Enter for TokenInputType.WithoutReference

---

packages/react-ui/components/TokenInput/TokenInput.tsx

Дубль #2706  для прогона тестов.

fix(TokenInput): handle Enter for TokenInputType.WithoutReference

---

packages/react-ui/lib/theming/AnimationKeyframes.ts

Анимация спиннера в Сафари работает неправильно 
Нашла информацию, что Сафари [не поддерживает отрицательные значения для `stroke-dashoffset`](https://stackoverflow.com/questions/37246113/svg-stroke-dashoffset-not-working-on-safari)
Но на самом деле большую роль сыграло добавление знака `%` к `stroke-dashoffset: 0%`

Анимация спиннера в Сафари

---

packages/react-ui/lib/__tests__/extractDataProps-test.ts
packages/react-ui/lib/utils.ts

Создал утилиту для извлечения `data-` атрибутов из пропов. 
Эта утилита нужна, когда нужно прокинуть `data-` атрибуты не на тот компонент, на который падают `...rest` пропы.
Такая нужда есть например у компонента `Checkbox`(#2744) и `Radio` (#2752). Конкретно в этих двух компонентах уже есть эта утилита, добавил её, чтобы не забыть, что эти компоненты в ней нуждаются: проще пофиксить возможные конфликты, чем неправильную передачу пропов.

:fire: chore(extractDataProps): utility for extracting data props out of all props

---

packages/react-ui/test-setup.js

Добавил `jest-dom` в `test-setup`, чтобы не приходилось постоянно её экспортировать.
Также изменил комментарий, в котором говорилось, что если проект использует версию `jest` >= 25.1.0, то нужно удалить `MutationObserver`. Потому что в `jest@25.1.0` [обновили](https://github.com/facebook/jest/blob/main/CHANGELOG.md#chore--maintenance-21) `jsdom` до 15-ой версии:
```
[jest-environment-jsdom] [BREAKING] Upgrade JSDOM from v11 to v15
```
Но нам не подходит это решение, так как в проекте используется `react-dom`, вместо `jsdom`.

:fire: test(test-setup): make jest-dom part of test-setup & change confusing comment

---

packages/retail-ui/components/RadioGroup/RadioGroup.tsx

Из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1644295772338949).
Подробности здесь https://github.com/skbkontur/retail-ui/pull/2772
Taken from https://github.com/skbkontur/retail-ui/pull/2772/commits/b545df8ba0700a159c66640a3597a792703c94dd
Fix https://yt.skbkontur.ru/issue/IF-336

fix(RadioGroup): Сделал `null` значением для сброса [1.6.x]

---

packages/react-ui-smoke-test/cra-template-react-ui/template.json

Обновить стоило в любом случае, но сейчас поводом стала ошибка:
```diff
-TS2589: Type instantiation is excessively deep and possibly infinite.
```
Подробности здесь https://github.com/skbkontur/retail-ui/pull/2760#issuecomment-1038043977

test(smoke): bump `typescript` from ~3.7.4 to 4.2.4

---

packages/react-ui/components/SidePage/SidePage.tsx
packages/react-ui/components/SidePage/SidePageContext.ts
packages/react-ui/components/SidePage/SidePageHeader.tsx
packages/react-ui/components/Sticky/Sticky.tsx

Из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1644214047162429). Заказчику нужен фикс в `2.17`
Подробности здесь https://github.com/skbkontur/retail-ui/pull/2763
Fix https://yt.skbkontur.ru/issue/IF-369

fix(SidePage): Исправил положение залипшего заголовка после закрытия второго SidePage

---

packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/chrome/sticky header, open and close internal side-page.png
packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/chrome8px/sticky header, open and close internal side-page.png
packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/firefox/sticky header, open and close internal side-page.png
packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/firefox8px/sticky header, open and close internal side-page.png
packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/ie11/sticky header, open and close internal side-page.png
packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/ie118px/sticky header, open and close internal side-page.png
packages/react-ui/components/SidePage/SidePage.tsx
packages/react-ui/components/SidePage/SidePageContext.ts
packages/react-ui/components/SidePage/SidePageHeader.tsx
packages/react-ui/components/SidePage/__stories__/SidePage.stories.tsx
packages/react-ui/components/Sticky/Sticky.tsx

Из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1644214047162429).
Вплоть до версии `3.7.0` была проблема с несколькими экземплярами (это когда один поверх другого). 
Когда появляется скроллбар, то `SidePadeHeader` залипает сверху. Если в это время открыть второй `SidePage`, то первый сдвинется на 20px, вместе с залипшим заголовком. А при закрытии второго, заголовок первого останется на месте.
Однако после этого коммита https://github.com/skbkontur/retail-ui/pull/2478/commits/4458332a79a143295e42ec9388ea27d0b94a7b21 баг как-бы пропал. Но только если второй `SidePage` открыть и сразу закрыть. Если в нём будет скроллбар, то при попытке поскролить Реакт развалиться из-за `Maximum update depth exceeded`.
Тут я не конца разобрался в чём именно причина. Остановился то том, что дело в …

[SidePageHeader] Исправил баги с залипшим заголовком

---

packages/react-ui/internal/ThemeShowcase/ThemeShowcase.tsx
packages/react-ui/internal/ThemeShowcase/VariablesCollector.ts

Фикс проблемы из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1646889580346469).
При извлечении всех переменных из объекта темы в список попадают лишние свойства объекта (вроде `_name`, `__emotion_styles`). Они же потом мешаются в таблице значений. Добавил проверку на соответствие свойства реальной переменной перед добавлением в список.

docs(react-ui): fix ThemeShowcase page

---

packages/react-ui/components/Button/Button.tsx

fix(Button): use default prop when "use"={null} (#2833)

---

package.json
scripts/update-package-registry.js

Добавил возможность менять регистр установки пакетов через переменную окружения. На случай временной блокировки npm.

build: use registry from env

---

packages/react-ui/components/SidePage/SidePage.styles.ts
packages/react-ui/components/Toast/Toast.styles.ts

Так как классы внутри компонента CSSTransition применяются в обход Emotion и его [cx](https://github.com/skbkontur/retail-ui/pull/2488), то возможно нарушение порядка применения стилей и возникновение багов в анимации, как в [этом случае](https://kontur.slack.com/archives/C013HTCE18Q/p1647840249775719) (комбинация кастомизации и хот-релоадинга).

fix(SidePage,Toast): fix animation bugs on hot-reloading

---

packages/react-ui-smoke-test/cra-template-react-ui/template.json

После выхода React 18 обнаружились [конфликты зависимостей](https://tc.skbkontur.ru/buildConfiguration/FrontendInfrastructure_Packages_ReactUI_LintTest/25513237?buildTab=log&focusLine=5426&linesState=4510.4515) в шаблонном проекте для smoke-тестов. Возможно дело в версии ноды на агенте (16.13.0). Локально на 16.14.0 не воспроизвелось. Временно зафиксировал 17 реакт.

test(smoke): use react 17

---

packages/react-ui-smoke-test/cra-template-react-ui/template.json

После выхода React 18 обнаружились [конфликты зависимостей](https://tc.skbkontur.ru/buildConfiguration/FrontendInfrastructure_Packages_ReactUI_LintTest/25513237?buildTab=log&focusLine=5426&linesState=4510.4515) в шаблонном проекте для smoke-тестов. Возможно дело в версии ноды на агенте (16.13.0). Локально на 16.14.0 не воспроизвелось. Временно зафиксировали 17 реакт.
[Аналогично](https://github.com/skbkontur/retail-ui/pull/2846)

test(smoke): use react 17 (lts)

---

packages/react-ui/components/DateInput/DateInput.styles.ts

fixes [IF-441](https://yt.skbkontur.ru/issue/IF-441).
Фикс проблемы [из чата](https://kontur.slack.com/archives/C013HTCE18Q/p1649661864438279). Фрагменты даты перестали выделяться при первом фокусе, что блокировало ввод с клавиатуры.
Сломалось в #2614 (3.8.4). Там дата стала выводиться всегда, вне зависимости от фокуса и переданного value, но визуально скрывалась через прозрачность, когда ненужна. Это было сделано для стабилизации ширины контрола. Однако, клики по полю стали попадать на фрагменты этой скрытой даты, что приводило к инверсии `this.isMouseDown` и попаданию `null` в `state.selected`, вместо `this.iDateMediator.getLeftmostType()`.
https://github.com/skbkontur/retail-ui/blob/e7daa6f102653bc642bbb1954abd3be1228f4c92/packages/react-ui/components/DateInput/DateInput.tsx#L250-L254 …

fix(DatePicker): fix focus and fragments selection

---

packages/react-ui-smoke-test/cra-template-react-ui/template.json
packages/react-ui-smoke-test/cra-template-react-ui/template/src/setupTests.ts
packages/react-ui-smoke-test/smoke.test.ts

Пофиксил smoke-тесты. 
После фиксирования 17-ой версии реакта в #2846 типы продолжили устанавливаться для 18-ой, что вызывало ошибки и падение теста. Зафиксировал их тоже.
Также, удалил неиспользовавшиеся настройки и зависимости.

test(smoke): fix type errors in smoke tests

---

packages/react-ui/components/Hint/Hint.tsx
packages/react-ui/components/Tooltip/Tooltip.tsx
packages/react-ui/internal/CommonWrapper/CommonWrapper.tsx
packages/react-ui/internal/Popup/Popup.tsx
packages/react-ui/internal/RenderContainer/RenderContainer.tsx
packages/react-ui/internal/RenderContainer/RenderContainerTypes.ts
packages/react-ui/lib/InstanceWithAnchorElement.ts
packages/react-ui/lib/SSRSafe.ts
packages/react-ui/lib/rootNode/getRootNode.ts
packages/react-ui/lib/rootNode/rootNodeDecorator.tsx

После #2518 с избавлением от `findDOMNode` и реализации своего `getRootNode` во всех компонентах в нашем новом механизме получения корневых DOM-элементов осталось несколько проблем:
1. Неправильно установили, что является корневым элементом у Popup (и Tooltip)
2. Не учли, что корневые элементы могут меняться (и появляться) не только при mount/unmount
3. Некоторые сценарии у Tooltip и Hint не работают в условиях пункта 1)
Сперва было неочевидно, но после обнаружения бага из задачи, стало понятно, что корневым элементом `Popup` (и соответственно `Tooltip` и `Hint`) должен являться контейнер, в который рендерится содержимое `Popup`, а не его `anchorElement`, как мы установили изначально. Это следует из того, что, например, `RenderLayer`, в который оборачивается `Popup` внутри `Tooltip`, …

fix(Popup): use content container as rootNode instead of anchorElement

---

packages/react-ui/lib/listenFocusOutside.ts

При удалении компонента из DOM можно получить ошибку `Origin node for container with id 34523452345 was not found`. Но такие ошибки не схлапываются в сентри, т.к. есть уникальные символы в строке. Сам id контейнера в тексте ошибки не несет никакой пользы.
Предлагаю выпилить id из текста ошибки.

[listenFocusOutside] Убрал из текста ошибки id контейнера

---

packages/react-ui/package.json
yarn.lock

В пакете `tabbable` с [версии 5.3.2](https://github.com/focus-trap/tabbable/commit/aa2a699d7e9d37628a7b1208ba700eb85b42a31e) используется метод дом элемента `Node.contains()`. Но в IE11 этот метод [поддерживается частично](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains).
Мы используем этот пакет, например, в контроле `Loader`. Эта может развалить всё приложение.
На нашей стороне можно исправить зафиксировав версию `tabbable` на `5.3.1`

chore: fixed `tabbable` version

---

packages/react-ui/components/Tooltip/Tooltip.tsx
packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx

Исправил баг в работе Tooltip с триггером `hover&focus`. Tooltip появлялся по ховеру на anchor, но при клике по нему сразу скрывался. А если anchor от клика получал фокус, то Tooltip появлялся снова. 
Также, с триггером `click` Tooltip скрывался по второму клику на `anchor`, хотя не должен.
В #2873 поменялось видение того, что является корневым элементом у `Popup`. Раньше им было то, что попадало в `children` (это мог быть anchor или контент)*, а в последствии стал конкретно его контент. Это повлияло на работу `Popup` внутри `RenderLayer` (который детектит клики вне корневого элемента того, что в него положили). А именно, `RenderLayer` стал детектить клики вне контента `Popup`, а не вне его `anchor`, как раньше. Эта поведение законно, но оно не было учтено в #2873, т.к. на триггеры …

fix(Tooltip): fix click outside detection

---

packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx
packages/react-ui/components/ResponsiveLayout/useResponsiveLayout.ts

По обращению пользователя пофиксил утечку памяти из `ResponsveLayout`.
Все компоненты с адаптивностью (напрямую или через декоратор и `<ResponsiveLayout />`) используют хук `useResponsveLayout` для определения текущего режима (мобильный или нет). Внутри для каждого компонента добавляются отдельные слушатели глобального `MediaQueryListEvent`, которые должны удаляться на `unmout`. Но из-за опечатки в коде они оставались и занимали память.
Исправил опечатку наладив удаление слушателей. Добавил тест.
IF-615, тестовая версия `@skbkontur/react-ui@0.0.0-8824ede9eb`

fix(ResponsiveLayout): fix memory leak

---

packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts

Явно указал у элемента `box-sizing`, чтобы глобальные стили не портили отображение.
Fixes #2935

fix(TooltipMenu): set box-sizing

---

packages/react-ui/components/Modal/ModalFooter.tsx
packages/react-ui/components/Modal/ModalHeader.tsx

Fixes #2947 
Состояния `hasHeader` и `hasFooter` устанавливались только в `useEffect` через некоторое время, а не сразу после маунта, из-за чего иногда появлялось дёргание. С использованием `useLayoutEffect` дёргания нет.

fix(Modal): useEffect -> useLayoutEffect

---

packages/react-ui/components/Tooltip/Tooltip.tsx
packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
packages/react-ui/internal/RenderLayer/RenderLayer.tsx

Пофиксил проблему закрытия тултипа с триггером `hover&focus` в сценарии, когда он открывался по ховеру (или фокусу без клика), а затем получал клик в контент. 
[Пример](https://codesandbox.io/s/staging-wind-vc5g2u) с проблемой, [пример](https://codesandbox.io/s/mystifying-pond-jkf7x8) с фиксом. Сначала кликнуть на `Ok`, затем в тултип. Тултип не должен закрываться.
Источник проблемы тянется из предыдущих правок (см. #2873), после которых корневой элемент Popup поменялся с его anchor на его контент. Это поменяло события, при которых вызывается обработчик `handleClickOutside` внутри `Tooltip`. Раньше он вызывался при кликах вне anchor,  после #2873 стал вызываться при кликах вне контента тултипа. В итоге, внутренний флаг `isClickedOutside` при клике в контент тултипа не проставлялся в …

fix(Tooltip): correct focus&hover trigger behavior

---

packages/react-ui-validations/package.json
packages/react-ui-validations/scripts/check-pack-files.js
packages/react-ui-validations/src/ValidationContainer.tsx
packages/react-ui-validations/src/utils/createPropsGetter.ts

Валидации `1.9.0` потеряли типы. В итоговой сборке пакета отсутствует файл `index.d.ts`:
| ![image](https://user-images.githubusercontent.com/2708211/182213910-8c85cc6e-6cdc-47f5-8d67-c1328a18c351.png) |
| --- |
Причина в [ПРе](https://github.com/skbkontur/retail-ui/pull/2915) по исправлению проблем с типами в `defaultProps`, где заимпортили хелпер `createPropsGetter` [из контролов](https://github.com/skbkontur/retail-ui/commit/72d02d511a6ca0ea1a3569942f8cbde2f4c07d25#diff-ef28c82ff8cef217bba35323d8826f9f5bc8cc0f9797288f8bfb9831d37ecf67R2):
```js
// ValidationContainer.tsx
import { createPropsGetter } from '@skbkontur/react-ui/lib/createPropsGetter';
```
Из-за этого сборщик `rollup` стал разделять типы для пакета валидаций и для пакета контролов:
| Было | Стало |
| --- | --- |
| …

build(validations): don't use createPropsGetter from react-ui

---

packages/react-ui/components/Tooltip/Tooltip.tsx
packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx

В `onCloseRequest` не прокидывается `event`. Для некоторых команд это оказалось нужно, чтобы не закрывать Tooltip при клике на определенные элементы
Прокинула `event`  в `onCloseRequest`. Сделала его необязательным, чтобы не нарушать обратную совместимость. Также добавила ему два типа: `Event` и `React.MouseEvent<HTMLElement> `чтобы не менять типы в других местах
Дублирует правки из #2966 
fix IF-652
⬜ нерелевантно
✅ нерелевантно
3. Изменения корректно …

[Tooltip]: добавить event в onCloseRequest - LTS

---

packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
packages/react-ui/components/CurrencyInput/CurrencyInputKeyboardActions.tsx
packages/react-ui/components/CurrencyInput/__tests__/CurrencyInput-test.tsx

> Точка, слеш (/), буква б или ю на лету заменяются на запятую. Слеш, б и ю находятся на тех же клавишах, что точка и запятая, и пользователь может ввести их, забыв сменить раскладку.
>
> _© [guides.kontur.ru](https://guides.kontur.ru/components/currency/#11)_
Недостаточно ожидать значения `б` или `ю` в свойстве события `key`. На разных раскладках клавиатуры и зажатым капсом кол-во значений сильно возрастает.
Надёжней всего использовать свойство события `code`. Они не зависят от регистра или раскладки.
Для подобных целей был реализован набор хэлперов по идентификации клавиш.
Подробнее про идентификацию клавиш здесь https://github.com/skbkontur/retail-ui/pull/1639.
⬜ нерелевантно
2. …

fix(CurrencyInput): add support comma aliases

---

packages/react-ui/components/Input/Input.styles.ts
packages/react-ui/components/Input/Input.tsx
packages/react-ui/internal/themes/DefaultTheme.ts

Поступил запрос на добавление переменных `inputFocusedIconColor` и `inputFocusedBg`
Добавил переменные. Не стал добавлять дополнительные переменные для глаза из `PasswordInput` и настраивать переменные для работы с `TokenInput`, так как запрос поступил именно на добавление переменных для обычного инпута
IF-625
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ все тесты и …

feat(react-ui): add inputFocusedBg and inputFocusedIconColor variables

---

jest.config.js
package.json
packages/react-ui-smoke-test/jest.config.js
packages/react-ui-smoke-test/package.json
packages/react-ui-validations/jest.config.js
packages/react-ui-validations/package.json
packages/react-ui/jest.config.js
packages/react-ui/package.json

Конфиги jest загромождают package.json-ы и не очень удобно версионируются.
Вынести конфиги в отдельные файлы.
close #1178 
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

build: move jest configs to separate files

---

packages/react-ui/components/Input/Input.styles.ts

В #2981 добавили переменную для цвета фона в состоянии фокуса. Но использование сокращенной формы `background: ${color};` устанавливает все другие неупомянутые явно свойства `background-*` в [дефолтные значения](https://developer.mozilla.org/en-US/docs/Web/CSS/background#formal_definition). Из-за этого, `background-clip` на элементе `root` сбросился с `padding-box` на `border-box`. 
Это вызвало дифф на скриншоте. Воспроизводится только в теме `THEME_2022`, т.к. там поменялся border-radius. Наши тесты не поймали, потому что новая тема еще не тестируется скриншотами. Найдено тестами экстерна.
_Добавить тест на это к нам, кажется, пока представляется не целесообразным._
Вернуть старое значение `background-clip`, указав цвет фона через специальное свойство `background-color`.
IF-720, IF-722 …

fix(Input): restore background-clip in focus state

---

packages/react-ui/components/Radio/Radio.styles.ts
packages/react-ui/internal/themes/DefaultTheme.ts

У текста в компоненте Radio пропадает отступ, если у контейнера указан `border-collapse: collapse`.
Указал нужный border-collapse у корневого элемента.
fix #2980

fix(Radio): указать нужный border-collapse у корневого элемента

---

packages/react-ui/components/FileUploader/FileUploader.md

Пример "Валидация файла в списке" в доке `FileUploader`'а некорректен, в нём возвращаемое значение в функции передаваемой в `validateBeforeUpload` не оборачивается в `Promise`, хотя согласно типам это происходить должно. Из-за чего, пользователи, которые копируют пример с доки, сталкиваются с `TypeScript`'овыми ошибками 
Обернул в `Promise.resolve` возвращаемое значение в функции передаваемой в `validateBeforeUpload`
IF-744
✅ нерелевантно
⬜ нерелевантно
3. …

docs(FileUploader): fix incorrect example

---

packages/react-ui/.creevey/images/Paging/Disabled Paging/chrome.png
packages/react-ui/.creevey/images/Paging/Disabled Paging/chromeDark.png
packages/react-ui/components/Paging/Paging.md
packages/react-ui/components/Paging/Paging.styles.ts
packages/react-ui/components/Paging/Paging.tsx
packages/react-ui/components/Paging/__stories__/Paging.stories.tsx
packages/react-ui/components/Paging/__tests__/Paging-test.tsx
packages/react-ui/internal/themes/DarkTheme.ts
packages/react-ui/internal/themes/DefaultTheme.ts

У `Paging`'а в отключенном состоянии пропадала только возможность сфокусироваться на нём, но никак не менялся внешний вид
1. Изменил дизайн отключенного состояния в соотвествии с макетами (макеты можно найти в комментариях к задаче)
2. Новых переменных в тему не добавлял, так как пока не ясно есть ли в них необходимость
3. Оставил скриншоты только в `Chrome`, так как в отключенном состоянии меняются только цвета контрола
#3018, IF-806
⬜ нерелевантно
⬜ …

fix(Paging): visual appearance of disabled state

---

packages/react-ui-testing/.gitignore
packages/react-ui-testing/SeleniumTesting/SeleniumTesting.csproj
packages/react-ui-testing/Tests/TestEnvironment/Browser.cs
packages/react-ui-testing/Tests/Tests.csproj

Пора переезжать на WebDriver 4.
Видимо, будет новая мажорная версия 4.0.0.

chore(react-ui-testing): move SeleniumTesting to WebDriver 4

---

packages/react-ui-validations/src/ValidationContextWrapper.tsx
packages/react-ui-validations/tests/ValidationContainer.test.tsx

В #2977 реализовали поведение, когда при типе валидаций `warning` `ValidationContainer` дает засабмитить форму только со второго раза. Но это поломало пользовательские сценарии и было решено разрешить сабмитить форму с первого раза
Просто откатить #2977 не помогло бы, так как до этого в #2804 при типе валидаций `warning` `ValidationContainer`  не давал в принципе засабмитить форму. Поэтому пришлось вручную удалять логику валидирования со второго раза и изменять условие валидации
fix IF-817
⬜ нерелевантно
⬜ прочие …

fix(ValidationContainer): level warning is valid

---

.teamcity/settings.kts
packages/react-ui-validations/selenium-tests/ValidationTests/packages.config

Начали падать шарповые тесты на некоторых агентах. Ранер тестов NUnit валился с такой ошибкой:
```diff
-Process exited with code -100 (Step: Run tests (NUnit))
-Step Run tests (NUnit) failed
```
Дело оказалось в обновлении dotnet до `7.0` на половине агентах. У нас в конфиг этого билда указана дефолтная версия NUnit. Тимсити назначил дефолтной версию `3.12.2`, и в ней оказался [баг](https://github.com/nunit/nunit3-vs-adapter/issues/987).
Указал другую версию NUnit, которая нормально работает и с `6.0` и с `7.0` версиями dotnet.
✅ нерелевантно
⬜ комментарии …

build(tc): pick 3.15 version of NUnit due to .NET 7.0

---

packages/react-ui/components/MenuItem/MenuItem.tsx
packages/react-ui/components/SidePage/SidePageFooter.tsx
packages/react-ui/components/SidePage/SidePageHeader.tsx
packages/react-ui/components/Sticky/Sticky.tsx
packages/react-ui/internal/Popup/Popup.tsx

Собирал библиотеку собственных контроллов поверх ваших и столкнулся с проблемой в тайпингах в связке со свежим реактом
```
Interface 'PopupProps' incorrectly extends interface 'CommonProps'.
Types of property 'children' are incompatible.
Type 'ReactNode | (() => ReactNode)' is not assignable to type 'ReactNode'.
Type '() => ReactNode' is not assignable to type 'ReactNode'.
```
Наследуюсь `Omit<CommonProps, 'children'>` вместо просто `CommonProps`, если есть несовместимое переопределение в описываемом интерфейсе  
Список измененных интерейфесов:
```
MenuItemProps
SidePageHeaderProps
SidePageFooterProps
StickyProps
PopupProps
```
✅ нерелевантно
⬜ …

chore: correct some ts interfaces

---

packages/react-ui/.creevey/images/Switcher/with custom render item/chrome.png
packages/react-ui/components/Group/Group.tsx
packages/react-ui/components/Switcher/Switcher.tsx

При использовании пропа `renderItem` в `Switcher` , компонент Group не может задетектить кнопку, чтобы убирать скругления углов.
Научил `Switcher` самостоятельно убирать скругления углов.
IF-847
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
⬜ заголовок PR кратко и доступно отражает суть изменений (он …

fix(Switcher): deliver `corners` to `Button` when using `renderItem`

---

packages/react-ui-validations/docs/Pages/Api.md
packages/react-ui-validations/selenium-tests/ValidationTests/Storybook/Sync/SubmitValidation.cs
packages/react-ui-validations/src/ValidationContainer.tsx
packages/react-ui-validations/src/ValidationContextWrapper.tsx
packages/react-ui-validations/tests/ValidationContainer.test.tsx

В #2804 добавили автофокус если уровень валидации `warning`. Потом в #3026 мы вернули изначальное поведение, когда при уровне валидации `warning` разрешить сабмитить форму с первого раза. 
Некоторые команды попросили добавить возможность отключать автофокус только для варнингов, так как нет смысла фокусировать форму на варнинге и тут же ее отправлять. 
В методе `validate` расширила тип аргумента: оставила `boolean` для обратной совместимости и добавила возможность прокинуть `'warningsWithoutFocus'` для отключения автофокуса при уровне валидации `warning`.
fix IF-832
⬜ нерелевантно
⬜ …

feat(Validation): add an option to disable focus on warning

---

packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
packages/react-ui/components/CurrencyInput/__tests__/CurrencyInput-test.tsx
packages/react-ui/lib/utils.ts

Правки из #2885 попали в `LTS`, следовательно там сейчас не работает очистка `CurrencyInput`
Продублировал правки из #3025 в `LTS`
IF-824
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

fix(CurrencyInput): clearing value (LTS)

---

packages/react-ui/components/Switcher/Switcher.tsx
packages/react-ui/components/Switcher/helpers.ts

После добавления возможности прокидывать кастомные пропы в кнопки Свитчера, появилась возможность дизейблить их по отдельности.
Свитчер не учитывает выключенность кнопок и позволяет навигацию клавишами [влево]/[вправо] по ним, и выбора по [энтеру].
Изменил логику перемещения по элементам с помощью клавиатуры.
https://yt.skbkontur.ru/issue/IF-855
✅ нерелевантно
✅ нерелевантно
⬜ …

fix(Switcher): fix keyboard navigation with disabled items

---

packages/react-ui/internal/Menu/Menu.styles.ts
packages/react-ui/internal/themes/DefaultTheme.ts
packages/react-ui/internal/themes/Theme2022.ts

Closes #3077
В теме 2022 у выпадающего меню есть отступы от полей ввода/кнопок.
В библиотеке отступы отсутствовали, переменные темы тоже.
Добавил `margin-top` и `margin-bottom` для `Menu`, равные `4px` для `Theme2022`.
Добавил переменную темы `menuOffsetY` для кастомизации отступа.
close https://github.com/skbkontur/retail-ui/issues/3077
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно …

feat(Menu): menu vertical offset and new theme variable menuOffsetY

---

packages/react-ui-validations/docs/Pages/Examples/Editors/Editors.demo.tsx
packages/react-ui-validations/docs/Pages/Examples/GuidesExample/GuidesExample.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Arrays/Arrays.md
packages/react-ui-validations/docs/Pages/Validator/Arrays/ObjectArray.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Arrays/PrimitiveTypeArray.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/MissingNodes/MissingObjectNode.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/MissingNodes/MissingUiNode.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Objects/FlatObject.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Objects/NestedObject.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Objects/Objects.md
packages/react-ui-validations/docs/Pages/Validator/Objects/PrimitiveType.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Reusable/Reusable.demo.tsx
packages/react-ui-validations/docs/Pages/Validator/Reusable/Reusable.md

В [документации](http://tech.skbkontur.ru/react-ui-validations/#/object-validation:~:text=%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%20%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B9) для проверки валидности email используется слишком строгая регулярка, которая не обеспечивает валидацию Internationalized Mail Address standards: rfc5322 или нового rfc653x
Матчасть:
- https://www.netmeister.org/blog/email.html
- https://habr.com/ru/post/175375/
- https://habr.com/ru/post/55820/
- https://habr.com/ru/post/274985/
- https://habr.com/ru/post/434640/
Если коротко:
1. email может содержать практически все символы ! $ & * - = ^ ` | ~ # % ' + / ? _ { }
2. email может содержать больше одного символа @ 
3. доменные имена могут не содержать точки
> …

chore: fix RegExp to check email in documentation

---

packages/react-ui-validations/docs/Layout.tsx
packages/react-ui-validations/docs/Pages/Examples/CustomControls/CustomControls.demo.tsx
packages/react-ui-validations/docs/Pages/Examples/CustomControls/CustomControls.md
packages/react-ui-validations/docs/Pages/Examples/index.ts
packages/react-ui-validations/docs/index.html
packages/react-ui-validations/docs/styles/typography.less
packages/react-ui-validations/docs/styles/variables.less

Время от времени пользователи приходят c такими вопросами по валидации, которые могут решиться созданием обёртки над контролами react-ui.
Также бывали вопросы об использовании с нашими валидациями контролов из другим библиотек или полностью кастомными компонентами.
Текущая реализация валидаций принципиально способна работать не только с нашими контролами.
Но об этом ничего не написано в Доке, и можно понять только изучив исходники в репе.
Правки в Доке валидаций:
- Добавил простой пример и ссылку на песочницу.
- Заменил `Segoe UI`  на `Lab Grotesque`.
- Добавил небольшой отступ в меню, чтобы было видно последний пункт.
`IF-935`
✅ нерелевантно
⬜ …

docs(validations): add page how to use custom controls

---

packages/react-ui-validations/src/ValidationWrapperInternal.tsx
packages/react-ui-validations/tests/ValidationWrapper.test.tsx

Метод `onInputValueChange` частично ломается в `ValidationWrapper`.
Клон-обёртка метода не возвращает значение.
При клонировании метода `onInputValueChange` добавил возвращение значение.
`IF-937`
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает суть изменений (он …

fix(validations): fix return value of `onInputValueChange`

---

packages/react-ui/components/DropdownMenu/DropdownMenu.md
packages/react-ui/components/TooltipMenu/TooltipMenu.md

Пользователи не знают о том, что в проп `caption` контролов `TooltipMenu` и `DropdownMenu` помимо компонента можно передать функцию, с помощью которой можно управлять текущим состоянием меню
Добавил в документацию соответствующих контролов примеры передачи функции в проп `caption`
IF-925
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
✅ в …

docs(TooltipMenu, DropdownMenu): add examples on manual control

---

packages/react-ui/components/Hint/Hint.md

Есть сценарии, когда необходимо использовать проп `useWrapper` или кастомную обёртку для правильной работы Хинта.
Эти сценарии кажутся редкими, а любое комплексное исправление ломающим.
Поэтому решили добавить информацию об этом в Доку с примерами обходных решений.
Добавил примеры использования встроеной и кастомной обёртки.
`F-948`
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. …

docs(Hint): add examples using `useWrapper` prop & custom wrapper

---

packages/react-ui/.creevey/images/Dropdown/with manual position/opened bottom with portal/chrome/opened bottom with portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened bottom with portal/firefox/opened bottom with portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened bottom without portal/chrome/opened bottom without portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened bottom without portal/firefox/opened bottom without portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened top with portal/chrome/opened top with portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened top with portal/firefox/opened top with portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened top without portal/chrome/opened top without portal.png
packages/react-ui/.creevey/images/Dropdown/with manual position/opened top without portal/firefox/opened top without portal.png
packages/react-ui/components/Dropdown/Dropdown.tsx
packages/react-ui/components/Dropdown/__stories__/Dropdown.stories.tsx

В #3076 всем компонентам основанным на `DropdownContainer` (`ComboBox`, `DatePicker`, `Select`, `Autocomplete`) добавили проп `menuPos` для возможности задания позиции выпадающего окна вручную. 
`Dropdown` сделан на основе `Select` и про него забыли
Добавила проп `menuPos` в `Dropdown`
fix IF-963
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ все тесты и линтеры на CI …

feat(Dropdown): add prop menuPos for manual control of dropdown position

---

packages/react-ui/.storybook/preview.tsx

При изменении темы в `Storybook` с темы по умолчанию (`DEFAULT_THEME`) на любую другую перестает отображаться мобильный вид контролов
У нас в качестве `mobileMediaQuery` по умолчанию задано квери вида: `(max-width: 576px) and (hover: none) and (pointer: coarse)`. То есть, помимо того, что ширина экрана должна быть меньше `576px` мы должны ещё и взаимодействовать с тач-устройством, чтобы это квери сработало. Вне зависимости от того, изменён ли у нас вьюпорт средствами `Storybook`'а или нет второе условие никогда не выполнится. Поэтому для `Storybook`'а квери подменяется на `(max-width: 576px)`, но это происходит только для `DEFAULT_THEME`, из-за чего в остальных темах ломается мобильное отображение. Распространил упрощенную версию квери на остальные темы
P.S.
Значение `(max-width: 576px)` …

chore(Storybook): fix mobile view of components on theme change

---

packages/react-ui/.styleguide/components/StyleGuideWrapper/StyleGuideWrapper.tsx
packages/react-ui/.styleguide/components/ThemeSwitcher/ThemeSwitcher.tsx
packages/react-ui/.styleguide/components/ThemeSwitcher/constants.ts
packages/react-ui/.styleguide/components/ThemeWrapper/ThemeWrapper.tsx

В документации не хватает возможности переключать готовые темы кастомизации.
Добавил Селект выбора тем. Задал ему тему `THEME_2022_DARK`.
`F-936`
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

docs: add Select of theme instead Toggle of dark theme

---

packages/react-ui/components/TokenInput/TokenInput.tsx

Если с помощью `ctrl+v` вставить строку: `'токен, токен'`, то `TokenInput` добавляет пустой токен посередине. 
Причина в том, что и запятая и пробел являются разделителями
Решили добавить проверку на пустой токен
fix IF-1097
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …

chore(TokenInput): add check for empty token on paste

---

packages/react-ui/components/Paging/Paging.styles.ts

При задании глобального стиля `box-sizing: border-box` (с помощью универсального селектора `*`) кружки `Paging`'а сжимаются в колбаски
[Песочница](https://stackblitz.com/edit/react-c8cs7g?file=package.json,src%2FApp.js,src%2Fstyle.css) с воспроизведением бага
Задал стиль `box-sizing: content-box` для кружков, чтобы глобальные стили не переписывали это значение 
P.S.
Нормальные тесты на это поведение написать не получается в голову приходят только костыльные варианты, поэтому опустил их
IF-1109
✅ нерелевантно
⬜ …

fix(Paging): global styles may cause circles to shrink

---

packages/react-ui/internal/Popup/Popup.tsx

В dev-режиме React 18 с использованием StrictMode тултипы и хинты не работают должным образом. Подробности в задаче.
Дело в том, что React в таком режиме эмулирует двойной mount/unmount, лишний раз вызывая соответствующие методы жизненного цикла компонентов. Но в Popup, при размонтировании, в том числе при фейковом, каждый раз удаляются слушатели событий на `anchorElement`. А добавляются они только при настоящем монтировании - внутри рендера или ref. Т.е. проблема в отсутствии нужных слушателей событий после нескольких циклов mount/unmount. 
По сути компонент не устойчив к многократному монтированию и размонтированию, которые в будущем [станут нормой](https://react.dev/blog/2022/03/29/react-v18#new-strict-mode-behaviors).
Отслеживать наличие слушателей после монтирования и добавлять их в …

fix(Popup): support multiple mount/unmount cycles (React18 Dev StrictMode)

---

packages/react-ui/lib/ModalStack.ts
packages/react-ui/lib/net/fetch.ts
packages/react-ui/typings/global.d.ts

Хэлпер `ModalStack` напрямую обращается к переменной `global`, которой по-умолчанию нет в глобальной области браузеров. Это может ломать компоненты `<Modal>` и `<SidePage>`, которые используют этот хэпер.
Заменить прямое обращение к `global` на безопасную переменную `globalThat`, которую мы сами объявляем.
В зависимости от окружения она будет ссылаться на `window` в браузерах, или на `global` в Node.js.
Fix `IF-1150`
Демка с проблемой
https://stackblitz.com/edit/vitejs-vite-4kqgqj?file=src%2FApp.tsx,vite.config.ts&terminal=dev
Демка с исправлением
https://stackblitz.com/edit/vitejs-vite-9z3nbb?file=src%2FApp.tsx,package.json&terminal=dev
⬜ нерелевантно
2. Добавлена (обновлена) …

fix(Modal,SidePage): use safety `globalThat` instead of `global`

---

packages/react-ui/components/DatePicker/DatePicker.md
packages/react-ui/components/DatePicker/DatePicker.tsx
packages/react-ui/components/DatePicker/Picker.tsx
packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx
packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
packages/react-ui/internal/Calendar/Calendar.styles.ts
packages/react-ui/internal/Calendar/Calendar.tsx
packages/react-ui/internal/Calendar/DayCellView.styles.ts
packages/react-ui/internal/Calendar/DayCellView.tsx
packages/react-ui/internal/Calendar/Month.tsx
packages/react-ui/internal/Calendar/MonthView.styles.ts
packages/react-ui/internal/Calendar/MonthViewModel.ts
packages/react-ui/internal/Calendar/__stories__/Calendar.stories.tsx
packages/react-ui/internal/Calendar/config.ts
packages/react-ui/internal/themes/DefaultTheme.ts
packages/react-ui/internal/themes/Theme8px.ts

В рамках проекта Контур.Продажи (как и в других проектах) появилась потребность в разрезе месяца\даты показывать дополнительную информацию вместе с датой в календаре.
На примере проекта Контур.Продажи: пользователю нужно показывать кол-во запланированных звонков в разрезе даты. Более подробно [проблема описана здесь](https://yt.skbkontur.ru/issue/KS-3821/Kalendar-5.-Pri-planirovanii-sobytiya-otobrazhat-Ispolnitelyu-informaciyu-o-kolichestve-sobytij-na-datu-v-kartochke-sdelki).
Было принято решение использовать `DatePicker ` для решения задачи и внести некоторые доработки в компоненты.
Что сделано:
1. Добавлен пропс `renderItem`, который рендерит кастомный элемент даты месяца. Если такой пропс не передан, то рендерится число месяца.
2. Добавлен пропс `onMonthChange`, который возвращает …

Добавление пропсов renderItem и onMonthChange. branch/KS-4180

---

packages/react-ui/components/Button/Button.tsx
packages/react-ui/components/Button/ButtonIcon.tsx
packages/react-ui/components/Input/InputLayout/InputLayoutAsideIcon.tsx
packages/react-ui/components/Kebab/Kebab.tsx
packages/react-ui/internal/icons2022/iconSizer.tsx
packages/react-ui/lib/forwardRefAndName.ts
packages/react-ui/lib/utils.ts

- В #3175 была удалена логика (пункт 4 описания пулл-реквеста), с помощью которой ресайзились кастомные иконки пользователей
- Также в `4.14.0` у пользователей пропала возможность изменять размер иконок с помощью пропа `size`, который они передают на свои иконки
- Выравнивание кастомных иконок теперь реализуется на стороне библиотеки иконок, поэтому чтобы получить правильное выравнивание пользователям нужно будет обновить библиотеку иконок
- Вернул логику для ресайза иконок и добавил условие, которое проверяет что ресайзатся именно наши иконки
- Вернул возможность менять размер иконок с помощью пропа `size`
IF-1253
⬜ нерелевантно
⬜ styleguidist для …

fix(Button, Input, Kebab): resize icons according to control's size

---

packages/react-ui/components/Calendar/DayCellView.styles.ts
packages/react-ui/components/Calendar/DayCellView.tsx
packages/react-ui/internal/themes/Theme2022.ts

В теме 2022 перестала работать переменная `calendarCellTodayBorder`
Прокинул актуальное значение для бордера в тему 2022
IF-1263
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

fix(Calendar): return customization of current day border in theme 2022

---

packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx

После #3144 в консоль стала падать ошибка:
```diff
- flushSync was called from inside a lifecycle method.
- React cannot flush when React is already rendering.
- Consider moving this call to a scheduler task or micro task.
```
Ошибка была вызвана тем, что метод `dispatch` вызывался в методах жизненного цикла `componentDidMount` и `componentDidUpdate`.
Так как в #3144 исправлялся другой баг, а покрыть тестами его не удалось важно было удостовериться в том, что фикс не сломает всё снова.
[Песочница](https://codesandbox.io/s/validations-objects-react-18-ojmzni?file=/src/index.tsx) с багом (`@skbkontur/react-ui@4.13.3`). Для воспроизведения нужно ввести в первый инпут валидное значение и затем нажать на кнопку "Submit" - у второго поля не появится тултип валидации: …

fix(ComboBox): flushSync throws an error into console

---

packages/react-ui/components/Button/getInnerLinkTheme.ts
packages/react-ui/components/Link/Link.mixins.ts
packages/react-ui/components/Link/Link.styles.ts
packages/react-ui/components/Link/Link.tsx
packages/react-ui/internal/themes/DefaultTheme.ts

После ПР #3185 пропала возможность кастомизировать подчеркивание в 22 теме
Изначально просили добавить переменную `linkLineHoverBorderBottomStyle `, чтобы изменять стиль подчеркивания при ховере по аналогии с переменной `linkLineBorderBottomStyle `. Но я также решила добавить переменную `linkLineBorderBottomOpacity `для возможности кастомизации прозрачности.
Добавила аналогичные переменные для кнопки-ссылки: `btnLinkHoverLineBorderBottomStyle`, `btnLinkLineBorderBottomOpacity`
Полная прозрачность достигается при `animation-delay: -0.99s`, а не `-1s`. Пришлось внести корректировку в 1 сотую процента для переменной
fix IF-1312
✅ нерелевантно
⬜ …

feat(Link, Button): add theme variables for border-bottom

---

packages/react-ui/.styleguide/components/StyleGuideWrapper/StyleGuideWrapper.styles.ts
packages/react-ui/.styleguide/config/base.config.js

В документации не у всех элементов установлен шрифт `LabGrotesque`
Проблема была в том, что в стайлгайдисте есть свои сгенерированные классы и они переписывали цвет некоторых элементов. 
Решила задачнием шрифта через тему стайлгайдиста
fix IF-1298
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR …

chore: change styleguidist font

---

packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx

Метод `flushSync()` (https://github.com/skbkontur/retail-ui/pull/3144) мог крашить всё приложение в `React@16`
В [песочнице](https://codesandbox.io/s/cool-tharp-gckcn7?file=/src/index.js) если в `ComboBox` ввести своё значение и убрать фокус то приложение развалиться.
Ранее также возникала проблема с варнингом (https://github.com/skbkontur/retail-ui/pull/3189) при вызове `flushSync()` из методов ЖЦ.
Т.к. `flushSync()` помогает исключительно в `React@18`, то решил добавить флаг `isReact18`, чтобы в остальных версиях всё работало по старому.
Об этом сообщит такое предупреждение в консоле:
Это можем привести к варнингу, которую правили здесь https://github.com/skbkontur/retail-ui/pull/3189.
Но т.к. такое использование Реакта 18 не рекомендуется, то я решил никак это не править.
В таком …

fix(ComboBox): use `flushSync` only in React@18

---

packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
packages/react-ui/internal/InputLikeText/InputLikeText.tsx

Фикс в `ComboBox` для React 18 #3144 создал 2 проблемы:
1. В React 17 в консоль сыпалась ошибка #3189
2. В React 16 эта же ошибка крашила приложение #3202 
Решили https://github.com/skbkontur/retail-ui/pull/3202#issuecomment-1632494470 использовать исходный фикс из #3144 исключительно под React 18.
Для этого последовательно откатил предыдущие комиты, и затем "скрестил" код из этих комитов в один.
> Если мест использования `flushSync` с проверкой на `React18` получается больше одного, то уже стоит вынести их в переиспользуемую функцию, наподобие тех, что у нас в `SSRSafe`. Так будет меньше вероятность наступить на ту же граблю в будущем.
© https://github.com/skbkontur/retail-ui/pull/3202#issuecomment-1632494470
Предлагаю пока не выносить это решение в хелперы. Сейчас это жуткий костыль для …

fix(ComboBox,InputLikeText): use `flushSync` only in React 18

---

packages/react-ui/components/ScrollContainer/ScrollContainer.tsx

`SideMenu` использует приватный `hasScrollBar`. Некоторые пользователи используют приватное поле  `inner`. Это вызывает недовольство у `TypeScript`
Сделала их публичными
fix IF-1111
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее …

chore(ScrollContainer): make `inner` and `hasScrollBar` public

---

packages/react-ui/components/DateInput/__stories__/DateInput.stories.tsx
packages/react-ui/internal/InputLikeText/InputLikeText.tsx

Компонент DatePicker при потере фокуса внутри валидации "не отдаёт" фокус при клике. При клике в другой Input надо кликать 2 раза. 
При использовании валидаций, при потере фокуса вызывается методы которые обновляет валидируемый контрол, что в итоге приводит нескольким вызовам метода `componentDidUpdate`.
В контроле DateInput (который внутри DatePicker) на него завязана логика удержания выделенных сегментов даты.
Эти сегменты выделяются асинхронно, и не прерывают предыдущие вызовы, что и приводит к проблеме.
Для исправление добавил debounce и отмену при потере фокуса.
---
Также исправил в одном тесте способ контроля дефолтного значения при восстановлении даты.
`IF-1285`
⬜ нерелевантно …

fix(InputLikeText): use debounce to control async content selection

---

packages/react-ui/components/ComboBox/ComboBox.md

В примере "_Переопределение renderValue, renderItem и itemWrapper_" некорректно отображались длинные имена: 
исправила пример
fix IF-1375
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее

chore(ComboBox): fix example

---

packages/react-ui-validations/src/index.tsx

Из пакета react-ui-validations yе получается импортировать `ValidationSettings` и `FocusMode`. Стоит проверить и другие типы
Добавила остутствующие экспорты
fix F-1371
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

chore: add missing export

---

packages/react-ui/package.json

Во время релиза react-ui перестала публиковаться директория `build`, несмотря на указание ее в команде:
> npm publish ./build
Опытным путем выяснил, что проблема появилась в [npm@8.5.0](https://github.com/npm/cli/blob/v8.5.0/CHANGELOG.md#v850-2022-02-10), вероятно из-за фичи с воркспейсами.
Проблема лечится отключением воркспейсов опцией [--workspaces=false](https://docs.npmjs.com/cli/v8/commands/npm-publish#workspaces). Проверил в последнем next: [@skbkontur/react-ui@4.16.0-next.5](https://npmfs.com/package/@skbkontur/react-ui/4.16.0-next.5/).
IF-1377
✅ нерелевантно
⬜ jsdoc для утилит …

ci: fix publishing of a specific directory via npm

---

packages/react-ui/.creevey/images/Textarea/size/chrome.png
packages/react-ui/.creevey/images/Textarea/size/chrome2022.png
packages/react-ui/.creevey/images/Textarea/size/chrome2022Dark.png
packages/react-ui/.creevey/images/Textarea/size/chrome8px.png
packages/react-ui/.creevey/images/Textarea/size/chromeDark.png
packages/react-ui/.creevey/images/Textarea/size/chromeFlat8px.png
packages/react-ui/.creevey/images/Textarea/size/firefox.png
packages/react-ui/.creevey/images/Textarea/size/firefox2022.png
packages/react-ui/.creevey/images/Textarea/size/firefox2022Dark.png
packages/react-ui/.creevey/images/Textarea/size/firefox8px.png
packages/react-ui/.creevey/images/Textarea/size/firefoxDark.png
packages/react-ui/.creevey/images/Textarea/size/firefoxFlat8px.png
packages/react-ui/components/Textarea/Textarea.md
packages/react-ui/components/Textarea/Textarea.mixins.ts
packages/react-ui/components/Textarea/Textarea.styles.ts
packages/react-ui/components/Textarea/Textarea.tsx
packages/react-ui/components/Textarea/TextareaCounter.tsx
packages/react-ui/components/Textarea/__stories__/Textarea.stories.tsx
packages/react-ui/internal/themes/DefaultTheme.ts

Добавить проп size для Textarea
https://yt.skbkontur.ru/issue/IF-1357/Dobavit-prop-Size-dlya-Textarea
https://yt.skbkontur.ru/issue/IF-807/Dobavit-propy-size-dlya-vseh-komponentov
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее

feat(Textarea): add prop size, tests, documentation

---

packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx

В #3206 отказались от фикса из #3189, который не позволял `flushSync` запускаться в методах жизненного цикла
Это привело к тому, что в консоль вернулась ошибка об использовании `flushSync` в методах жизненного цикла
Вернул логику из #3189
[Песочница](https://codesandbox.io/s/validations-objects-react-18-forked-dct8d8?file=/src/index.tsx) с ошибкой в `react@18` для проверки
IF-1385
✅ нерелевантно
✅ нерелевантно
✅ без …

fix(ComboBox): flushSync throws an error into console (React@18)

---

packages/react-ui/components/Select/Select.tsx
packages/react-ui/components/Select/__tests__/Select-test.tsx

Если пробрасывать `aria-label` в `Select` при использовании пропа `_renderButton`, то `aria-label` проброшенный в `_renderButton` будет перезаписан, что приводит к ломающим изменениям
Написал условие для проверки что в `_renderButton` не был проброшен `aria-label`, прежде чем записывать `aria-label` из пропов
Создал задачу IF-1420, чтобы избавиться от этого поведения в мажорной версии, так как остальные пропы перезаписывают значение в `_renderButton`
IF-1416, IF-1420
⬜ нерелевантно
✅ комментарии для неочевидных мест в коде …

fix(Select): let _renderButton override aria-label passed to root

---

packages/react-ui/.creevey/images/ZIndex/Loader and SidePage/SidePage shadow cover Loader/chrome2022Dark/SidePage shadow cover Loader.png
packages/react-ui/components/Toggle/Toggle.styles.ts

В теме `THEME_2022` не работает проп `disableAnimations`.
Из-за чего невозможно стабильно воспроизводить результат в скриншотном тестировании.
| ![image](https://github.com/skbkontur/retail-ui/assets/2708211/8e5d07a5-a6e7-4518-8adb-e1c690c78dad) |
| --- | 
Удалил лишний `!important`.
Дело в альтернативной вёрстке для темы `THEME_2022`.
В ней отдельно задаются стили для анимации. И почему-то был добавлен флаг `!important`.
Вкупе с селектором, их специфичность не мог перебить стиль, отключающий анимации.
✅ нерелевантно
⬜ комментарии для неочевидных мест в …

fix(Toggle): disable animations for `THEME_2022`

---

packages/react-ui/components/ComboBox/ComboBox.tsx
packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx

Указанный тип пропа `getItems` не соответствует реальности:
```js
// Интерфейсе
getItems: (query: string) => Promise<T[]>;
// Фактические возможности
getItems: (query: string) => Promise<Array<T | (() => React.ReactElement<T>) | React.ReactElement<T>>>;
```
Описал реальный тип `getItems`.
Также исправил типа пропа `itemWrapper`. Изначальный тип предполагал, что `item` может быть `undefined`.
Хотя по логике кода такого происходить не должно.
```js
// Было
itemWrapper?: (item?: T) => React.ComponentType<unknown>;
// Стало
itemWrapper?: (item: T) => React.ComponentType<unknown>;
```
`IF-1425`
✅ ❗ В качестве теста добавил стори с `getItems` и другими пропами использующими `item`.
⬜ …

fix(ComboBox): describe all available types returned by `getItems`

---

packages/react-ui/components/Link/Link.styles.ts
packages/react-ui/components/Link/Link.tsx
packages/react-ui/internal/themes/DefaultTheme.ts

Отсутствует transition на подчеркивании в 2022 теме. 
Изначально планировалось добавить стили:
`transition: border-bottom-color 1000ms cubic-bezier(0.5, 1, 0.89, 1);
border-bottom-color: color-mix(in srgb, currentColor 50%, transparent);`
Однако, в chrome и edge сочетание transition, color-mix и currentColor вызывает моргание при применении transition.
Чтобы избежать этого - добавила lineTextWrapper с прозрачным подчеркиванием, при hover'е меняющимся на currentColor, а у lineText оставила подчеркивание currentColor с половинной прозрачностью.
При hover'е выполняется подчеркивание из прозрачного переходит в currentColor. За счет наложения этого цвета на подчеркивание lineText (currentColor с половинной прозрачностью) достигается эффект перехода currentColor с половинной прозрачностью до …

feat(Link): add transition on underline

---

packages/react-ui/components/Button/Button.styles.ts

[Песочница](https://codesandbox.io/s/falling-currying-3ty3ky?file=/src/App.js:117-1131)
Кнопка находится внутри кликабельного блока. Если кнопка `disabled`, то при клике по ней происходит редирект, что отличается от нативного поведения. Решили исправить
Обнаружила, что проблема в свойстве `pointer-events: none`:
1. Нативной кнопке пробрасывается состояние `disabled`, что само по себе отключает события мыши, поэтому дополнительно указывать `pointer-events: none` не нужно
2. Если в песочнице для нативной заблокированной кнопки добавить это свойство, то при клике на нее тоже будет происходить редирект
Удалила это свойство. Тесты добавлять не вижу необходимости
fix IF-1433
✅ нерелевантно …

chore(Button): delete pointer-events style

---

packages/react-ui/components/Modal/Modal.styles.ts
packages/react-ui/internal/themes/Theme2022.ts

в мобильной модалке появляется горизонтальный скролл. Воспроизводится в документации
Проблема была в том, что в 22 теме крестик чуть расширял модалку
fix IF-1434
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

chore(Modal): delete mobile horizontal scroll

---

packages/react-ui/components/Input/InputLayout/InputLayout.tsx

При использовании `<CurrencyInput />` в `THEME_2022` с включенным `StrictMode` `React` выдавал ошибку о использовании `findDOMNode`.
При реализации `THEME_2022` в `<Input />` добавился новый функциональный компонент - `<InputLayout />`, который не умел работать с `ref`. Для того, чтобы исправить проблему научил его работать с `ref`.
Песочница в которой воспроизводится проблема: https://codesandbox.io/s/competent-bas-2lkvpy
Песочница с исправлениями из пулл-реквеста: https://codesandbox.io/s/amazing-rhodes-lv8hkx?file=/src/index.js
IF-1459
✅ нерелевантно
⬜ …

fix(CurrencyInput): remove `findDOMNode` console warning in `THEME_2022`

---

packages/react-ui/README.md
packages/react-ui/index.ts

Пользователи хотят получать доступ к корневым элементам из классовых компонентов
Добавил экспорт `InstanceWithRootNode` и описал как им пользоваться в документации
IF-1452
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее

chore: add export of type `InstanceWithRootNode` to use rootNode API

---

packages/react-ui/.styleguide/helpers.js
packages/react-ui/components/Tabs/Tab.md
packages/react-ui/components/Tabs/Tab.tsx
packages/react-ui/components/Tabs/Tabs.md
packages/react-ui/components/Tabs/Tabs.tsx

В документации нет ни слова о визуальных состояниях `<Tabs.Tab />`. Хотя визуальные состояния компонента - часть публичного `API`.
Добавил описание визуальных состояний, с примерами и объяснениями о работе фичи с автоматическим подбором цвета подчёркивания при наведении.
IF-1451
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
✅ в коде нет …

docs(Tab): add information about <Tabs.Tab /> visual states

---

packages/react-ui/components/Button/Button.tsx
packages/react-ui/components/Button/__tests__/Button-test.tsx

В теме 2022 нельзя получить доступ к иконке кнопки в состоянии `loading`
Добавил на обёртку иконки `data-tid`
IF-1457
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

feat(Button): add data-tid for spinner icon

---

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx

Когда `ComboBox` находится внутри формы, при нажатии на `enter` не происходит сабмит
Ожидаемое поведение при нажатии на `enter`:
При открытом результате поиска в комбобоксе - выбор элемента
Когда выбран элемент и просто инпут в фокусе - сабмит
При закрытом меню не вызываю обработчик события. Следовательно, не происходит вызов `preventDefault` и форма засабмитится
fix IF-1436
✅ нерелевантно
✅ нерелевантно
⬜ без …

fix(ComboBox): fix key down logic in closed state

---

packages/react-ui/components/Sticky/Sticky.tsx

При ресайзе страницы со `Sticky` в фиксированном состоянии не пересчитывается ширина 
Поправила расчет ширины
fix IF-1470
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

fix(Sticky): fix width calc in fixed state on page resize

---

packages/react-ui/components/DateInput/DateInput.tsx

Проблема с батчингом в Реакт18, который под строгим режимом автоматически пакетирует изменения в стейт, из-за чего цепочка изменений отличается от Реакт17, и это сказывается уже на визуальном отображении контрола.
Исправляется так же, использованием flushSync в проблемном месте.
Это самое место находится в `DateInput`.
Релиз для теста `4.16.0-DateInput-flushSync.1` (✅ проверен на проекте).
- `IF-1477`
- https://github.com/skbkontur/retail-ui/pull/3144#issuecomment-1535235366
✅ нерелевантно
⬜ прочие инструкции …

fix(DateInput): use `flushSync` in React@18

---

packages/react-ui/internal/themes/Theme2022.ts
packages/react-ui/internal/themes/Theme2022Dark.ts

В 22 теме подчеркивание в кнопках-ссылках и ссылках реализовано через `border-bottom`, а не `text-decoratoion`. Но иногда пользователям необходимо реализовать подчеркивание через `text-decoratoion` для однородности с другими элементами. [Пример](https://codesandbox.io/s/withered-leaf-sdxtv4?file=/src/index.js). Они отключают подчеркивание через  `border-bottom` и ожидают, что и в ссылке и в кнопке-ссылке заработает подчеркивание через  `text-decoratoion`. Проблема в том, что в кнопке оно не работает, а в ссылке работает.
Считаю что при отключении подчеркивания через `border-bottom`, `text-decoratoion` не должен автоматически включаться. Это касается и кнопки-ссылки и ссылки
Установила `linkHoverTextDecoration`  = `'none'` в 22х темах. 
Объяснить пользователям, что это правильное поведение …

chore(Link): change text decoration on hover in 22 theme

---

packages/react-ui/components/SidePage/SidePage.tsx

При переключении адаптива компонент с вуалью перемонтировался, из-за чего инкрементил z-index в рамках своей "группы".
--- 
Вуаль и SidePage находятся в одной группе приоритетности z-index'ов - `Sidepage: 9`.
`ZIndex` вычисляет для нового объекта `z-index` так: `последний z-index в группе` + `delta`.
При первом рендере как desktop, `SidePage` сначала монтирует вуаль и затем основной контент. Оба элемента обёрнуты в ZIndex.
Следовательно, вуаль всегда находится **под** основным контентом.
Затем, при срабатывании условия `isMobile`, вуаль удаляется, и грубо говоря забывает про свой предыдущий `z-index`.
А когда, возвращается десктопное отображение, вуаль монтируется заново, и теперь уже она **над** основным контентом.
Основной контент не удаляется, а просто меняет стиль отображение. Поэтому …

fix(SidePage): fix overlay when changing desktop->mobile->desktop

---

packages/react-ui/components/SidePage/SidePageHeader.tsx
packages/react-ui/components/Sticky/Sticky.tsx

[песочница](https://codesandbox.io/s/small-shadow-nycmjd)
При открытии `SidePage` первого уровня скроллинг в низ не приводит к ошибке, но при открытии вложенного `SidePage` при проскролировании в самый низ сайдпейджа получаем ошибку бесконечного обновления
Проблема возникла после [коммита](https://github.com/skbkontur/retail-ui/commit/5603ef6eedec2786a68bb86a8b1131b609aea25c), когда мы вынесли крестик в отдельный компонент.
Проблема оказалась в компоненте `Sticky`: раньше в SidePage мы рендерили 
```
<Sticky side="top" offset={stickyOffset}>
{this.closeIcon}
</Sticky>
```
что не вызывало перерендера Sticky:
```
public componentDidUpdate(prevProps: StickyProps, prevState: StickyState) {
if (!shallowEqual(prevProps, this.props) ...
```
Но после того, как мы заменили на 
```
<Sticky …
```

Sticky: fix max update depth error

---

packages/react-ui/internal/themes/DefaultTheme.ts
packages/react-ui/internal/themes/Theme2022.ts
packages/react-ui/internal/themes/Theme2022Dark.ts

В 22 темах пропала обратная совместимость для управления цветом тогла через переменную темы `toggleBgChecked`. 
Залинковала новые переменные `toggleContainerBg..` на старые
fix IF-1520
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее …

fix(Toggle): link toggleContainerBg to toggleBg variables

---

packages/react-ui/components/Link/Link.styles.ts
packages/react-ui/components/Link/Link.tsx

После #3254 в 22 темах перестало работать подчеркивание ссылки при фокусе. Проблема была в том, что создавалась дополнительная обертка, которая не изменялась при фокусе. Считаю, что это дополнительный аргумент в пользу отказа от `border-bottom` (IF-1490)
Добавила на обертку стили для фокуса. В creevey  невозможно это протестировать, так как он применяет стили из `oldLineText`
fix IF-1528
✅ нерелевантно
✅ нерелевантно
⬜ без …

fix(Link): fix link underline on focus

---

packages/react-ui/components/Link/Link.styles.ts

После #3185 в 22 темах при наведении на иконку перестало работать подчеркивание
Добавила подеркивание при наведении на корень ссылки, а не на сам текст
fix IF-1535
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

fix(Link): return underline when hovering over icon

---

packages/react-ui/components/Select/Select.tsx

Если у `Select` есть поисковая строка (проп `search`), то при открытии выпадашки может выбрасываться ошибка, при попытке фокуса в поисковую строку.
Причина проблемы в `setTimeout`, который решает эту проблему https://github.com/skbkontur/retail-ui/issues/1995. Т.е. если быстро размонтировать компонент, то `setTimeout` может вызваться после и спровоцировать ошибку.
Удалось исправить через `debounce`, т.к. при размонтировании ref-функция вызывается с null, следовательно можно прервать текущий отложенный автофокус.
`IF-1543`
✅ нерелевантно
⚠ Не удалось воспроизвести проблему юнит-тестом. Скриншотный тест решил слишком замороченно будет ради такого редкого сценария.
2. Добавлена …

fix(Select): reject focus of unmounted input

---

packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
packages/react-ui/components/GlobalLoader/GlobalLoaderView.tsx
packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx

Если вызвать методы в такой последовательности, не дождавшись появления лоадера
— ⚫ start ➔ 🟢 done
то всё норм, лоадер так и не появится.
А если же вызвать в такой последовательности
— 🟢 done ➔ ⚫ start ➔ 🟢 done
то лоадер появится, и понадобиться второй раз вызывать done.
Метод done ожидает определённого состояние контрола, чтобы "сбросить" это состояние. Делается это без проверок, ожидая, что это будет делать пользователь.
Добавил такую проверку вначале метода, чтобы состояние не сбрасывалось, если сбрасывать нечего.
`IF-1540`
⬜ нерелевантно
⬜ комментарии …

fix(GlobalLoader): repair of call chain done()➔start()➔done()

---

packages/react-ui-validations/src/Validations/PathHelper.ts
packages/react-ui-validations/tests/PathHelper.test.ts

При минификации кода имена переменных могут быть заменены на $ символ.
Например, такая конструкция
`validation.getNode(x => x.SomeProperty)`
преобразуется в `G.getNode($ -> $.SomeProperty)`
и падает с ошибкой `"Not supported or invalid path: $->$.SomeProperty"`
Добавила $ в разрешенные символы
fix IF-1557
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ все тесты и линтеры …

fix(validations): add $ as allowed symbol

---

packages/react-ui/components/ScrollContainer/ScrollContainer.styles.ts

В [документации](https://tech.skbkontur.ru/react-ui/#/Components/ScrollContainer) в первом примере с горизонтальным скроллом если навести курсор на пустое пространство под контеном и зажать shift - не сработает скролл. Проблема в том, что внутренний скролл контейнер сжимается до высоты контента и получается пустое пространство между внешним и внутренним контейнерм, в котором скролл не работает
Заменила `max-height` на `height` и  `max-width` на `width`. При этом у пользователей останется возможность применить их через пропы `maxHeight` и `maxWidth`
fix IF-1573
✅ нерелевантно
⬜ jsdoc для …

fix(ScrollContainer): stretch small content to size of container

---

packages/react-ui/internal/themes/Theme2022Dark.ts

После #3234 в `DropdownMenu` в 22 темной теме перестала работать переменная темы `bgSecondary`. Причина была в том, что раньше `DropdownMenu` использовал внутри себя `InternalMenu`, который использовал переменную `bgSecondary`. Теперь же он использует `Menu`, который использует переменную `menuBgDefault` и в 22 темной теме она не залинкована на `bgSecondary`
Залинковала `menuBgDefault` на `bgSecondary` в 22 темной теме 
fix IF-1583
✅ нерелевантно
✅ …

fix(DropdownMenu): fix bgSecondary in THEME_2022_DARK

---

packages/react-ui/components/Switcher/Switcher.tsx

`Switcher` имеет проп `items` с типом `SwitcherItems[]`, но тип `SwitcherItems` не экспоритируется, вынуждая пользователей писать тип самим
Добавила экспорт типа `SwitcherItems`
fix IF-1601
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …

fix(Switcher): export SwitcherItems type

---

packages/react-ui/.creevey/images/ScrollContainer/Never Show Scroll Bar/chrome.png
packages/react-ui/.creevey/images/ScrollContainer/Never Show Scroll Bar/firefox.png
packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
packages/react-ui/components/ScrollContainer/__stories__/ScrollContainer.stories.tsx

Проблема возникла в [SideMenu](https://git.skbkontur.ru/ui/ui-parking/-/merge_requests/527) при сворачивании до иконок: при сворачивании `ScrollContainer` считает, что есть переполнение контента внутри и добавляет горизонтальный скроллбар: 
https://github.com/skbkontur/retail-ui/assets/32093844/822caf3e-d69b-4a03-be45-b139cb4f6a24
Пробовала монтировать `ScrollContainer` только после полного открытия `SideMenu`, но тогда не срабатывает проп `showScrollbar = 'hover'`, так как при монтировании ScrollContainer'а мышь уже находится над ним и не срабатывает событие `onMouseEnter`. 
Считаю, что лучшим решением было бы добавить состояние`showScrollbar = 'never'` и изменять его на `showScrollbar = 'hover'` после открытия `SideMenu`
Добавила состояние`showScrollbar = 'never'`
Проблему с тем, что …

feat(ScrollСontainer): add value `never` to `showScrollbar` prop

---

packages/react-ui/components/Calendar/Calendar.tsx
packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
packages/react-ui/components/Paging/Paging.tsx
packages/react-ui/components/ScrollContainer/ScrollBar.tsx
packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
packages/react-ui/components/SidePage/SidePage.tsx
packages/react-ui/components/Tabs/Indicator.tsx
packages/react-ui/components/Tabs/Tabs.tsx
packages/react-ui/components/Tooltip/Tooltip.tsx
packages/react-ui/internal/DateSelect/DateSelect.tsx
packages/react-ui/internal/DropdownContainer/DropdownContainer.tsx
packages/react-ui/internal/FocusTrap/FocusTrap.tsx
packages/react-ui/internal/IgnoreLayerClick/IgnoreLayerClick.tsx
packages/react-ui/internal/InputLikeText/InputLikeText.tsx
packages/react-ui/internal/InternalMenu/InternalMenu.tsx
packages/react-ui/internal/Menu/Menu.tsx
packages/react-ui/internal/Popup/Popup.tsx
packages/react-ui/internal/RenderLayer/RenderLayer.tsx
packages/react-ui/lib/dom/tabbableHelpers.ts
packages/react-ui/lib/events/fixClickFocusIE.ts
packages/react-ui/lib/events/keyboard/identifiers.ts
packages/react-ui/lib/isInstanceOf.ts
packages/react-ui/lib/isInstanceOfForIE11.ts
packages/react-ui/lib/listenFocusOutside.ts
packages/react-ui/lib/rootNode/getRootNode.ts

В IE 11 внутри функции `isInstanceOf` `typeof` определяет конструкторы `Element`, `Node`, `MouseEvent` и другие как объекты. Хотя в хроме и других браузерах - как функции.
Как я понял, IE 11 не поддерживает фичи ES6, в том числе классы. Проверка, является ли поле `constructor` прокинутого класса функцией, вместо проверки самого класса решило проблему. Сделал исправленную версию функции `isInstanceOf`  в библиотеке.
Отдельным коммитом добавил фикс проверки, где использовалось определение isBrowser вместо вызова.
fix [IF-1576](https://yt.skbkontur.ru/issue/IF-1576)
✅ нерелевантно
⬜ jsdoc …

fix: globalObject.isInstanceOf in IE 11

---

packages/react-ui/components/Button/Button.tsx
packages/react-ui/components/Button/__tests__/Button-test.tsx

В теме 22, если использовать кнопку-ссылку <Button use={"link"} type={"submit"}> внутри формы, то на нажатие submit не срабатывает.
В 22 теме кнопка-ссылка использует внутри компонент Link, который если не задан href вызывает event.preventDefault.
Задал шаблонный href в Link для кнопки-ссылки.
Fix [IF-1627](https://yt.skbkontur.ru/issue/IF-1627), IF-1574
⬜ нерелевантно
✅ нерелевантно
⬜ без использования `any` (см. PR …

fix(Button): form submit with Button-Link in theme 22

---

packages/react-ui/internal/RenderContainer/RenderContainer.tsx

Криво работают порталы при серверном рендеринге в строгом режиме на 18-й версии Реакта.
Причина в двойном рендеринге в дев режиме.
Если точнее, то дело в специфичном двойном рендеринге метода `constructor()` у классовых компонентов:
> When __Strict Mode__ is on, React will call `constructor twice` in development and then throw away one of the instances. This helps you notice the accidental side effects that need to be moved out of the `constructor()`. [^1]
В компоненте `RenderContainer` в методе `constructor()` как раз были побочные эффекты - в DOM монтировался div-контейнер для портала.
Песочница с багом:
— https://stackblitz.com/edit/stackblitz-starters-hhdbkc?file=app%2Fpage.tsx
[^1]: https://react.dev/reference/react/Component#constructor-caveats
Для исправление достаточно было …

fix(RenderContainer): remove side effects from constructor

---

packages/react-ui/components/Token/Token.tsx
packages/react-ui/components/Token/__tests__/Token-test.tsx
packages/react-ui/lib/utils.ts

В #3337 по ошибке оставил возможность фокусироватсья на крестике
1. Вернул `tabbable={false}`
2. Научил `aria-label` работать с `ReactElement` — в решении я придерживаюсь эвристики, что текст будет в первой ноде и выполняю поиск только в ней. Текст может находиться сразу в нескольких нодах, либо во второй, третьей и т.д., но это менее вероятная ситуация, поэтому не стал её поддерживать — в таком случае будет просто выводиться пустая строка или часть текста
IF-1670
⬜ нерелевантно
3. Добавлена (обновлена) документация
✅ jsdoc для утилит и хелперов …

fix(Token): prevent focus on cross

---

packages/react-ui-validations/.prettierignore
packages/react-ui-validations/src/ValidationContainer.tsx
packages/react-ui-validations/src/ValidationContextWrapper.tsx
packages/react-ui-validations/stories/ValidationContainer.stories.tsx
packages/react-ui-validations/tests/ValidationContainer.test.tsx

Не пробрасывается data-tid с ValidationContainer, это сильно усложняет е2е тестирование в продуктах
Прокинуть data-tid через ValidationContainer
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

feat: пробрасывается data-tid с validation container  на корневой span

---

packages/react-ui/components/DatePicker/DatePicker.tsx

В консоли летит ворнинг что у DatePicker проп width обязательный, но это не правда, есть рассинхрон с ts interface
убрать обязательность width в PropTypes
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

[DatePicker] prop 'width' in PropTypes is not required

---

packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/chrome.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/chrome2022.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/chrome2022Dark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/chrome8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/chromeDark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/chromeFlat8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/firefox.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/firefox2022.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/firefox2022Dark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/firefox8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/firefoxDark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/idle/firefoxFlat8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/chrome.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/chrome2022.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/chrome2022Dark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/chrome8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/chromeDark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/chromeFlat8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/firefox.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/firefox2022.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/firefox2022Dark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/firefox8px.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/firefoxDark.png
packages/react-ui/.creevey/images/TokenInput/with placeholder and width/selected/firefoxFlat8px.png
packages/react-ui/components/Token/TokenView.tsx
packages/react-ui/components/TokenInput/TokenInput.styles.ts
packages/react-ui/components/TokenInput/TokenInput.tsx
packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
packages/react-ui/internal/themes/DefaultTheme.ts

После #3251 в TokenInput образовалась пара проблем, которые были найдены во время тестирования next в продуктах:
1. Была удалена переменная `tokenInputLineHeight`, которая использовалась в продукте. Значит, она нужна.
2. При наличии длинного плейсхолдера в TokenInput, после выбора первого токена из списка, высота всего TokenInput могла стать больше, чем нужно.
| До | После |
| --- | --- |
| ![image](https://github.com/skbkontur/retail-ui/assets/4607770/c3312b10-ffc1-4ea1-b020-efd8c9beb142)![image](https://github.com/skbkontur/retail-ui/assets/4607770/bbe7ebc0-7852-435f-a4a8-651253afa7fc) | ![image](https://github.com/skbkontur/retail-ui/assets/4607770/a0c52f77-97ad-4e71-be39-1bb6da223a3a)![image](https://github.com/skbkontur/retail-ui/assets/4607770/727aba61-2dd2-4664-98a6-dc3ed8c3f956) | …

fix(TokenInput): fixes after visual changes

---

packages/react-ui/components/Button/Button.styles.ts
packages/react-ui/components/Button/Button.tsx
packages/react-ui/components/Button/__stories__/Button.stories.tsx
packages/react-ui/internal/themes/Theme2022.ts

Во время влития #3272, когда теста из #3376 еще не было, в стилях появился important, который ломал работу переменной btnTextHoverBg.
А при влитии #3376 не был подлит актуальный next с обновленной версией creevey. В результате стал падать линт на некорректном более скипе и тест на переменную btnTextHoverBg стал скипаться полностью.
Поправил проблемную переменную и скип.
✅ нерелевантно
✅ нерелевантно
✅ без использования …

fix(Button): fix btnTextHoverBg var

---

packages/react-ui/components/Token/Token.tsx
packages/react-ui/components/Token/__tests__/Token-test.tsx
packages/react-ui/lib/__tests__/reactGetTextContent-test.tsx
packages/react-ui/lib/utils.ts

Если условно рендерить что-то внутри `Token`, то появляется ошибка.
Добавил в хелпер `getChildrenText` возврат пустой строки на boolean.
Fix [IF-1734](https://yt.skbkontur.ru/issue/IF-1734)
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее …

fix(Token): correct render with conditional children

---

packages/react-ui/components/Calendar/DayCellView.tsx
packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/components/DropdownMenu/__tests__/DropdownMenu-test.tsx
packages/react-ui/components/MenuItem/MenuItem.tsx
packages/react-ui/components/Paging/Paging.tsx
packages/react-ui/components/Select/__tests__/Select-test.tsx
packages/react-ui/components/Tabs/Tab.tsx
packages/react-ui/internal/CommonWrapper/CommonWrapper.tsx
packages/react-ui/internal/CommonWrapper/__tests__/CommonWrapper-test.tsx
packages/react-ui/internal/CommonWrapper/__tests__/getCommonVisualStateDataAttributes.test.ts
packages/react-ui/internal/CommonWrapper/__tests__/getVisualStateDataAttributes.test.ts
packages/react-ui/internal/CommonWrapper/__tests__/tryGetBoolean.test.ts
packages/react-ui/internal/CommonWrapper/utils/extractCommonProps.ts
packages/react-ui/internal/CommonWrapper/utils/getCommonVisualStateDataAttributes.ts
packages/react-ui/internal/CommonWrapper/utils/getVisualStateDataAttributes.ts
packages/react-ui/internal/CommonWrapper/utils/tryGetBoolean.ts

В дом стало попадать много лишних атрибутов вида, data-visual-state='false' -- особенно это видно в календаре
Вообще не прокидывать false значения, прокидывать только true, тем самым можно либо добавлять атрибут либо нет, так работают нативные атрибуты типа disabled
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ в коде нет лишних …

Visual state attributes looks like as native attributes

---

packages/react-ui/components/Autocomplete/Autocomplete.tsx
packages/react-ui/components/Autocomplete/__tests__/Autocomplete-test.tsx
packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx

Нативный браузерный [autofill](https://html.spec.whatwg.org/multipage/forms.html#attr-form-autocomplete) дублирует и перекрывает подсказки в `<Autocomplete>` и `<ComboBox>`
_Autocomplete_
_ComboBox_
- В `<ComboBoxView>` для `<input>` указал атрибут [`autocomplete="off"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values).
- В `<Autocomplete>` добавил атрибут для десктопной и мобильной версии
_P.S. Не стал добавлять аналогичный атрибут в `<TokenInput>`, который использует `<textarea>`. Не смог воспроизвести autofill-поведение `<textarea>` в Chrome, Firefox и Safari_
- https://yt.skbkontur.ru/issue/IF-1624/
- https://kontur.slack.com/archives/C013HTCE18Q/p1705926378481079
⬜ скриншоты для верстки и …

fix(Autocomplete, ComboBox): disable browser autofill

---

contributing.md
packages/react-ui/components/TokenInput/TokenInput.tsx
packages/react-ui/components/TokenInput/__tests__/TokenInput-test.tsx
packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
packages/react-ui/lib/featureFlagsContext/ReactUIFeatureFlagsContext.tsx

Удаление `tokenInputRemoveWhitespaceFromDefaultDelimiters` фиче-флага
Удалила фиче-флаг. Теперь в TokenInput из дефолтных разделителей удалён пробел по умолчанию
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

feat: remove tokenInputRemoveWhitespaceFromDefaultDelimiters feature flag

---

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/eslint.config.js
packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
packages/react-ui/lib/featureFlagsContext/ReactUIFeatureFlagsContext.tsx

Удаление comboBoxAllowValueChangeInEditingState фиче-флага
Удалила фиче-флаг. Теперь можно менять значение value в Combobox в режиме редактирования
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

feat: remove comboBoxAllowValueChangeInEditingState feature flag

---

packages/react-ui/.styleguide/helpers.js
packages/react-ui/components/Textarea/Textarea.tsx
packages/react-ui/components/Textarea/TextareaWithSafari17Workaround.tsx
packages/react-ui/lib/client.ts
packages/react-ui/lib/featureFlagsContext/ReactUIFeatureFlagsContext.tsx

Удаление textareaUseSafari17Workaround фиче-флага
Удалила фиче-флаг. Но оставила решение для определенных версий Сафари, в которых баг воспроизводится
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

feat: remove textareaUseSafari17Workaround feature flag

---

packages/react-ui-validations/.creevey/images/FeatureFlags/fixedValidationTextColors/chromeDefault.png
packages/react-ui-validations/docs/Pages/Displaying/FeatureFlags/FeatureFlagsContext.md
packages/react-ui-validations/src/ReactUiDetection.ts
packages/react-ui-validations/src/ValidationText.tsx
packages/react-ui-validations/src/utils/getValidationTextColor.ts
packages/react-ui-validations/stories/FeatureFlags.stories.tsx
packages/react-ui-validations/stories/ValidationContainer.stories.tsx
packages/react-ui-validations/typings/theme-context.d.ts
packages/react-ui/internal/ThemePlayground/constants.ts
packages/react-ui/internal/themes/DarkTheme.ts
packages/react-ui/internal/themes/DefaultTheme.ts

Цвета для текста сообщения вшиты в пакет валидаций.
Из-за чего их нельзя кастомизировать, нормально обновлять, и настраивать под тёмную тему.
Добавил переменные темы `validationsTextColorError` и `validationsTextColorWarning` и применил `ThemeContext` из `react-ui` внутри `react-ui-validations`.
В пакете валидаций пакет `react-ui` указан в `peerDependencies`, поэтому мы можем использовать его компоненты.
Подобным образом мы уже используем `Tooltip`.
[IF-1788](https://yt.skbkontur.ru/issue/IF-1788) Валидации: цвет для текста сообщения нельзя кастомизировать
⬜ нерелевантно
⬜ jsdoc для …

feat(validations): use `ThemeContext`

---

packages/react-ui/components/Calendar/Calendar.tsx
packages/react-ui/components/DatePicker/DatePicker.md

В рамках задачи [IF-87 Компонент выбора периода](https://yt.skbkontur.ru/issue/IF-87/Komponent-vybora-perioda) заметил, что в PR #3415 были удалены не все упоминания пропсов `periodStartDate` и `periodEndDate`
- Починил пример с кастомными днями в `<DatePicker />` 
- Удалил пример из документации `<DatePicker />` 
- Удалил описание jsdoc props `periodStartDate` и `periodEndDate` в `<Calendar />`
- https://tech.skbkontur.ru/react-ui/#/Components/Calendar/Calendar
- [https://tech.skbkontur.ru/react-ui/#/Components/DatePicker](https://tech.skbkontur.ru/react-ui/#/Components/DatePicker:~:text=VIEW%20CODE-,%D0%9F%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%20%D0%B4%D0%B0%D1%82,-%D0%9F%D0%BE%D0%B4%D0%B1%D1%80%D0%BE%D0%B1%D0%BD%D1%8B%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D0%B2)
1. Добавлены тесты на …

docs(DatePicker,Calendar): remove period props

---

packages/react-ui/components/Button/Button.md

В виду отсутствия примера использования узкой кнопки и показа состояния валидации, пользователь может не знать о такой возможности
Добавил примеры использования
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее

docs(Button): add example with narrow, warning, error

---

packages/react-ui-validations/src/Validations/PathHelper.ts
packages/react-ui-validations/tests/Validator.test.ts

По гайдам [узел может содержать null или undefined](https://tech.skbkontur.ru/react-ui-validations/#/missing-nodes) , но в случае когда узел содержит опциональный параметр в типе, возникает ошибка.
Это hot-fix для задачи [IF-1828](https://yt.skbkontur.ru/issue/IF-1828/Validator-Obnovit-ispolzovanie-tipa-NonNullable)
Добавили модификатор `-?` 
Задача: [IF-1828](https://yt.skbkontur.ru/issue/IF-1828/Validator-Obnovit-ispolzovanie-tipa-NonNullable)
⬜ нерелевантно
⬜ прочие инструкции (`README.md`, `contributing.md` и …

fix(): add modifier -? to NonNullableRecursive type

---

packages/react-ui/components/Autocomplete/Autocomplete.md

В виду отсутствия примера использования компонента с использованием props (selectAllOnFocus, leftIcon и rightIcon, menuWidth, menuPos, hasShadow, borderless), пользователь может не знать о такой возможности
Добавил примеры использования
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и …

docs(Autocomplete): add examples

---

packages/react-ui-validations/src/ValidationWrapperInternal.tsx
packages/react-ui-validations/tests/ValidationContainer.test.tsx
packages/react-ui/components/Calendar/Calendar.tsx
packages/react-ui/components/DatePicker/DatePicker.md

Предыдущий PR (3450) был закрыт, так как вливание было в ветку с будущей мажорной версией 5.х, а изменение -- не ломающее, а фикс бага.
Если при проверке по нажатию submit несколько (2 и более) полей станут невалидными, а затем их значения исправятся программно, то событие onValidationUpdated не вызовется.
Но если поле одно, то всё работает.
Вызов resolve внутри Promise теперь находится внутри коллбэка. Добавлены unit-тесты, проверяющие описанное поведение. В unit-тестах screen.getByRole(...).click() заменен на await userEvent.click(screen.getByRole(...)), так как иначе тесты падают.
[IF-1719](https://yt.skbkontur.ru/issue/IF-1719/Validacii.-Esli-po-sabmitu-2-polej-stanut-nevalidnymi-to-programmnoe-ispravlenie-ne-vyzyvaet-onValidationUpdated)
[Предыдущий …

fix: program validation on multi fields IF-1719

---

packages/react-ui/lib/taskWithDelayAndMinimalDuration.ts

Если Лоадер активен при маунте, то в 18 реакте не отображается спинер. [Песочница](https://codesandbox.io/p/sandbox/auto-components-d8qjks?file=%2Fpackage.json) 
Решение нашел Эдуард в веточке IF-1780, решили продублировать в мастер так как это баг.
Причина: в 18 реакте компонент рендерится дважды:
при первом маунте вызывается `this.spinnerTask.start()`, которая запускает лоадер (и сетит isTaskActive в true)
Затем компонент анмаунтится.
При повторном маунте в методе старт проверяется что лоадер еще не запущен:
```
if (this.isTaskActive) {
return;
}
```
а так как мы при анмаунте не сбросили переменную `isTaskActive` в `false`, то выполение прерывается и спинер не показывается. 
Решение простое - при анмаунте устанавливать `isTaskActive` в `false`
fix IF-1825
1. Добавлены тесты на все …

fix(Loader): fix Loader in 18 react

---

packages/react-ui/components/RadioGroup/RadioGroup.tsx
packages/react-ui/components/RadioGroup/__tests__/RadioGroup-test.tsx
packages/react-ui/components/Select/Select.tsx
packages/react-ui/components/Select/__tests__/Select-test.tsx
packages/react-ui/components/Token/Token.tsx
packages/react-ui/components/Token/__tests__/Token-test.tsx

Пришел Женя Иванов, с проблемой, что сложно тестировать компоненты RadioGroup, Select, Token
Сложно понять задисаблен ли контрол.
Еще заметили баг что в Select при использовании _renderButton не прокидывается disabled проп
Добавили визуальные атрибуты, прокинули disabled
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
⬜ в коде нет лишних …

fix(Select): pass disabled in _renderButton, add visual attributes

---

packages/react-ui/.creevey/images/ZIndex/Several Roots/chrome2022.png
packages/react-ui/README.md
packages/react-ui/internal/RenderContainer/RenderContainer.tsx
packages/react-ui/internal/RenderContainer/RenderInnerContainer.tsx
packages/react-ui/internal/ZIndex/ZIndex.tsx
packages/react-ui/internal/ZIndex/__stories__/ZIndex.stories.tsx
packages/react-ui/lib/listenFocusOutside.ts

Когда на странице есть несколько реакт-рутов, то выпадашки в них не могут правильно позиционироваться, т.к. теряется контекст.
Самое простое решение на данный момент, это пытаться интерпретировать контекст через dom окружение.
Также, в контексте виджет-потребитель, текущее решение потребует обновить пакет только в виджете.
Подробнее всё описано в задаче и в `README.md`.
---
`ZIndexContext` состоит из 2-х полей `parentLayerZIndex` и `maxZIndex`.
Где `parentLayerZIndex` это фактически свойство `z-index` родителя.
А `maxZIndex` почти всегда равна `Infinity`, кроме случая с активным Лоадером, который можно обнаружить через data-tid.
| Пример в readme выглядит так |
| --- |
| ![image](https://github.com/user-attachments/assets/82a306a6-7766-4023-9930-cb25a1c2e1d3) |
— …

feat(ZIndex): add support several React roots

---

packages/react-ui-validations/.storybook/featureFlagsConfig/featureFlagsConfig.tsx

Правка отображение текста в переключателе фиче-флагов, когда есть фиче-флаги
Изменение логики фильтрации в featureFlagsConfig
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее

docs(featureFlags): update featureFlagsConfig filter

---

packages/react-ui/.storybook/featureFlagsConfig/featureFlagsConfig.tsx
packages/react-ui/.storybook/webpack.config.js
packages/react-ui/typings/storybookAddonMultiple.d.ts

Добавил в переключатель featureFlags текст, когда фиче-флагов не будет
Заменил в storybook webpack config slice(2) на slice(1)
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅  в коде нет лишних изменений

docs(featureFlags): update webpack.config storybook, featureFlagsConfig

---

packages/react-ui/components/Calendar/Calendar.md

Дополнил документацию `<Calendar>` примером календаря с кастомизацией темы и кастомным рендерингом дня
[Обращение с вопросами по кастомизации DatePicker / Calendar](https://chat.skbkontur.ru/kontur/pl/4qbgrjo7bpyupy76ehrtidbo4y)
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее …

docs(Calendar): Add Calendar example with prices

---

packages/react-ui/components/ScrollContainer/ScrollContainer.tsx

Компонент `ScrollContainer` не предоставляет возможность получить доступ к элементу прокрутки за его пределами.
Такая функциональность крайне полезна и в качестве яркого примера можно привести виртуализацию, а именно когда задействуется прокрутка внешнего документа, в частности когда необходимо назначить пользовательский родительский элемент прокрутки.
Для решения проблемы был добавлен проп `scrollRef` с типом `React.Ref` (выбор типа обусловлен заявленной поддержкой react начиная с 16.9.0).
Элемент прокрутки присваивается `refInner` и внутри `refInner` уже присваивается `scrollRef` с помощью хелпера `callChildRef` (чтобы поддержать [ref callback'и](https://react.dev/reference/react-dom/components/common#ref-callback) и чтобы избежать [лишних вызовов (последний …

feat(ScrollContainer): new prop 'scrollRef'

---

packages/react-ui-validations/src/ValidationContextWrapper.tsx
packages/react-ui-validations/src/utils/featureFlagsContext/ValidationsFeatureFlagsContext.tsx
packages/react-ui-validations/stories/docs/FeatureFlags.mdx

Удаление тестового фиче-флага, который был нужен для проверки переключателя фиче-флагов в документации.
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

docs(featureFlags): remove testFeatureFlags validations

---

packages/react-ui/.storybook/preview-head.html
packages/react-ui/components/__stories__/Versions/Versions.mdx

Пустое содержание на странице версий
Убрал содержание для компонента Versions. Пока в mdx файле в Meta не поддерживается parameters для отключения toc. Поэтому сделано вручную через <Unstyled /> и css
[YouTrack](https://yt.skbkontur.ru/issue/IF-1918/Dopolneniya-dlya-perehoda-na-novuyu-dokumentaciyu)
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ все тесты и линтеры на CI …

docs(Versions): disable table of contents

---

packages/react-ui/components/Button/getInnerLinkTheme.ts
packages/react-ui/lib/theming/ThemeFactory.ts
packages/react-ui/lib/utils.ts

Cейчас `ThemeFactory.create` может принимать любое значение отличное от `null (T extends {})`.
Ограничил тип аргумента `theme` до доступных токенов в теме:
- Добавил служебный тип `NoInfer`.
- Обернул аргумент типа метода `create` в `NoInfer`.
- Пофиксил ошибку ТС, возникшую из-за правки.
Пример работы: 
resolve [IF-283](https://yt.skbkontur.ru/issue/IF-283) Поправить типизацию ThemeFactory.create
✅ нерелевантно
✅ нерелевантно
3. Изменения корректно …

refactor(ThemeFactory): disallow arbitrary theme tokens by default

---

packages/react-ui/components/Button/Button.tsx
packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
packages/react-ui/components/Paging/Paging.tsx
packages/react-ui/components/Select/__tests__/Select-test.tsx

В рамках мажора решили переименовать корневой дататид `Button` в `root`, по аналогии с остальными компонентами.
- Поменял местами дататиды кнопки `root` и `rootElement`.  `rootElement` не стал менять, так как потом там может быть не только кнопка, но и ссылка и ещё что-то.
- Отрефакторил прокидывания дататида в `Paging`, сделал как в других компонентах. 
resolve [IF-1742](https://yt.skbkontur.ru/issue/IF-1742)
✅ нерелевантно
✅ нерелевантно
3. Изменения …

refactor(Button): rename root data-tid

---

packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
packages/react-ui-testing/Tests/PagingTests/PagingTest.cs
packages/react-ui/.creevey/images/ScrollContainer/Hide Scroll Bar/hideScroll/chrome2022/afterScroll.png
packages/react-ui/.creevey/images/ScrollContainer/Hide Scroll Bar/hideScroll/chrome2022/beforeScroll.png
packages/react-ui/.creevey/images/ScrollContainer/Hide Scroll Bar/hideScroll/chrome2022/duringScroll.png
packages/react-ui/.creevey/images/ScrollContainer/Hide Scroll Bar/hideScroll/firefox2022/afterScroll.png
packages/react-ui/.creevey/images/ScrollContainer/Hide Scroll Bar/hideScroll/firefox2022/beforeScroll.png
packages/react-ui/.creevey/images/ScrollContainer/Hide Scroll Bar/hideScroll/firefox2022/duringScroll.png
packages/react-ui/components/Button/Button.tsx
packages/react-ui/components/Checkbox/Checkbox.tsx
packages/react-ui/components/FileUploader/FileUploader.tsx
packages/react-ui/components/Input/Input.tsx
packages/react-ui/components/MenuFooter/MenuFooter.tsx
packages/react-ui/components/MenuHeader/MenuHeader.tsx
packages/react-ui/components/MenuItem/MenuItem.tsx
packages/react-ui/components/Paging/Paging.tsx
packages/react-ui/components/Paging/__tests__/Paging-test.tsx
packages/react-ui/components/Radio/Radio.tsx
packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
packages/react-ui/components/ScrollContainer/__creevey__/ScrollContainer.creevey.ts
packages/react-ui/components/ScrollContainer/__stories__/ScrollContainer.stories.tsx
packages/react-ui/components/Switcher/Switcher.tsx
packages/react-ui/components/Tabs/Tab.tsx
packages/react-ui/components/Textarea/Textarea.tsx
packages/react-ui/components/Toggle/Toggle.tsx
packages/react-ui/components/Toggle/__stories__/Toggle.stories.tsx
packages/react-ui/components/Token/Token.styles.ts
packages/react-ui/components/Token/Token.tsx
packages/react-ui/internal/themes/BasicDarkTheme.ts
packages/react-ui/internal/themes/BasicLightTheme.ts

Для 5.0 осталось удалить все устаревшие сущности, которые так или иначе помечены deprecated. Кроме пропа `mask` в `Input` и всего, что с ним связано. Его мы решили пока оставить.
- Удалил проп `hideScrollBar` в `ScrollContainer`.
- Удалил проп `Color` в `Toggle`.
- Удалил проп `shouldBeVisibledWithLessThanTwoPages` в `Paging`.
- Удалил устаревшие типы размера в ряде компонентов.
- Переменные `color` в `Token` - `Token[use](Idle|Active)`, `tokenWhite`, `tokenBlack`
- Переименовал некоторые переменные и стили `Token`, убрал из названия цвет и привёл названия к принятому стилю наименования.
resolve IF-1960
✅ нерелевантно
⬜ styleguidist для пропов и …

refactor(react-ui): remove deprecated entities

---

packages/react-ui/components/Toast/ToastView.tsx
packages/react-ui/components/Toast/__tests__/Toast-test.tsx

Во время обновления зависимостей (#3400) почему-то сломалась типизация, которую "полечили" неправильным использованием `CommonWrapper`. Из-за этого `ToastDataTids.toastView` стал перезатираться.
<details>
<summary>Неправильное использование, проблема с пропами</summary>
</details>
<details>
<summary>Правильное использование, проблема с типами</summary>
</details>
Проблему с типами решить пока не удалось. Поэтому переделал использование `CommonWrapper` и проброс пропов по другому, но корректно.
Старый проброс `...rest` в `div` посчитал излишним, т.к. список возможных пропов там ограничен. Это позволило упростить решение.
IF-1990
⬜ нерелевантно
⬜ …

fix(Toast): restore root data-tid

---

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
packages/react-ui/lib/featureFlagsContext/ReactUIFeatureFlagsContext.tsx

После удаления флага появились баги в Фиас и в самом Комбобоксе. Решили вернуть фичефлаг.
- Вернул фичефлаг, убрал поведение под него. 
- Вернул тесты поведения под фичефлагом.
- Удалил упоминание фичефлага для Textarea из документации, т.к. он не используется нигде.
fix [IF-1988](https://yt.skbkontur.ru/issue/IF-1988)
⬜ нерелевантно
✅ комментарии для неочевидных мест в коде
✅ прочие инструкции (`README.md`, `contributing.md` и др.)
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
⬜ все …

fix(ComboBox): restore comboBoxAllowValueChangeInEditingState feature flag

---

packages/react-ui/.creevey/images/TokenInput/[combined] filled/editToken/chrome2022/editToken.png
packages/react-ui/.creevey/images/TokenInput/[combined] filled/editToken/chrome2022Dark/editToken.png
packages/react-ui/.creevey/images/TokenInput/[combined] filled/selectAndType/chrome2022/typed.png
packages/react-ui/.creevey/images/TokenInput/[combined] filled/selectAndType/chrome2022Dark/typed.png
packages/react-ui/.creevey/images/TokenInput/empty combined/selectFirst/chrome2022.png
packages/react-ui/.creevey/images/TokenInput/empty combined/selectFirst/chrome2022Dark.png
packages/react-ui/components/TokenInput/TokenInput.md
packages/react-ui/components/TokenInput/locale/locales/en.ts
packages/react-ui/components/TokenInput/locale/locales/ru.ts

После [отключения](https://github.com/skbkontur/retail-ui/pull/3434) фиче флагов не убрали из локали упоминание пробела в качестве одного из разделителей по умолчанию.
Убрал из локали и доки локали упоминание пробела.
✅ нерелевантно
✅ прочие инструкции (`README.md`, `contributing.md` и др.)
⬜ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает …

chore(TokenInput): remove mention of whitespace from default locale

---

packages/react-ui/.creevey/images/ThemeProvider/Unlink Vars/chrome2022.png
packages/react-ui/components/Paging/Paging.styles.ts
packages/react-ui/internal/ThemePlayground/UnlinkVarsPlayground.tsx
packages/react-ui/internal/ThemePlayground/__creevey__/ThemeProvider.creevey.ts
packages/react-ui/internal/ThemePlayground/__stories__/ThemePlayground.stories.tsx
packages/react-ui/internal/themes/BasicDarkTheme.ts
packages/react-ui/internal/themes/BasicLightTheme.ts

У некоторых переменных есть неочевидные для пользователя связи и стили меняются в неожиданных местах.
- Завёл переменную `pagingPageLinkColor` для `Paging`, эта переменная и `pagingForwardLinkColor` наследуются от `textColorDefault`.
- Завёл переменную `bgChecked`, `checkboxCheckedBg` наследуется от неё. А от неё уже наследуется переменная `radioCheckedBgColor`.
- `fileUploaderLinkColor` теперь наследуется от `textColorDefault`.
Close [IF-1993](https://yt.skbkontur.ru/issue/IF-1993) Связь переменных в 5.0
⬜ нерелевантно
⬜ комментарии для неочевидных мест в …

chore(Checkbox, Radio, FileUploader, Paging): unlink vars

---

packages/react-ui/components/Button/Button.styles.ts
packages/react-ui/components/Link/Link.tsx
packages/react-ui/lib/styles/Mixins.ts

В https://github.com/skbkontur/retail-ui/pull/3521 убрали возможность выделения текста. Но оказалось, что для пользователей это важный сценарий.
Убрал стиль с `user-select: none` у `Button` и `Link`. У `Button component=a`  появилось выделение текста при двойном клике, из-за чего я изначально убирал выделение. Это можно через js убрать, но кажется, что не очень важно.
✅ нерелевантно
✅ нерелевантно
⬜ без использования `any` …

refactor(Button, Link): return user select

---

packages/react-ui/components/DatePicker/DatePicker.tsx
packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx

При использовании пропа onMonthChange в DatePicker при нажатии "Сегодня" возникает ошибка.
Оказалось, что перемотка календаря вызывалась дважды: первая еще не заканчивалась, а вторая уже начиналась и календарь листался слишком сильно, пролистывая текущую дату и месяц, из-за чего возникала ошибка.
Я оставила лишь один вызов метода, который вызывает перемотку календаря.
Создала историю с названием TEST, с помощью которой легко проверить, что всё правильно работает. Для этого нужно выбрать дату позже 01.01.2024 или раньше 01.07.2024 и нажать "Сегодня". Раньше выкидывалась ошибка, теперь же всё работает правильно.
Тестовую историю планирую убрать после ревью, так как считаю, что это поведение постоянно проверять не нужно.
Задача [IF-1992](https://yt.skbkontur.ru/issue/IF-1992)
1. Добавлены …

fix(DatePicker): scrolling to today

---

packages/react-ui/internal/ZIndex/ZIndex.tsx

При получении контекста через dom есть прямое обращение к `document`. 
Доступ к `document/window` должен быть через `global-object`, либо через html-элементы полученные через ref, иначе `Upgrade.setWindow()` не будет работать ожидаемо.
Заменила 
```const noscript = document.querySelector(...); ```
на 
```
const root = element.getRootNode() as HTMLElement;
const noscript = root.querySelector(...);
```
Задача [IF-1949](https://yt.skbkontur.ru/issue/IF-1949)
✅ нерелевантно …

fix(ZIndex): change document to getRootNode

---

packages/react-ui-validations/package.json
packages/react-ui/package.json
scripts/creevey-prepare.js

1. При запуске Creevey контрибьютеры забывают создавать `.env` файл
2. Некоторым контрибьютерам неочевидно, что `yarn creevey:ui` требует параллельного запуска `yarn storybook:test` 
3. В проектах в package.json **дублируются**:
- URL Storybook (`http://localhost:6060`)
- Таймаут, если Storybook не отвечает (`-t 300000`) 
Добавил помощь контрибьютерам, которые впервые вызывают `yarn creevey:ui`
**1. Нет .env файла для прогона скриншотных**
https://github.com/user-attachments/assets/4b6adbdf-5b83-46f1-8f8d-e0f43f53e64f
**2. Не запущен Storybook**
https://github.com/user-attachments/assets/1123abdb-1688-4e41-ad16-ae36b17c5829
**3. Creevey не дождался ответа Storybook**
**Обобщил код перед запуском Creevey**
- Заменил wait-on на `script/creevey-prepare.js` с проверками
- Вместо URL нужно …

feat(creevey): Add creevey's help messages for new contributors

---

packages/react-ui/components/SingleToast/SingleToast.tsx

В react 16 при отрисовке тоста через SingleToast.push в useEffect возникает ошибка.
Убрал flushSync 
Fix [IF-1967](https://yt.skbkontur.ru/issue/IF-1967)
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

fix(SingleToast): use flushSync only in React@18

---

packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/chrome2022/0.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/chrome2022/1.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/chrome2022/2.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/chrome2022Dark/0.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/chrome2022Dark/1.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/chrome2022Dark/2.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/firefox2022/0.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/firefox2022/1.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/firefox2022/2.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/firefox2022Dark/0.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/firefox2022Dark/1.png
packages/react-ui/.creevey/images/TokenInput/size/MenuItem inherits size/firefox2022Dark/2.png
packages/react-ui/.creevey/images/TokenInput/size/chrome2022.png
packages/react-ui/.creevey/images/TokenInput/size/chrome2022Dark.png
packages/react-ui/.creevey/images/TokenInput/size/firefox2022.png
packages/react-ui/.creevey/images/TokenInput/size/firefox2022Dark.png
packages/react-ui/components/TokenInput/TokenInput.tsx
packages/react-ui/components/TokenInput/TokenInputMenu.tsx
packages/react-ui/components/TokenInput/__creevey__/TokenInput.creevey.ts
packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx

TokenInput не прокидывает `size` до пунктов меню. Легко проверить в доке.
- Прокинул проп
- Обновил скриншотные тесты для `size`, чтобы ловить такие случаи
Задачу на заводил
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее

fix(TokenInput): forward prop `size` to menu items

---

packages/react-ui/.creevey/images/ComboBox/With Menu Align And Menu Pos/chrome2022.png
packages/react-ui/.creevey/images/Select/With Menu Align And Various Width/chrome2022.png
packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
packages/react-ui/components/Select/__creevey__/Select.creevey.ts
packages/react-ui/components/Select/__stories__/Select.stories.tsx
packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx

В `ComboBox` с `5.0` сломался проп `menuAlign` со значением `right`.
При избавлении от `DropdownContainer` потеряли проброс пропа `menuAlign`. Значение `left` работало т.к. умолчательное
https://github.com/skbkontur/retail-ui/commit/723ec43470bec9f0dd89b5f899ffffb90004a538#diff-e0e7a85c99ee1a5128183657766ce12f6c35c467bc8fb3f2f6bed591d68ad74cL258
Попутно расскипал стори в `Select`, где тестировалось выравнивание меню. По аналогии сделал стори для `ComboBox`
`IF-2085`
⬜ нерелевантно …

fix(ComboBox): fix menuAlign

---

packages/react-ui-testing/SeleniumTesting/Controls/Input.cs

Имелась проблема медленной очистки поля input, а именно посимвольно. В проекте использовались поля, где вводились значения длинной 20 символов и более. И метод clear довольно долго отрабатывал.
Заменил посимвольное удаление на "выделить всё сразу и удалить" через Keys.Control + "a" и Keys.Delete
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
⬜ все тесты и линтеры на CI …

Corrected clear method for quick cleaning of input field in Input.cs

---

packages/react-ui/components/DateInput/DateInput.tsx
packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx

Если на кликнуть на контролы `DatePicker/DateInput` в состоянии `disabled`, чтобы выделился хотя бы один фрагмент, то после этого на каждый `componentDidUpdate` этот фрагмент продолжит выделяться.
Если что-то вводить после выделения в контролируемом Инпуте, то фокус будет ломаться на каждый ввод.
Вызывать `selectNode` только в незаблокированном состоянии.
Fix [IF-1954](https://yt.skbkontur.ru/issue/IF-1954)
✅ нерелевантно
✅ нерелевантно
3. Изменения …

fix(DateInput): disallow date fragment selection in disabled state

---

packages/react-ui/components/Calendar/DayCellView.tsx
packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx

`Calendar` позволяет кликом выбирать невалидную дату - день, выходящий за рамки `minDate` или `maxDate`, хотя визуально эта дата остаётся заблокированной.
Запретить клик по заблокированной дате.
fix [IF-1905](https://yt.skbkontur.ru/issue/IF-1905)
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR …

fix(Calendar, DatePicker): no click on disabled dates

---

packages/react-ui/components/DatePicker/DatePicker.tsx
packages/react-ui/components/DatePicker/MobilePicker.tsx
packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx

1. Вызов flushSync для Реакта 18 вызывает ошибки на в мобильном прежставлении ДатаПикера
2. onBlur вызывается до обновления value через onValueChange
Добавил костыль в виде `setTimeout` в обоих случаях.
По хорошему этот компонент надо переписать, т.к. flushSync тоже костыль.
`IF-2098`, `IF-2099`
⬜ нерелевантно
3. Добавлена (обновлена) документация
✅ нерелевантно
4. Изменения корректно типизированы
⬜ нерелевантно
5. Прочее
✅ все тесты и линтеры на CI …

DatePicker. Исправил flushSync и onBlur - ПР не надо сквошить, т.к. тут 2 фикса

---

packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/hide.png
packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/idle.png
packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/resize.png
packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/show.png
packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx
packages/react-ui/internal/HideBodyVerticalScroll/__creevey__/HideBodyVerticalScroll.creevey.ts
packages/react-ui/internal/HideBodyVerticalScroll/__stories__/HideBodyVerticalScroll.stories.tsx

Компонент `HideBodyVerticalScroll` может блокировать скролл при ресайзе.
Если кратко то проблема в обработчике события `resize`, который является методом одного из экземпляров `HideBodyVerticalScroll`. 
При размонтировании компонента из обработчиков "удаляется" метод другого экземпляра `HideBodyVerticalScroll`, из-за чего фактически обработчик остаётся.
Детально причины описаны тут https://github.com/skbkontur/retail-ui/pull/3121#discussion_r1135875204
Сделал обработчик статическим методом, чтобы все экземпляры ссылались на один.
⬜ нерелевантно
⬜ …

fix(HideBodyVerticalScroll): fix disorderly unmount and resize

---

packages/react-ui/.storybook/preview.tsx
packages/react-ui/.storybook/scripts/props2attrs.ts
packages/react-ui/.storybook/webpack.config.js

В нашем сторибуке для тестов используется пакет props2attrs. Он добавляет в html атрибуты `data-comp-name`, которые мы используем в скриншотных тестах.
Это фича замедляет работу сторибука и не нужна в новой доке, которая построена на нем же. Но полностью отключить пакет внутри preview.tsx не получается из-за его статического импорта там.
Вынести подключение и настройку props2attrs в отдельный entry в конфиге вебпака сторибука, который легко отключить для доки.
✅ нерелевантно …

chore: remove props2attrs from docs

---

packages/react-ui/internal/InternalMaskedInput/InternalMaskedInput.tsx

После перевода страницы, при фокусе на Инпут с маской, приложение падает с ошибкой.
Добавить спану, в котором лежат символы маски, атрибут `translate='no'`
Fix [IF-2120](https://yt.skbkontur.ru/issue/IF-2120)
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает суть …

fix(Input): crash on focus after page translation

---

packages/react-ui/components/Link/Link.styles.ts
packages/react-ui/components/Link/Link.tsx
packages/react-ui/components/Link/__stories__/Link.stories.tsx

При установке одинаковых цветов (обычное состояние, hover, active) для разных use у Link цвет иногда не применяется к Link. 
Выяснилось, что три заданных цвета попадают в миксин
```
export const linkUseColorsMixin = (mainColor: string, hoverColor: string, activeColor: string) => {
return `
color: ${mainColor};
&:hover {
color: ${hoverColor};
}
&:active {
color: ${activeColor};
}
`;
};
```
Он в свою очередь используется в стилях useDefault, useSuccess, useDanger, useGrayed
```
useDefault(t: Theme) {
return css`
${linkUseColorsMixin(t.linkColor, t.linkHoverColor, t.linkActiveColor)};
`;
},
useSuccess(t: Theme) {
return css`
${linkUseColorsMixin(t.linkSuccessColor, t.linkSuccessHoverColor, t.linkSuccessActiveColor)};
`;
},
useDanger(t: Theme) {
return css` …
```

fix(Link): same color styles for different use dont work

---

packages/react-ui-validations/docs/Common/Notification.tsx
packages/react-ui-validations/docs/index.tsx
packages/react-ui-validations/docs/styles/main.less
packages/react-ui/.styleguide/components/Notification/Notification.styles.ts
packages/react-ui/.styleguide/components/StyleGuideWrapper/StyleGuideWrapper.tsx

1. Починил z-index у баннера — календарь оказывался выше
2. В macOS и iOS срабатывает свайп вверх — отключил через `overscroll-behavior-y`
https://github.com/user-attachments/assets/1a29fd58-7102-4b25-ba78-9b6b9462ad2f
✅ нерелевантно
4. Добавлена (обновлена) документация
✅ нерелевантно
5. Изменения корректно типизированы
✅ нерелевантно
6. Прочее
✅ заголовок PR кратко и доступно отражает …

chore(docs): Fix banner z-index, disable top swipe in old docs

---

packages/react-ui/internal/themes/BasicLightTheme.ts

На некоторых мобильных устройствах некоторые контролы отображаются десктопными.
Конкретный [пример из старой доки](https://tech.skbkontur.ru/react-ui/#/Components/SidePage/SidePage): SidePage в неправильно открывается на некоторых телефонах. SidePage должен выглядеть как на первом скрине. На нескольких телефонах он так и выглядит, но на нескольких других — SidePage рендерится большим, будто на десктопе.
Взяли несколько телефонов андроид:
- Honor Magic 6, браузер chrome 131.0 -- всё правильно,
- Xiaomi 13T, браузер chrome 131.0 -- неправильная отрисовка
- Poco, браузер duckduckgo -- всё правильно
- Samsung Galaxy A71, встроенный самсунговский браузер -- неправильная отрисовка
Проверили, что флаг "Версия для ПК" везде выключен, масштаб экрана не влияет, отрисовка не зависит от браузера и …

fix(): desktop view on some mobiles

---

packages/react-ui/components/Calendar/__tests__/Calendar.test.tsx
packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx

В React 18 в dev режиме из-за `StrictMode` не рисуется `GlobalLoader`.
Очищать переменную `currentGlobalLoader` при размонтировании.
fix [IF-2126](https://yt.skbkontur.ru/issue/IF-2126)
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …

fix(GlobalLoader): render in StrictMode

---

packages/react-ui-validations/.storybook/Meta.tsx
packages/react-ui-validations/.storybook/preview-head.html
packages/react-ui-validations/.storybook/preview.tsx
packages/react-ui-validations/package.json
packages/react-ui/.storybook/Meta.tsx
packages/react-ui/.storybook/preview-head.html
packages/react-ui/.storybook/preview.tsx
packages/react-ui/package.json
yarn.lock

1. В новой доке кое-где был дефолтный сторибучный шрифт, который сложно переопределялся стилями
2. Код примеров сбрасывался при перерисовках страницы с докой, например после переключения контекстов  или ресайза до мобильного вида сторибука
1. Нашел достаточно надежный [способ](https://github.com/storybookjs/storybook/blob/c6b8ca7faec9d6b73f71c112100506ef41dde619/code/lib/blocks/src/components/DocsPage.tsx#L19) отключить дефолтные шрифты через обертку с классом `sb-unstyled`.
2. Добавил сохранение отредактированного кода примера в sessionStorge. Реализовано внутри аддона для живых примеров.
[Демо](https://ui.gitlab-pages.kontur.host/docs/storybook/react-ui/live-code-storage/?path=/docs/input-data-input--docs).
⬜ скриншоты для …

docs: fix font-family, add session storage for code examples

---

packages/react-ui/components/PasswordInput/PasswordInput.tsx
packages/react-ui/components/PasswordInput/__tests__/PasswordInput-test.tsx
packages/react-ui/internal/RenderLayer/__tests__/RenderLayer-test.tsx

В PasswordInput используется RenderLayer, который всегда active=true, это приводит к тому что события слушаются даже если компонент не в фокусе, условно даже если в другом компоненте на форме мы теряем фокус то тригернется и PasswordInput.
Замечено в ветке про shadow dom, там это поведение ломающее.
Починить использование active в RenderLayer, на фокус ставить его, на потерю снимать подписки.
Задача - https://yt.skbkontur.ru/issue/IF-2172
✅ нерелевантно
✅ …

fix(PasswordInput): add correct activation RenderLayer

---

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/components/DateInput/DateInput.tsx
packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
packages/react-ui/internal/InputLikeText/InputLikeText.tsx
packages/react-ui/internal/InputLikeText/__tests__/InputLikeText-test.tsx

1. Скринридер **не читает** значения`<DateInput>`
2. Нет поддержки **aria-атрибутов** в кастомном input — нет возможности добавлять инструкции для пользователей со скринридером. Например, они нужны для подписей в DateRangePicker.
Проблемы связаны с тем, что кастомный ипнут состоит из `<span tabindex="0" onKeyDown>` + `<input type="hidden">`.
Изменения затрагивают компонент `<DateInput>` и тесты `<Combobox>`, которые  используют `<InputLikeText>`.
`<ComboBox>` использует `<InputLikeText>` только для внешнего вида и получения фокуса.
После получения фокуса поле `<InputLikeText>` заменяется на обычный `<Input>` — проверки на это появились в тестах на focus/blur в PR #3133.
Ранее через `queryByRole('textbox').not.toBeInTheDocument()` мы проверяли отсутствие `<Input>`, но теперь …

feat(DateInput,DatePicker): add screenreader support to custom input

---

packages/react-ui-validations/.storybook/manager-head.html
packages/react-ui/.storybook/manager-head.html

Хоткеи DateInput конфликтуют с включенным сайдбаром Storybook — контрол теряет фокус при вводе '1'.
Проблема мешает показывать демки для пользователей библиотеки в песочнице.
Отключил хоткей для бокового меню Storybook через хак с CSS-свйоством visibility. Остальные [хоткеи](https://ui.gitlab-pages.kontur.host/storybook-documentation/?path=/settings/shortcuts) не стал выключать.
- [IF-2185](https://yt.skbkontur.ru/issue/IF-2185)
- [IF-2158](https://yt.skbkontur.ru/issue/IF-2158) — повесил TODO, что проблема исправится вместе с этой задачей
✅ нерелевантно
⬜ …

docs(): disable Storybook hotkey '1' conflicted with DateInput

---

packages/react-ui-validations/src/ValidationHelper.ts
packages/react-ui-validations/tests/ValidationWrapper.test.tsx

`ValidationWrapper` при изменении поля `level` в пропе `validationInfo` ничего не меняется.
Добавил поле `level` в функцию, которая сравнивает старый и новый проп `validationInfo`.
Добавил тестов для всех полей этого пропа.
`IF-2084`
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и …

fix(validations): updating field `level` in prop `validationInfo`

---

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
packages/react-ui/internal/Menu/Menu.tsx
packages/react-ui/internal/Menu/__tests__/Menu-test.tsx

Внутри `ComBoxMenu` в `Menu` прокидывались разные дататиды, но в `Menu` они фактически никак не использовались. Из-за этого не работали тесты для комбобокса из `SeleniumTesting`.
- Обернул `Menu` в `CommonWrapper`, добавил в тип `CommonProps`.
- Добавил тест.
fix [IF-2170](https://yt.skbkontur.ru/issue/IF-2170)
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ все тесты и …

fix(Combobox): use ComboBoxMenuDataTids in Menu

---

packages/react-ui/components/Dropdown/Dropdown.tsx
packages/react-ui/components/MenuItem/MenuItem.tsx
packages/react-ui/components/MenuItem/__tests__/MenuItem-test.tsx
packages/react-ui/components/PasswordInput/PasswordInput.tsx
packages/react-ui/components/PasswordInput/__tests__/PasswordInput-test.tsx

Из-за неправильного использования `CommonWrapper` для лечения ошибки типов в (https://github.com/skbkontur/retail-ui/pull/3400) стал перетираться  `InputDataTids.root` вместе с `PasswordInputDataTids.root`, хотя не должен.
Поправил использование `CommonWrapper`, ошибку типов полечил, прокинув `this.getProps()` вместо `this.props`.
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. …

fix(PasswordInput):  prevent Input root data-tid override

---

packages/react-ui/.creevey/images/MaskedInput/Change Theme/chrome2022.png
packages/react-ui/components/MaskedInput/ColorableInputElement/ColorableInputElement.tsx
packages/react-ui/components/MaskedInput/__stories__/MaskedInput.stories.tsx

При смене темы компонент не перекрашивает текст.
Причина в методе `paintText()` в компоненте `ColorableInputElement`. Этот метод обёрнут в `useCallback`, а значит необходимо указать зависимости, чтобы он обновлялся.
- Добавил зависимости в `useCallback`
- Добавил тест на смену темы
---
Изначально хотел использовать в тесте темы мажорных версий — `LIGHT_THEME_2022_0` и `DARK_THEME_2022_0`.
Идея была в том, что этот тест именно смены темы, поэтому нет смысла обновлять скриншот если обновиться тема.
Но потом подумал, что тогда при обновлении мажора придётся обновлять сам тест-кейс. Каждый раз..
И решил проще и лучше уж обновлять скриншот вместе с другими скриншотами, чем обновлять уникальный тест-кейс в каждом мажоре.
`IF-2193`
✅ …

fix(MaskedInput): fix change theme

---

packages/react-ui/components/Autocomplete/__docs__/Autocomplete.docs.stories.tsx
packages/react-ui/components/ComboBox/ComboBox.tsx
packages/react-ui/components/ComboBox/__docs__/ComboBox.docs.stories.tsx
packages/react-ui/components/Input/Input.tsx
packages/react-ui/components/Input/__docs__/Input.docs.stories.tsx

| Было | Стало |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/49f46666-da50-48a7-a14e-7308c7d60654" width="300"> | <img src="https://github.com/user-attachments/assets/4f521bfc-0cbd-4a1e-b228-b734c2d15d32" width="300"> | 
Прибрался в описаниях в props и в примерах:
- Input
- Combobox
- Autocomplete
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее …

docs(Input,Combobox,Autocomplete): update examples & props desc

---

packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
packages/react-ui/internal/Popup/Popup.tsx
packages/react-ui/lib/__tests__/mergeRefs-test.tsx
packages/react-ui/lib/mergeRefs.ts
packages/react-ui/lib/utils.ts

При рендере tooltip-a на странице, были случаи появления ошибки 'Anchor element is not defined or not instance of Element'. Частично эту ошибку заглушили в #3356, но не до конца. 
Изменена функция передачи ref ссылки в якорь, относительно которого рендерится tooltip со стрелочной, на обычную. Это позволило не вызывать лишний раз commitDetachRef в компонентах жизненного цикла, которые приводили к ошибке.
[IF-1145](https://yt.skbkontur.ru/issue/IF-1145) Popup: разобраться, откуда появляется варнинг  'Anchor element is not defined or not instance of Element'
⬜ нерелевантно
⬜ jsdoc для …

fix(Popup): fix error 'Anchor element is not defined' on render

---

packages/react-ui-testing/Tests/TestEnvironment/Browser.cs
packages/react-ui-testing/Tests/Tests.csproj

Осталось одно место использующее старый грид3
https://github.com/skbkontur/retail-ui/blob/40156951239bc7ae63033c09d03ad647c9e3df1f/packages/react-ui-testing/Tests/TestEnvironment/Browser.cs#L68
Добавил использование переменной окружения.
Для локальной работы подключается файл `.env`, но я не смог нормально проверить, т.к. локально проект у меня перестал тесты запускать. Почему-то не может достучаться до тестовых страниц, хотя они запущенны, и сам проект под админом открыт.
Думаю, пока можно оставить как есть.
✅ нерелевантно
⬜ комментарии для неочевидных …

 ci(react-ui-testing): use grid-4 url from env

---

packages/react-ui/.creevey/images/PasswordInput/Width/chrome2022.png
packages/react-ui/components/PasswordInput/PasswordInput.styles.ts
packages/react-ui/components/PasswordInput/__creevey__/PasswordInput.creevey.mts
packages/react-ui/components/PasswordInput/__stories__/PasswordInput.stories.tsx

В PasswordInput неправильно устанавливается ширина в процентах. 
Пример -- width=200% в PasswordInput и Input. Input -- для сравнения, как должно быть.
Добавила в стилях width=100% на рутовый div.
[IF-2181](https://yt.skbkontur.ru/issue/IF-2181)
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ заголовок PR …

fix(PasswordInput): width in percent

---

packages/react-ui-testing/TestPages/src/components/TestPages/InputTestPage.jsx
packages/react-ui-testing/Tests/TestEnvironment/Browser.cs
packages/react-ui-testing/Tests/Tests.csproj

1. В прошлый раз #3624 пропустил логин для подключения.
Почему-то подумал, что мы подключаемся к общему Гриду и теперь не надо указывать команду.
2. В последней версии драйвера (4.30.0) нет некоторых исключений, которые используется в тестах, в самом реакт-тестинг и в тестах валидаций.
3. Иногда падает тест `TestCheckValueIntoControlThatAppearsAfterTimeout`.
После двух кликов Инпут не успевает появиться раньше проверки его значения.
1. Добавил нашу команду для подключения к Гриду
2. Вернул старую версию драйвера.
Коды исключений надо либо заменить, либо отрефакторить логику. Подумал, что это может слишком затянуться и решил просто откатить драйвер.
3. Уменьшил таймаут появления Инпута с `2000мс` до `1500мс`.
Проверка значение происходит тоже через `2000мс` после клика. И т.к таймер в …

 ci(react-ui-testing): fix Selenium Grid 4 configuration issues

---

packages/react-ui/components/MenuItem/MenuItem.tsx
packages/react-ui/components/MenuItem/__tests__/MenuItem-test.tsx
packages/react-ui/internal/Menu/Menu.tsx

В версии 5.х в `Menu` по умолчанию работает подсветка пунктов меню, реализованная через контекст, и компонент явно не передаёт состояние подсветки в свои дочерние компоненты. А в `MenuItem` осталась старая логика получения состояния подсветки через проп `state`.
Передавать в контент функцию состояние `hover` через `this.activeState`, т.к. в старой системе  `Menu` передавало только его. Состояние же `selected` обычно передаётся явно компонентами более высокого уровня, использующими `Menu`, например `Select`.
fix [IF-2222](https://yt.skbkontur.ru/issue/IF-2222)
⬜ нерелевантно
⬜ jsdoc для …

fix(MenuItem): correctly pass state to functional children

---

packages/react-ui-testing/SeleniumTesting/Controls/Input.cs
packages/react-ui-testing/Tests/InputTests/InputTest.cs

Метод для вставки текста в инпут (ClearAndInputText) - вставляет текст слишком быстро. Это приводит к нестабильному падению тестов - иногда фронт не успевает обрабатывать ввод или обрабатывает их в неправильном порядке. 
Предоставить альтернативные методы, которые позволят избежать нестабильных падений:
1. `ClearAndInputTextWithDelays`. Метод с задержкой после каждого введенного символа (эмуляция скорости ввода, близкой к пользователю). 
2. `ClearAndEnsureInputText`. Метод с ожиданием успешного ввода после каждого введенного символа. 
Первый вариант более привычный для пользователей тестовых библиотек. Второй мне кажется более надежным. Когда я его применил к одному из нестабильных тестов в проекте, который падал 13/30 раз - он прошел 100 раз подряд.
2. …

feat(react-ui-testing): add methods for text input

---

.teamcity/settings.kts

Добавление конфиги прогонов на 16, 17, 18 react и strictMode=true в teamcity kotlin dsl
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
⬜ заголовок PR кратко и доступно отражает суть изменений (он …

ci: add react 16, 17, 18, strcit true for diff version test config

---

packages/react-ui/components/MiniModal/MiniModal.styles.ts
packages/react-ui/components/MiniModal/MiniModalFooter.tsx
packages/react-ui/components/MiniModal/MiniModalIndent.tsx

не работает flex gap в старых браузерах
убрать использование gap до лучших времен, оставить только margin
https://yt.skbkontur.ru/issue/IF-2192/MiniModal-ne-rabotaet-flex-gap-v-staryh-brauzerah
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает суть изменений (он попадет …

fix(MiniModal): prop 'gap' works in old browsers

---

.teamcity/settings.kts

Добавление subproject с env параметрами react/ts/stricMode для прогонов на разных версиях
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
⬜ заголовок PR кратко и доступно отражает суть изменений (он …

ci: add subproject to set env params in version testing config
