components/Logotype/Logotype.js, docs/src/snippets/Logotype-snip.js
Нужно для использования логотипа на не контрастном к черному цвету фона
=> [Logotype] Текст "контур" теперь можно писать любым цветом

components/ComboBox/ComboBox.js, components/ComboBox/ComboBoxRenderer.js, components/DropdownContainer/DropdownContainer.js
В ответ на issue [https://github.com/skbkontur/retail-ui/issues/15](https://github.com/skbkontur/retail-ui/issues/15)
=> [ComboBox] Added noUsePortal prop

package.json
=> switched to earlier react-input-mask version

.yarnrc, components/Toggle/Toggle.js, components/Toggle/Toggle.less, components/Toggle/index.js, docs/package.json, docs/src/components.js, docs/src/snippets/Toggle-snip.js, docs/yarn.lock, yarn.lock
[Some UI](https://ui.skbkontur.ru/Retail/%D0%95%D0%93%D0%90%D0%98%D0%A1/MARKET/Naklad/4.02%20%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%20%D1%81%D0%BE%20%D1%88%D1%82%D1%80%D0%B8%D1%85-%D0%BA%D0%BE%D0%B4%D0%BE%D0%BC.png.htm)
And there weren't any requirements. So, the first version is dead simple.
=> Компонент Toggle

components/DatePicker/DatePicker.js
Fix for the [issue #36](https://github.com/skbkontur/retail-ui/issues/36)
=> [DatePicker] add public focus method

components/Input/Input.js, components/Input/Input.less
https://github.com/skbkontur/retail-ui/issues/42
=> fix placeholder in IE

components/ComboBox/ComboBoxRenderer.js, components/Textarea/Textarea.less
fixes textarea placeholder color in #42
=> flowtype fix and textarea placeholder color in ie

components/Loader/Loader.js
Очень часто требуется возможность добавить стили на обёртку лоадера. Самый частый кейс - растянуть лоадер на высоту 100%. Решили добавить :)
=> Добавили возможность стилизовать обёртку лоадера

components/Button/Button.js, components/Button/Button.less, components/Checkbox/Checkbox.js, components/Checkbox/Checkbox.less, components/Link/Link.js
[Button] prevent focus on click,
[Link] prevent focus on click
[Checkbox] prevent focus on click
+ чекбоксы по гайдам
=> Стили для кнопки (анимация загрузки) и чекбоксов (при наведении и нажатии) 

components/FxInput/FxInput.adapter.js
Добавил функции в адаптер FxInput для получения props.auto и выполнения onRestore
=> getAutoFlag and restore

components/RenderContainer/RenderContainer.js
Ещё убрал комментарий, ибо там null возвращать не будем
=> [RenderContainer] add testID to domContainer for test purposes

components/MenuItem/MenuItem.js
=> [MenuItem] render span if disabled

components/RadioGroup/RadioGroup.js
=> [RadioGroup] Визуальный фикс фокуса (issue #159)

components/Logotype/Logotype.js
как то так, на то что суффикс состоит из пробелов решил не проверять
=> при отсутствии суффикса - не рисуем точку в логотипе

components/Dropdown/Dropdown.js
Добавлен аттрибут "disabled" в компонент "Dropdown".
=> [Dropdown] Add "disabled" attribute (issue #173)

components/Checkbox/Checkbox.less
ie9 не поддерживает linear-gradient
=> [Checkbox] Background for ie9

components/Button/Button.js
=> Added width support for link-buttons

components/Menu/Menu.js, components/Select/Item.js, components/Select/Select.adapter.js, components/Select/Select.js
=> Select close

components/Dropdown/Dropdown.js
=> Added close method to dropdown

components/Select/Select.d.ts
двойное объявление static - не порядок - убрал
=> Починил dts для Select

components/ComboBoxOld/ComboBoxRenderer.js, components/CustomComboBox/ComboBoxView.js, components/DatePicker/DatePicker.js, components/Select/Select.js, components/Tooltip/Tooltip.js, components/internal/withFocusOutside.js
Временная заплатка на задачу https://github.com/skbkontur/retail-ui/issues/266 для comboBoxOld и tooltip.
=> [RenderLayer] Каждый инстанс подписывает свой обработчик на событие `mousedown`

components/Select/Select.d.ts, components/Select/Select.js, components/Select/__tests__/Select-test.js
=> [Select] changed default value for areValuesEqual property

components/Modal/Modal.adapter.js, components/Modal/Modal.d.ts, components/Modal/Modal.js, components/Modal/Modal.less, components/Modal/__tests__/Modal.stories.js, components/Modal/index.d.ts, package.json, yarn.lock
=> [Modal] disableClose prop

components/Kebab/Kebab.d.ts, components/Kebab/Kebab.js, components/Kebab/Kebab.less
- нельзя получить фокус
- отключается клик
- отключается hover
=> добавил поддержку disabled в кебаб

components/Modal/Modal.js, components/Popup/PopupPin.js
При открытом состоянии Popup'a, пин наезжает на большую часть кебаба:
Из-за этого, при клике на эту область, всплываха не закрывается.
=> PopupPin fix

components/Textarea/Textarea.js
=> add resize style to Textarea component

components/ComboBoxOld/__tests__/Combobox.stories.js, components/DropdownContainer/DropdownContainer.js
=> Fixed menu when opened to top

components/DatePicker/DatePicker.js, components/DatePicker/Picker.less, components/DropdownContainer/DropdownContainer.js
У календаря Datepcker'a неверно расчитываются координаты, если у body или html позиционирование отлично от static.
Модифицировали расчет координат для компонента DropdownContainer, добавив определение позиционирования элементов html и body .
=> Fixed Datepicker's position calculation

components/Textarea/Textarea.js, components/Textarea/Textarea.less, components/Textarea/__tests__/textarea.stories.js
Научила изменять размер под содержимое
=> add autoResize and id props

components/DatePicker/DatePicker.js, components/RenderContainer/RenderContainer.js
Fix for multiple different react-ui instances in one page.
Please, check IE8 backward compatibility because I can't.
=> Fix calculation of lastID in RenderContainer 

components/Tabs/Tab.js, components/Tabs/Tab.less, components/Tabs/__tests__/Tabs.stories.js
Добавил свойство по аналогии. Мог где-то что-то пропустить, поэтому, пожалуйста, проверьте тщательнее.
=> Prop for disable tab

components/Radio/Radio.d.ts, components/Radio/Radio.js, components/Radio/index.d.ts, components/RadioGroup/RadioGroup.d.ts, components/RadioGroup/RadioGroup.js, components/RadioGroup/RadioGroup.js.flow, components/RadioGroup/__tests__/RadioGroup.definition.tsx, components/RadioGroup/__tests__/RadioGroup.test.js, components/RadioGroup/index.ts, docs/package.json, docs/webpack.config.js, docs/yarn.lock
added TS definitions
added Flow definitions
improved docs
=> [RadioGroup] accepts any object as value

components/Autocomplete/Autocomplete.d.ts, components/Autocomplete/index.d.ts, components/Input/Input.d.ts
Help with typescript definitions:
* Update Input definitions;
* Add Autocomplete definitions;
=> Typescript definitions help

components/Autocomplete/Autocomplete.d.ts, components/Autocomplete/index.d.ts, components/ComboBox/ComboBox.d.ts, components/Input/Input.d.ts, components/Radio/Radio.d.ts, components/Sticky/Sticky.d.ts, components/Sticky/index.d.ts
* Add definitionts for Sticky
* Remove `| undefined`
=> More help with typescript definitions

components/Toast/Toast.d.ts
=> [Toast] Types fix

components/Tooltip/Tooltip.d.ts
Сделал пропсы pos и trigger необязательными
=> Fix for #369

components/ComboBox/ComboBox.js
=> Correct Typo

components/Select/Select.less, components/variables.less
Добавил цвет иконки у выпадашки в переменную, чтобы её можно было переопределить.
=> variables for icon color in component select

components/Select/Select.js, components/Select/Select.less
выпилил неиспользуемые методы и стили, немного подрефачил, концептуально ничего не менял
=> подчистил Select

components/ScrollContainer/ScrollContainer.less, components/SidePage/SidePage.d.ts, components/SidePage/SidePage.js, components/SidePage/SidePage.less, components/SidePage/__tests__/SidePage.stories.js, components/SidePage/index.d.ts, components/SidePage/index.js
Добавил контролл [Сайдпейджа](https://guides.kontur.ru/components/sidepage/)
Пока простая версия:
- нет анимации
- есть некоторые кривости, когда открыты несколько сайдпейджей с разными параметрами
Реализовано:
- залипающие Header и Footer
- Наложение нескольких сайдпейджей друг на друга
Сделано по аналогии с Modal
=> Append SidePage

components/Select/Select.less
В пылу разработки прошлые изменения были затерты, прошу вернуть.
=> again: variables for icon color in component select

components/Select/Select.js, components/Select/__tests__/Select.stories.js
=> [Select] Возможность переопределять отображаемое значение для null #397

components/Tabs/Tabs.js
Fix onChange firing on active Tab
=> [Tabs] Fix onChange

components/CurrencyInput/CurrencyHelper.js, components/CurrencyInput/CurrencyInput.d.ts, components/CurrencyInput/CurrencyInput.js, components/CurrencyInput/CurrencyInputHelper.js, components/CurrencyInput/__tests__/CurrencyHelper-test.js, components/CurrencyInput/__tests__/CurrencyInput.stories.js
fixes #394
fixes #395
fixes #403
fixes #404
=> Currency input fixes

components/CurrencyInput/CurrencyInput.js
=> [CurrencyInput] починил отображение начального значения

components/Kebab/Kebab.js, components/Popup/Popup.js, components/Popup/__tests__/Popup.stories.js
1. Поправил позиционирование для маленьких элементов
2. Добавил пересчет позиции на события браузера
=> Доработки компонента Popup

components/Button/Button.less, components/Button/Button.styles.js
Аналогично #402 , в кнопке для медиума шрифт должен быть 16px.
=> добавил font size 16px для medium size в стили Button

.storybook/config.js, ROADMAP.md, components/Button/Button.js, components/Checkbox/Checkbox.js, components/Input/Input.js, components/Radio/Radio.js, components/internal/InputLikeText/InputLikeText.js
Keeping high standarts in english grammar
=> Oxford graduate 🎓 grammar fixes

components/IgnoreLayerClick/IgnoreLayerClick.d.ts, components/IgnoreLayerClick/IgnoreLayerClick.js, components/IgnoreLayerClick/__tests__/IgnoreLayerClick.stories.js, components/IgnoreLayerClick/index.d.ts, components/IgnoreLayerClick/index.js, components/SidePage/SidePage.js
Сделал компонент, клик по которой игнорит клик RenderLayer-а
Поправил width в сайдпейдже
=> Сделал компонент, клик по которой игнорит клик RenderLayer-а

components/HideBodyVerticalScroll/HideBodyVerticalScroll.js
Все стили теперь добавляются в stylesheet, и не затрагивают инлайн стили
=> [HideBodyVerticalScroll] Dynamic css

components/Select/Select.js
=> [Select] props.onChange не поджигается при выборе старого значения

components/ComboBox/ComboBox.js, components/CustomComboBox/ComboBoxView.js, components/CustomComboBox/CustomComboBox.js
Такой уже есть в ComboBoxOld, пробросил его и в новый.
Описание и причины появления этого пропса можно почитать здесь https://github.com/skbkontur/retail-ui/issues/15.
=> [Combobox] added prop 'disablePortal'

components/ScrollContainer/ScrollContainer.js
В переменной inner может лежать null, что приводит к ошибке
=> Добавить проверку на null в компоненте ScrollContainer

components/Button/Button.less
Кнопка в режиме ссылки отображалась неправильно. Исправил следующие проблемы:
1. Высота перекрывалась стилем из sizeSmall, которая устанавливала ее в 32px, что для ссылки не правильно. 
2. На hover не появлялось нижнее подчеркивание текста ссылки.
=> [Button] fixed styles in the case of using 'use="link"'

components/Popup/Popup.js, components/ZIndex/ZIndex.js, components/ZIndex/__tests__/ZIndex.stories.js
Reverts skbkontur/retail-ui#453
=> Revert "Когда рендерим Popup в пререндере не создаем ZIndex"

package.json, tsconfig.json, yarn.lock
Right way to start using TS helpers 🤷‍♂️ 
See [this link](https://github.com/Microsoft/tslib) for reference
=> Add tslib for better TS bundle experience 

components/internal/InputLikeText/InputLikeText.js
See https://github.com/skbkontur/retail-ui/issues/475
=> [Combobox] fixed handling focus in InputLikeText for firefox esr 52.7.2

components/SidePage/SidePage.js, components/SidePage/__tests__/SidePage.stories.js
SidePage.Header и SidePage.Footer  позволяют рендерить в себе контен в зависимости от того в sticky моде они сейчас или нет
=> SidePage.Header и SidePage.Footer sticky mode

components/Button/__tests__/Button.stories.js, components/Checkbox/Checkbox.js, components/Link/__tests__/Link.stories.js
У нас не проходят тесты из-за этого, Checkbox кидает warning.
=> Rename some icon names 'ok' -> 'Ok'

components/Checkbox/Checkbox.flat.less, components/Checkbox/Checkbox.less, components/Radio/Radio.less
Исправлены стили радио и компонента чекбокс.
Проблема 1:
У компонента радио нет стиля cursor: pointer несмотря на то что компонент кликабельный
Проблема 2:
Нужно поменять размер шрифта для подписи чекбокса.
=> fix-radio-and-checkbox-cosmetic 

components/Modal/Modal.tsx, components/Modal/ModalBody.tsx, components/Modal/ModalClose.tsx, components/Modal/ModalContext.tsx, components/Modal/ModalFooter.tsx, components/Modal/ModalHeader.tsx
Fixes documentation issues with Modal
=> [Modal] splitted components

components/DatePickerOld/DatePickerOld.js, components/DateSelect/DateSelect.js, components/FxInput/FxInput.js, components/Group/README.md, components/Input/README.md, components/Input/__tests__/Input.stories.js, components/Kebab/Kebab.js, components/Paging/Paging.js, components/PasswordInput/PasswordInput.js, components/TopBar/Organizations.js, components/TopBar/README.md, components/TopBar/TopBar.js, docs/src/components/DemoPage.js, docs/src/snippets/Group-snip.js, docs/src/snippets/Input-snip.js, docs/src/snippets/TopBar-snip.js
Когда сейчас используешь компоненты сыпятся ворнинги на устаревшие иконки, хотя сам ты их не используешь.
=> Обновление устаревших иконок используемых внутри библиотеки.

components/Textarea/Textarea.less
To fix overflow on small screen sizes
=> Update fake textarea styles

components/Button/Button.less, components/Button/Button.tsx
Добавил кнопке отображение стрелкой влево, если ей передать в пропсах arrow='back'
=> [Button] added arrow back view

components/DatePickerOld/DatePickerOld.js
Предлагаю бэк-портировать этот фикс на v0.16.5
=> fixing handling of blur in handlePick

package.json, packages/retail-ui/package.json, yarn.lock
`husky` переехал в корень, все хуки из корневого package.json вызывают соответствующие хуки в пакетах, почищены зависимости
=> Поднастроены зависимости

packages/retail-ui/components/CurrencyInput/CurrencyInput.tsx, packages/retail-ui/components/CurrencyInput/CurrencyInputKeyboardActions.tsx, packages/retail-ui/components/CurrencyInput/SelectionHelper.tsx
теперь работает ввод на Android и под Selenium, в том числе с учетом выделения
сатья про работу с вводом https://learn.javascript.ru/keyboard-events
на андроиде не прилетает keypress, в keydown для букв и цифр не прилетает key, а keyCode=229
возможно, решение не самое лучшее, но рабочее
=> fix(сurrency-input): починка ввода циферок на андроиде и под selenium

packages/retail-ui/testing/Lookup.js
Propagate `tid` prop down to the children until component with adapter.
`search` now find all ids including children with `tid`.
`getAdapter` now accept array of elements and merge adapters.
=> fix(lookup): allow correctly work with recompose

packages/retail-ui/components/Input/Input.flat.less
=> fix(input): fixed placeholder polyfill in flat

packages/retail-ui/components/Input/Input.flat.less
=> fix(combobox): no focus on placeholder click if flat

packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx
=> fix(combobox): call onBlur if menu is opened

packages/retail-ui/components/Modal/Modal.less, packages/retail-ui/components/Modal/Modal.tsx, packages/retail-ui/components/Modal/__stories__/Modal.stories.tsx, packages/retail-ui/lib/Upgrades.tsx
при включенном флаге Upgrades.adaptiveStyles = true, при ширине меньше 425px, у модалки убираются внешние падинги.
=> feat(modal): адаптивная модалка

packages/retail-ui/components/internal/InternalMenu/InternalMenu.tsx
=> #607 add null type guard

.travis.yml, packages/react-ui-screenshot-tests/gemini/screens/Tooltip left/plain/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip right/plain/firefox.png, packages/retail-ui/components/Popup/Popup.less, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/SidePage/SidePage.tsx, packages/retail-ui/components/Toast/Toast.less, packages/retail-ui/components/Toast/Toast.tsx, packages/retail-ui/package.json, yarn.lock
react-addons-css-transition-group устарел и теперь заменен на react-transition-group
=> Removed react-addons-css-transition-group

packages/retail-ui/components/DateSelect/DateSelect.tsx
-закрытие по esc
-бесконечная промотка при длинном нажатии
-при одном клике смещается на 3 позиции
=> fix(datepicker): correct keyboard and mouse events in date select

packages/retail-ui/components/Calendar/CalendarUtils.tsx
Reverts skbkontur/retail-ui#616
=> Revert "fix(Calendar): пофикшен скролл к максимальному месяцу"

packages/react-ui-screenshot-tests/gemini/utils.js
fixes failing screenshot tests
=> refactor: changed host-url

packages/retail-ui/components/Logotype/Logotype.less
=> fix(logotype): fixed widget button in safari

packages/retail-ui/components/Popup/PopupPin.less
```css
pointer-events: none;
```
у стрелочки в попапе
=> fix(Hint): fix #624

packages/retail-ui/components/CurrencyInput/CurrencyInput.tsx, packages/retail-ui/components/FxInput/FxInput.tsx, packages/retail-ui/components/FxInput/__stories__/FxInput.stories.tsx, packages/retail-ui/components/FxInput/__tests__/FxInput-test.tsx
=> Fx input inner ref

packages/retail-ui/components/Dropdown/Dropdown.tsx, packages/retail-ui/components/Dropdown/__tests__/Dropdown-test.tsx
=> fix(Dropdown): починен интерфейс пропсов

packages/retail-ui/components/Modal/Modal.less, packages/retail-ui/components/Modal/Modal.tsx, packages/retail-ui/components/Modal/ModalClose.tsx, packages/retail-ui/components/Modal/ModalHeader.tsx, packages/retail-ui/package.json, yarn.lock
- Фокус по табу не выходит за пределы модалки
- После закрытия модалки фокус возвращается на первоначальный элемент
- Кнопка закрытия модалки имеет обводку во время фокуса
=> feat(Modal): фокус внутри модалки

packages/retail-ui/components/all.ts
=> fix(tabs): added default export

packages/react-ui-integration-tests/tests/tokens.js, packages/react-ui-screenshot-tests/gemini/screens/Tokens/clicked/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/clicked/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/clicked/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/idle/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/idle/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/idle/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/withMenu/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/withMenu/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/withMenu/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/withText/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/withText/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tokens/withText/ie11.png, packages/react-ui-screenshot-tests/gemini/tokens.js, packages/retail-ui/components/Menu/Menu.tsx, packages/retail-ui/components/Spinner/__stories__/Spinner.stories.tsx, packages/retail-ui/components/Tokens/DeleteIcon.tsx, packages/retail-ui/components/Tokens/RemoveIcon.tsx, packages/retail-ui/components/Tokens/TextWidthHelper.tsx, packages/retail-ui/components/Tokens/Tokens.less, packages/retail-ui/components/Tokens/Tokens.tsx, packages/retail-ui/components/Tokens/TokensMenu.tsx, packages/retail-ui/components/Tokens/TokensReducer.tsx, packages/retail-ui/components/Tokens/TokensTokens.tsx, packages/retail-ui/components/Tokens/__stories__/Tokens.stories.tsx, packages/retail-ui/components/Tokens/__tests__/Tokens.test.tsx, packages/retail-ui/components/variables.less
Базовая реализация компонента "Поле с токенами"
=> WIP #650 tokens

packages/retail-ui/components/Input/Input.flat.less, packages/retail-ui/components/internal/InputLikeText/InputLikeText.tsx
=> fix(Combobox): disabled в плоской теме вновь работает

packages/retail-ui/components/Hint/Hint.tsx
=> fix(Hint): позиционирование с блочным элементом

packages/retail-ui/components/Calendar/DayCellView.less, packages/retail-ui/components/Calendar/MonthView.less, packages/retail-ui/components/DateInput/DateInput.less, packages/retail-ui/components/DatePicker/DatePicker.less, packages/retail-ui/components/DatePicker/Picker.less, packages/retail-ui/components/Input/Input.flat.less, packages/retail-ui/components/MenuSeparator/MenuSeparator.less, packages/retail-ui/components/Paging/Paging.less, packages/retail-ui/components/Paging/Paging.tsx, packages/retail-ui/components/SidePage/SidePage.less, packages/retail-ui/components/Textarea/Textarea.flat.less, packages/retail-ui/components/variables.flat.less, packages/retail-ui/components/variables.less
Moved css props from components styles files to variables.less
=> refactor(retail-ui): moved styles props

packages/retail-ui/components/Modal/Modal.less, packages/retail-ui/components/Modal/Modal.tsx
=> Modal width fix

packages/react-ui-screenshot-tests/gemini/button.js, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/clicked/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/clicked/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/clicked/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/clickedOutside/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/clickedOutside/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/clickedOutside/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/hover/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/hover/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/hover/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/idle/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/idle/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/idle/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/mouseLeave/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/mouseLeave/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/mouseLeave/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/pressed/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/pressed/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/pressed/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/tabPress/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/tabPress/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/button use link with error/tabPress/ie11.png, packages/retail-ui/components/Button/Button.flat.less, packages/retail-ui/components/Button/Button.less, packages/retail-ui/components/Button/Button.tsx, packages/retail-ui/components/Button/__stories__/Button.stories.tsx, packages/retail-ui/components/variables.less
=> Button use="link" error

packages/retail-ui/components/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx
=> fix(HBVS): восстановление скролла контейнера при unmount

packages/retail-ui/styleguide.config.js
- better version display format
- link to github repo
=> docs: styleguide improvements

packages/retail-ui/components/Button/Button.flat.less, packages/retail-ui/components/Button/Button.less, packages/retail-ui/components/Button/Button.tsx
=> fix(Button): removed z-index

packages/retail-ui/components/Calendar/__tests__/CalendarDateShape.test.tsx, packages/retail-ui/components/CurrencyInput/CurrencyHelper.tsx, packages/retail-ui/components/CurrencyInput/__tests__/CurrencyHelper-test.tsx, packages/retail-ui/components/CurrencyInput/__tests__/CursorHelper-test.tsx, packages/retail-ui/components/DateSelect/__tests__/DateSelect-test.tsx, packages/retail-ui/components/Dropdown/__tests__/Dropdown-test.tsx, packages/retail-ui/components/FxInput/__tests__/FxInput-test.tsx, packages/retail-ui/components/Menu/__tests__/Menu-test.tsx, packages/retail-ui/components/MenuItem/__tests__/MenuItem-test.tsx, packages/retail-ui/components/Paging/__tests__/PagingHelper-test.tsx, packages/retail-ui/components/PasswordInput/__tests__/PasswordInput-test.tsx, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/RadioGroup/__tests__/RadioGroup.test.tsx
Поправил типы в тестах, чтобы проходил `yarn tsc`
=> test: fixed ts types

packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/reducer/default.tsx, packages/retail-ui/components/DateInput/__tests__/DateInput-test.tsx, packages/retail-ui/components/Input/Input.less
=> Fix issue 608

packages/retail-ui/components/Toggle/Toggle.tsx, packages/retail-ui/components/Toggle/__stories__/Toggle.stories.tsx
- Теперь работает как обычный controlled/uncontrolled компонент:
если передан `checked`, компонент полностью контролируется снаружи.
В противном случае будет использоваться только внутренний стэйт. Для uncontrolled-режима
можно передать `defaultChecked`
- Close #699
=> fix(Toggle): controlled/uncontrolled

packages/react-ui-screenshot-tests/gemini/hint.js, packages/react-ui-screenshot-tests/gemini/screens/Hint with block caption/mouseOver/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Hint with block caption/mouseOver/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Hint with block caption/mouseOver/ie11.png, packages/retail-ui/components/Hint/Hint.tsx, packages/retail-ui/components/Hint/HintBox.less, packages/retail-ui/components/Hint/__stories__/Hint.stories.tsx, packages/retail-ui/components/Hint/__tests__/Hint-test.tsx
- `render` возвращает `react-элемент`, а не массив для совместимости
с `react 15`
- Fixed #716
=> fix(Hint): render method

packages/react-ui-screenshot-tests/gemini/Textarea.js, packages/react-ui-screenshot-tests/gemini/screens/Textarea with custom width/Textarea with custom width/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Textarea with custom width/Textarea with custom width/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Textarea with custom width/Textarea with custom width/ie11.png, packages/retail-ui/components/Textarea/Textarea.less, packages/retail-ui/components/Textarea/Textarea.tsx, packages/retail-ui/components/Textarea/__stories__/textarea.stories.tsx
=> Fix textarea width

packages/retail-ui/components/Input/Input.flat.less
- Добавлен стиль для кастомного плэйсхолдера при наличии иконки слева (ie)
- Fixed #731
=> fix(Input): fix flat styles

packages/retail-ui/components/Button/Button.flat.less
=> fix(Button): fix type link in flat mode

packages/retail-ui/components/Group/__stories__/Group.stories.tsx, packages/retail-ui/components/Group/__tests__/Group-test.tsx, packages/retail-ui/components/Input/Input.less, packages/retail-ui/components/Input/Input.tsx
Закрывает https://github.com/skbkontur/retail-ui/issues/766
=> feat(Group): added stories and tests

packages/react-ui-testing/SeleniumTesting/SeleniumTesting/ControlBase.cs, packages/react-ui-testing/SeleniumTesting/TestPages/react-selenium-testing-custom-props.js, packages/react-ui-testing/SeleniumTesting/TestPages/src/components/TestPages/ButtonTestPage.jsx, packages/react-ui-testing/SeleniumTesting/Tests/ButtonTests/ButtonTest.cs, packages/react-ui-testing/SeleniumTesting/Tests/ButtonTests/ButtonTestPage.cs
Пока написал тест только на кнопку, если всё ок — допишу ещё
=> WIP: react-ui-testing. Check warning prop

packages/react-ui-screenshot-tests/gemini/datepicker.js, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/DateSelect month/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/DateSelect month/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/DateSelect year/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/DateSelect year/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/opened/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/opened/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/DatePicker/opened/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/DateSelect in DatePicker/DateSelect month/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/DateSelect in DatePicker/DateSelect month/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/DateSelect in DatePicker/DateSelect year/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/DateSelect in DatePicker/DateSelect year/ie11.png, packages/retail-ui/components/Calendar/Calendar.less, packages/retail-ui/components/Calendar/DayCellView.less, packages/retail-ui/components/DateSelect/DateSelect.less, packages/retail-ui/components/variables.less
**[DateSelect] добавлены переменные**
- @date-select-menu-bg
- @date-select-menu-item-bg-active
- @date-select-menu-item-bg-selected
- @date-select-menu-item-bg-disabled
- @date-select-menu-item-font-active
- @date-select-menu-item-font-selected
- @date-select-menu-item-font-disabled
**[Calendar] добавлены переменные**
- @calendar-cell-selected-font-color
Closed #755
=> feat(Calendar): больше переменных в стилях

packages/retail-ui/components/Input/Input.tsx
`selectAllOnFocus` добавлен в список пропсов в `styleguidist`
=> docs(Input): selectAllOnFocus prop add to doc

packages/react-ui-screenshot-tests/gemini/screens/modal with variable height of content/toggle content height/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/modal with variable height of content/toggle content height/ie11.png, packages/retail-ui/components/Modal/Modal.less, packages/retail-ui/components/Modal/Modal.tsx
=> fix(Modal): fix modalClickTrap height

packages/retail-ui/components/Button/Button.flat.less, packages/retail-ui/components/Button/Button.less
кажется, это решит баг с белой полосой в кнопках
=> fix(Button): fix subpixel bug in chrome

packages/retail-ui/components/FxInput/FxInput.tsx
=> fix(FxInput): fix warning from 'mainInGroup' prop

packages/retail-ui/components/Input/Input.tsx, packages/retail-ui/components/Input/__tests__/Input-test.tsx
=> fix(Input): filter props for HTMLInputElement, fix #831

packages/retail-ui/components/Input/Input.tsx
=> fix(Input): update typings

packages/retail-ui/components/CustomComboBox/ComboBoxView.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx
=> feat(CustomComboBox): добавил ref для InputLikeText

packages/retail-ui/components/Loader/Loader.less
#787
Hotfix for `Loader` z-index level
=> Loader zindex fix

packages/retail-ui/components/Link/Link.tsx
=> fix(Link): fix types, fix #841

packages/retail-ui/components/Tooltip/Tooltip.tsx, packages/retail-ui/components/Tooltip/__stories__/Tooltip.stories.tsx
=> feat[Tooltip]: Сделать проп для закрытия тултипа, даже если курсор над ним

.travis.yml, packages/retail-ui/.eslintignore, packages/retail-ui/components/ComboBoxOld/ComboBoxOld.adapter.js, packages/retail-ui/components/ComboBoxOld/ComboBoxOld.js, packages/retail-ui/components/ComboBoxOld/ComboBoxRenderer.js, packages/retail-ui/components/DatePickerOld/Calendar.js, packages/retail-ui/components/DatePickerOld/DateInput.js, packages/retail-ui/components/DatePickerOld/DatePicker.adapter.js, packages/retail-ui/components/DatePickerOld/DatePickerOld.js, packages/retail-ui/components/DatePickerOld/Picker.js, packages/retail-ui/components/DatePickerOld/__stories__/DatePicker.stories.js, packages/retail-ui/components/DatePickerOld/dateParser.js, packages/retail-ui/components/IgnoreLayerClick/__stories__/IgnoreLayerClick.stories.tsx, packages/retail-ui/components/Kladr/AddressModal.js, packages/retail-ui/components/Kladr/KladrAPI.js, packages/retail-ui/components/Kladr/Types.js, packages/retail-ui/components/Kladr/util.js, packages/retail-ui/package.json, yarn.lock
Меня задолбало, что оно разваливается на какой-нибудь левой dts'ке от less файла после чекаута и нет возможности закоммитить свои изменения.
=> Lint in travis

packages/retail-ui/components/Modal/Modal.less
=> Modal adaptivity

packages/retail-ui/components/Button/README.md, packages/retail-ui/components/DropdownMenu/README.md, packages/retail-ui/components/Group/README.md, packages/retail-ui/components/Group/__stories__/Group.stories.tsx, packages/retail-ui/components/Icon/Icon.tsx, packages/retail-ui/components/Input/README.md, packages/retail-ui/components/Kebab/README.md, packages/retail-ui/components/Tooltip/README.md, packages/retail-ui/components/TooltipMenu/README.md, packages/retail-ui/components/TopBar/README.md, packages/ui-kit/src/components/DropdownMenu/README.md
Обновил ридми с иконками и забыл влить :)
=> chore(Icon): update components readme

packages/retail-ui/components/DropdownMenu/DropdownMenu.tsx, packages/retail-ui/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx, packages/retail-ui/components/Hint/Hint.tsx, packages/retail-ui/components/Hint/__stories__/Hint.stories.tsx, packages/retail-ui/components/Kebab/Kebab.tsx, packages/retail-ui/components/Kebab/__stories__/Kebab.stories.tsx, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/TooltipMenu/TooltipMenu.tsx, packages/retail-ui/components/TooltipMenu/__stories__/TooltipMenu.stories.tsx, packages/retail-ui/components/internal/PopupMenu/PopupMenu.tsx
Починен проп `disableAnimation` в `Popup`е.
Добавлена возможность не показывать анимацию у компонентов:
- Dropdown
- Kebab
- TooltipMenu
- Hint
Close #832 #863
=> [Popup]: Disable animations

package.json, yarn.lock
Run `yarn commit` use commit message wizard
=> chore: add commitizen and conventional changelog

packages/retail-ui/lib/listenFocusOutside.tsx
=> fix(Tooltip): click on svg in tooltip #877

packages/retail-ui/components/FxInput/FxInput.tsx, packages/retail-ui/components/Group/Group.tsx, packages/retail-ui/components/Input/Input.tsx
Проп `mainInGroup` снова работает. Убраны `deprecationWarning`, актуализирована документация.
=> fix(FxInput): mainInGroup works again

packages/retail-ui/components/FxInput/FxInput.tsx, packages/retail-ui/components/FxInput/__tests__/FxInput-test.tsx
=> feat(FxInput): add public method blur

packages/retail-ui/components/ComboBox/ComboBox.tsx, packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/retail-ui/components/CustomComboBox/ComboBoxView.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx
Состояние MenuItem (hover, active) передается в `renderItem` вторым аргументом
=> feat(ComoboBox): pass state of menu item to renderItem second arg

packages/react-ui-screenshot-tests/gemini/button.js, packages/react-ui-screenshot-tests/gemini/screens/Button arrows/plain/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Button arrows/plain/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Button arrows/plain/ie11.png, packages/retail-ui/components/Button/Button.less, packages/retail-ui/components/Button/Button.tsx, packages/retail-ui/components/Button/README.md, packages/retail-ui/components/Button/__stories__/Button.stories.tsx, packages/retail-ui/components/variables.less
Новые клевые стили от @laion220995 (оригинальный pr #821)
Close #150
=> feat[Button]: Новые стили для кнопок-стрелок

packages/retail-ui/components/Tooltip/Tooltip.tsx
=> fix(Tooltip): add shallow equal on shouldComponentUpdate

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/reducer/autocomplete.tsx
=> fix(ComboBox): show editing input text on focus instead of value (autocomplete mode)

packages/retail-ui/components/Calendar/Calendar.tsx, packages/retail-ui/components/Calendar/Month.tsx, packages/retail-ui/components/Calendar/__stories__/Calendar.stories.tsx, packages/retail-ui/components/DatePicker/DatePicker.tsx, packages/retail-ui/components/DatePicker/Picker.tsx, packages/retail-ui/components/DatePicker/README.md
Праздничные дни передаются в компонент массивом строк dd.mm.yyyy
и помечаются красным как выходные.
Close #423
=> feat(DatePicker): поддержка праздничных дней

packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/reducer/default.tsx, packages/retail-ui/test-setup.js
- Починено открытие комбобокса после потери фокуса инпутом, fix #897
- Попутно починился мигающий тест, fix #916
=> fix(ComboBox): prevent request after blur

packages/react-ui-screenshot-tests/gemini/hint.js, packages/react-ui-screenshot-tests/gemini/popup.js, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/hover/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/hover/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Popup wrap inline-block/hover/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Popup wrap inline-block/hover/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Popup wrap inline-block/hover/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip wrap inline-block/hover/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip wrap inline-block/hover/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip wrap inline-block/hover/ie11.png, packages/react-ui-screenshot-tests/gemini/tooltip.js, packages/retail-ui/components/Hint/Hint.tsx, packages/retail-ui/components/Hint/__stories__/Hint.stories.tsx, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/Popup/__stories__/Popup.stories.tsx, packages/retail-ui/components/Popup/index.tsx, packages/retail-ui/components/Tooltip/Tooltip.tsx, packages/retail-ui/components/Tooltip/__stories__/Tooltip.stories.tsx
Fix #721
Будет чуть позже
Следующий релиз
#927
=> Rewrite Tooltip, Hint and Popup FTW

packages/retail-ui/components/Modal/Modal.tsx, packages/retail-ui/components/Modal/ModalBody.tsx, packages/retail-ui/components/Modal/ModalClose.tsx, packages/retail-ui/components/Modal/ModalContext.tsx, packages/retail-ui/components/Modal/ModalFooter.tsx, packages/retail-ui/components/Modal/ModalHeader.tsx, packages/retail-ui/components/Modal/__tests__/Modal-test.tsx
Поправил генерацию доки для `Modal`
=> Modal styleguide fix

packages/retail-ui/components/DatePickerOld/DatePicker.less
=> fix(DatePickerOld): fix firefox specific bug

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/reducer/autocomplete.tsx
=>  fix(ComboBox): don't do search on focus in autocomplete mode

packages/react-ui-screenshot-tests/gemini/screens/ComboBox/Component/AutoFocus/plain/firefox.png
Заменил сломанный скриншот в #929.
=> test(ComboBox): fix broken ff screenshot

packages/retail-ui/components/ComboBox/ComboBox.tsx, packages/retail-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx, packages/retail-ui/components/CustomComboBox/reducer/autocomplete.tsx, packages/retail-ui/components/CustomComboBox/reducer/default.tsx
=>  feat(ComboBox): add open/close methods

packages/react-ui-screenshot-tests/gemini/screens/Textarea set selection/Select all by button/Selected/chrome.png
=> test(Textarea): update screenshot for chrome 70+

packages/react-ui-screenshot-tests/gemini/screens/Hint right/mouseOver/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Hint with 100%-width input/mouseOver/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Popup All pin opened on small elements/plain/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Popup Hint/plain/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Popup Toast/plain/firefox.png, packages/retail-ui/components/Popup/Popup.less, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/Popup/__tests__/__snapshots__/Popup-test.tsx.snap
=>  fix(Popup): remove unwanted pin border in IE

packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Hint wrap inline-block/mouseOver/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip wrap inline-block/hover/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip wrap inline-block/hover/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Tooltip wrap inline-block/hover/ie11.png, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/RenderContainer/RenderContainer.tsx, packages/retail-ui/lib/listenFocusOutside.tsx
Поправил механику поиска контейнеров и работу `clickOutside`
Порефакторил `RenderContainer`
=> fix(RenderContainer): correct store ids in data-attribute

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/Popup/__tests__/Popup-test.tsx, packages/retail-ui/components/Tooltip/Tooltip.tsx, packages/retail-ui/components/Tooltip/__tests__/Tooltip-test.tsx, packages/retail-ui/lib/utils.ts
=> fix(Tooltip): reset opened state by trigger prop

packages/react-ui-testing/Tests/TestEnvironment/Browser.cs
Костыль до переезда на TC, чтобы первые пару тестов не отваливались из-за очереди сауса
=> test(react-ui-testing): increase webdriver connection timeout

packages/retail-ui/components/Input/Input.flat.less
=> fix(Input): fix regression around medium font-size

packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/internal/InternalMenu/InternalMenu.tsx, packages/retail-ui/components/internal/PopupMenu/PopupMenu.tsx
=> [InternalMenu] fixed focus on root element

packages/retail-ui/components/Kebab/Kebab.tsx, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/internal/InternalMenu/InternalMenu.tsx, packages/retail-ui/components/internal/PopupMenu/PopupMenu.tsx
Fixes #996
Добавил `onOpen` проп в `Popup`.
В хендлере на onOpen вызваю `focus` у `InternalMenu`
=> [InternalMenu] Fix window.scrollTo on focus

packages/retail-ui/components/Fias/Fias.tsx, packages/retail-ui/components/Fias/Form/FiasComboBox.tsx, packages/retail-ui/components/Fias/Form/FiasForm.tsx, packages/retail-ui/components/Fias/Form/FiasSearch.tsx, packages/retail-ui/components/Fias/README.md, packages/retail-ui/components/Fias/__stories__/Fias.stories.tsx, packages/retail-ui/components/Fias/api/APIResultFactory.ts, packages/retail-ui/components/Fias/api/FiasAPI.ts, packages/retail-ui/components/Fias/api/MockAPI.ts, packages/retail-ui/components/Fias/api/data.json, packages/retail-ui/components/Fias/constants/locale.ts, packages/retail-ui/components/Fias/logger/Logger.ts, packages/retail-ui/components/Fias/models/Address.ts, packages/retail-ui/components/Fias/models/AddressElement.ts, packages/retail-ui/components/Fias/types.ts
=> [Fias]: доработки и улучшения

packages/retail-ui/components/Autocomplete/Autocomplete.adapter.ts, packages/retail-ui/components/Autocomplete/Autocomplete.tsx
=> fix(Autocomplete): многократный вызов source

packages/retail-ui/components/DatePicker/DatePicker.tsx, packages/retail-ui/components/DatePicker/__tests__/DatePicker-test.tsx
=> fix(DatePicker): do not open on focus if disabled

packages/retail-ui/components/Sticky/Sticky.tsx
=> fix(Sticky): infinity update loop in safari

packages/retail-ui/components/TopBar/User.tsx
=> fix(TopBar): update User's links to cabinet.kontur.ru

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx
=>  fix(ComboBox): close combobox on clickOutside

packages/retail-ui/components/Calendar/Calendar.less
=> fix(Calendar): set box-sizing

packages/retail-ui/components/ComboBoxOld/ComboBoxRenderer.js
=> fix(ComboBoxOld): fix click on disabled arrow

packages/retail-ui/components/Modal/Modal.less
=> fix(Modal): скрыта нативная рамка фокуса в ff

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/CustomComboBox/reducer/default.tsx
=>  fix(ComboBox): keep focus after click on refresh

packages/retail-ui/components/Radio/README.md
=> docs(Radio): fix warning in styleguidist

packages/retail-ui/components/Kebab/Kebab.less, packages/retail-ui/components/Kebab/Kebab.tsx, packages/retail-ui/components/Kebab/__stories__/Kebab.stories.tsx
=> feat(Kebab): add size medium

packages/retail-ui/components/Paging/Paging.tsx
Теперь вместо `Required` выводится значение по умолчанию
=> docs(Paging): add default value description for `component` prop

packages/retail-ui/components/Fias/constants/locale.ts, packages/retail-ui/components/Fias/models/Address.ts
Разрешаем искать дома в Планировочных структурах (поле "Иная территория") без указания улицы.
Адрес для проверки: _Кемеровская область, город Мыски, квартал 4-ый, дом 14_
fix #1098
=> fix(Fias): allow to search for houses in planning structures

packages/retail-ui/components/Logotype/Logotype.tsx
Добавил пропсу для локализации логотипа
=> feat(Logotype): add locale prop

packages/retail-ui/components/CustomComboBox/ComboBoxView.tsx
Правка лечит проблему, описанную здесь https://github.com/skbkontur/retail-ui/issues/1090
=> fix(Combobox): fix non-closing menu with disablePortal prop

packages/react-ui-screenshot-tests/gemini/button.js, packages/react-ui-screenshot-tests/gemini/screens/Button with width/plain/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Button with width/plain/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Button with width/plain/ie11.png, packages/retail-ui/components/Button/Button.less, packages/retail-ui/components/Button/__stories__/Button.stories.tsx
=> fix(Button): text align center with custom width

packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx
Поправил начальное положение DropdownContainer'a.
=> fix(DropdownContainer): fixed initial position

packages/retail-ui/components/ComboBox/README.md
Добавил в пример вывод ранее выбранного элемента в выпадашке
=> docs(ComboBox): improve example, add `selectedItem` in complex menu

packages/retail-ui/components/Toast/README.md
=> docs(Toast): add usage example

packages/retail-ui/components/ScrollContainer/ScrollContainer.tsx, packages/retail-ui/components/ScrollContainer/__stories__/ScrollContainer.stories.tsx
Некоторая тавтология в названия присутствует, ну и в целом ревью не помешает :)
=> Scroll container scroll state

packages/retail-ui/package.json, packages/retail-ui/styleguide.config.js
Починил автоматический паблиш для TeamCity
=> ci(retail-ui): fix publishing on TeamCity

packages/retail-ui/README.md, packages/retail-ui/ROADMAP.md
- Добавлен бейдж с отображением статуса билда текущего мастера. Для корректного отображения статуса в бейдже необходимо быть авторизованным в TeamCity
- Обновил роадмап
=> Readme roadmap update

packages/retail-ui/components/DateInput/SelectionHelpers.tsx
Sometimes clear selection on IE11 caused to error 0x800a025e
fix #1205
=> fix(DatePicker): fix clear selection on IE11

packages/retail-ui/components/Fias/Form/FiasForm.tsx
=> fix(Fias): fix textarea import

packages/retail-ui/lib/listenFocusOutside.tsx
Fix #1107
*решение отсюда d99676d*
=> fix(Tooltip): fix svg icons click in ie11

packages/retail-ui/components/Button/Button.common.less
fix  #1213
Повысил специфичность для стилей ссылки.
=> fix(Button): fix disabled link background

packages/retail-ui/components/CustomComboBox/ComboBoxMenu.tsx
=> fix(ComboBoxMenu): unique keys warning

packages/retail-ui/LOCALEPROVIDER.md
Исправил пример с обзором всех доступных контролов
=> docs(LocaleProvider): refactor example

packages/react-ui-validations/src/ValidationWrapper.tsx
Добавил поддержку `React.createRef()`
=> chore(ValidationWrapper): support different refs

packages/retail-ui/components/Autocomplete/Autocomplete.js.flow, packages/retail-ui/components/ComboBox/ComboBox.js.flow, packages/retail-ui/components/ComboBox/index.js.flow, packages/retail-ui/components/DropdownMenu/DropdownMenu.js.flow, packages/retail-ui/components/Hint/Hint.js.flow, packages/retail-ui/components/Kebab/Kebab.js.flow, packages/retail-ui/components/Tooltip/Tooltip.js.flow
=> Optional props for flow types

packages/retail-ui/package.json, packages/retail-ui/styleguide.prod.config.js, yarn.lock
Правка для укладки Styleguidist'а в правильную папку при деплое старых версий.
=> build(retail-ui): correct styleguidist build for old versions

packages/retail-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/Select/Select.tsx, packages/retail-ui/components/SidePage/SidePageHeader.tsx, packages/retail-ui/components/Sticky/Sticky.tsx
Поломал импорты для `@skbkontur/react-ui` :(
=> fix(retail-ui): fix some imports for `@skbkontur/react-ui`

packages/retail-ui/components/Popup/Popup.tsx, packages/retail-ui/components/ensureOldIEClassName.ts, packages/retail-ui/lib/SSRSafePropTypes.ts, packages/retail-ui/lib/listenFocusOutside.tsx
CurrencyInput
Gapped
RadioGroup
Radio
CurrencyLabel
Tooltip
=> Сделал ssr безопасный код у нескольких компонентов:

packages/react-ui-validations/src/ValidationContainer.tsx, packages/react-ui-validations/src/ValidationContext.tsx, packages/react-ui-validations/src/ValidationWrapper.tsx, packages/react-ui-validations/src/smoothScrollIntoView.ts, packages/react-ui-validations/stories/Input.stories.tsx, packages/react-ui-validations/stories/ModalInput.stories.tsx
теперь scrollOffset это объект {top, bottom} для ишью https://github.com/skbkontur/retail-ui/issues/1250
=> feat(ValidationContainer): scrollOffset 2.0

packages/retail-ui/components/DropdownMenu/DropdownMenu.tsx, packages/retail-ui/components/TopBar/TopBarDropdown.tsx, packages/retail-ui/components/TopBar/__stories__/TopBar.stories.tsx, packages/retail-ui/components/internal/PopupMenu/PopupMenu.tsx
Добавил (вернул) методы open/close для TopBarDropdown, а как следствие для DropdownMenu и PopupMenu
=> fix(TopBarDropdown): added methods open & close

.teamcity/patches/buildTypes/TestConfig.kts, packages/retail-ui/components/DropdownMenu/DropdownMenu.tsx, packages/retail-ui/components/TopBar/TopBarDropdown.tsx, packages/retail-ui/components/TopBar/__stories__/TopBar.stories.tsx, packages/retail-ui/components/TopBar/__tests__/TopBarDropdown-test.tsx, packages/retail-ui/components/internal/PopupMenu/PopupMenu.tsx
=> fix(TopBarDropdown): add open/close methods

packages/retail-ui/components/Tabs/Tabs.tsx
Как обычно, не тестим в 15-м реакте :(
=> fix(Tabs): context provider render children for reac@15

packages/retail-ui/components/ComboBox/README.md, packages/retail-ui/components/MenuItem/MenuItem.tsx
Добавить пример использования в `stylegudist` (Кнопка "Добавить" должна появляться только если value отсутствует или прилетело событие `onInputChange`, событие `onChange` должно сбрасывать флаг рендера кнопки)
Существует проблема, при добавлении элемента не сохраняется фокус в `ComboBox`
=> feat(MenuItem): add `link` prop

packages/retail-ui/README.md
Пофиксил бэйджик TeamCity после реструктуризации конфигов.
=> docs(retail-ui): fix teamcity badge

packages/retail-ui/components/Paging/Paging.tsx
=> fix(Paging): add autofocus for IE11

packages/retail-ui/components/TokenInput/TokenInput.tsx
=> fix(TokenInput): add mapping `valueToString` before copying to clipboard

packages/retail-ui/components/Dropdown/Dropdown.js.flow, packages/retail-ui/components/DropdownMenu/DropdownMenu.js.flow, packages/retail-ui/components/Kebab/Kebab.js.flow, packages/retail-ui/components/Logotype/Logotype.js.flow, packages/retail-ui/components/Modal/Modal.js.flow, packages/retail-ui/components/Modal/ModalBody.js.flow, packages/retail-ui/components/Modal/ModalContext.js.flow, packages/retail-ui/components/Modal/ModalFooter.js.flow, packages/retail-ui/components/Modal/ModalHeader.js.flow, packages/retail-ui/components/RadioGroup/RadioGroup.js.flow, packages/retail-ui/components/SidePage/SidePage.js.flow, packages/retail-ui/components/SidePage/SidePageContainer.js.flow, packages/retail-ui/components/SidePage/SidePageContext.js.flow, packages/retail-ui/components/TopBar/TopBar.js.flow, packages/retail-ui/components/TopBar/TopBarLogout.js.flow
=> fix(flow): update types

packages/retail-ui/components/Toggle/Toggle.less
=> fix(Toggle): fix overflow issue in Safari (#1411)

packages/retail-ui/components/Select/Select.tsx
В методе select есть код `setTimeout(this.focus, 0)`, внутри `focus` есть использование `this`
=> fix(Select): bind public focus function to component instance

packages/react-ui-testing/SeleniumTesting/Controls/Toast.cs, packages/react-ui-testing/TestPages/src/ReactTestApplication.jsx, packages/react-ui-testing/TestPages/src/components/TestPages/ToastTestPage.jsx, packages/react-ui-testing/Tests/ToastTests/ToastTest.cs, packages/react-ui-testing/Tests/ToastTests/ToastTestPage.cs, packages/retail-ui/components/Toast/ToastStatic.tsx, packages/retail-ui/components/Toast/ToastView.tsx
Добавил тестовую обвязку для тоста (статичная версия и ref версия) и тесты на него
=> test(Toast): toast is testable

packages/react-ui-testing/SeleniumTesting/Controls/Toggle.cs, packages/react-ui-testing/TestPages/src/ReactTestApplication.jsx, packages/react-ui-testing/TestPages/src/components/TestPages/ToggleTestPage.jsx, packages/react-ui-testing/Tests/ToggleTests/ToggleTest.cs, packages/react-ui-testing/Tests/ToggleTests/ToggleTestPage.cs
Добавил тестовую обвязку для Toggle, написал тесты на поведения Toggle по аналогии с Combobox
=> test(Toggle): toggle is testable

packages/retail-ui/components/Button/Button.tsx, packages/retail-ui/lib/events/tabListener.ts
=> fix(Button): add dropping `isTabPressed` by mouseDown

packages/react-ui-screenshot-tests/gemini/Checkbox.js, packages/retail-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
Так как в будущем структура тестов и директорий со скриншотами будет соответствовать историям в storybook. Необходимо чтобы названия групп и историй не содержали зарезервированных символов https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#naming-conventions
=> refactor(Checkbox): rename story without slash character

packages/react-ui-validations/docs/Common/Demo.tsx, packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx, packages/react-ui-validations/docs/Pages/Displaying/ErrorMessages/ErrorMessages.md, packages/react-ui-validations/docs/Pages/Displaying/FormValidity/FormValidity.demo.tsx, packages/react-ui-validations/docs/Pages/Displaying/FormValidity/FormValidity.md, packages/react-ui-validations/docs/Pages/Displaying/GettingStarted/GettingStarted.md, packages/react-ui-validations/docs/Pages/Displaying/ScrollToValidation/ScrollToValidation.demo.tsx, packages/react-ui-validations/docs/Pages/Displaying/ScrollToValidation/ScrollToValidation.md, packages/react-ui-validations/docs/Pages/Displaying/ValidationType/SubmitValidation.demo.tsx, packages/react-ui-validations/docs/Pages/Displaying/ValidationType/ValidationType.md, packages/react-ui-validations/docs/Pages/Examples/ArrayExample/ArrayExample.demo.tsx, packages/react-ui-validations/docs/Pages/Examples/Editors/Editors.demo.tsx, packages/react-ui-validations/docs/Pages/Examples/GuidesExample/GuidesExample.demo.tsx, packages/react-ui-validations/docs/Pages/Examples/GuidesExample/GuidesExample.md, packages/react-ui-validations/docs/Pages/Validator/Arrays/ObjectArray.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/Arrays/PrimitiveTypeArray.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/MissingNodes/MissingObjectNode.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/MissingNodes/MissingUiNode.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/Objects/FlatObject.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/Objects/NestedObject.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/Objects/PrimitiveType.demo.tsx, packages/react-ui-validations/docs/Pages/Validator/Reusable/Reusable.demo.tsx
поправил замечания от @dzekh 
подсветку кода оставил как есть, он самая адекватная из тех что есть, светлые темы не очень, похожих на стайлгайдист нету, однажды все равно переедем на стайлгайдист - будет одинаково
текст ссылки переделал на VIEW CODE, но цвет остался синий
=> refactor(react-ui-validations): docs style changes

packages/retail-ui/components/SidePage/SidePage.tsx
=> chore(retail-ui): Update SidePage typings

packages/retail-ui/components/internal/MaskedInput/MaskedInput.tsx, packages/retail-ui/components/internal/MaskedInput/__tests__/MaskedInput-test.tsx
=>  fix(MaskedInput): add support prop 'defaultValue'

packages/retail-ui/components/SidePage/SidePage.tsx
=> fix(SidePage): allow pass string to width prop (#1447)

packages/retail-ui/components/DateInput/DateInputFallback.tsx
=> fix(DateInputFallback): remove unnecessary call 'emitChange'

packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx
=> fix(DropdownContainer): change calculations for positioning up

packages/react-ui-validations/package.json, packages/react-ui-validations/src/ValidationTooltip.tsx
fix #1138 fix #1102
Заиспользовал новый триггер у Tooltip `trigger={'hover&focus'}`
=> fix(react-ui-validations): tooltip improvements

packages/retail-ui/components/Textarea/Textarea.tsx
=> fix(Textarea): add blocking Enter after reaching 'maxLength'

packages/retail-ui/package.json
Добавил команду для запуска плоского сторибука.
=> build: add storybook:flat command

packages/retail-ui/components/ThemeShowcase/ThemeShowcase.less, packages/retail-ui/components/ThemeShowcase/ThemeShowcase.tsx, packages/retail-ui/components/ThemeShowcase/ThemeShowcaseHelpers/FormatSourceCode.tsx
1) Таблица теперь влазит в отведенные styleguidist'ом 886px
2) Тултип с исходным кодом теперь может в production почти так же хорошо, как и в development :)
=> Fix theme showcase

packages/retail-ui/.styleguide/helpers.js
=> docs: exclude Playground from the list

packages/retail-ui/components/Textarea/Textarea.tsx
=> [LTS] fix(Textarea): add blocking Enter after reaching 'maxLength'

packages/retail-ui/components/Input/Input.tsx
=> [LTS] fix(Input): add calling 'selectAll' via 'raf'

packages/retail-ui/components/Switcher/Switcher.tsx
=> feat(Switcher): add prop 'size'

packages/react-ui-screenshot-tests/gemini/tokenInput.js, packages/retail-ui/components/TokenInput/TokenInput.tsx
Влейте пожалуйста, не можем нормально написать е2е с токенинпутом тесты без этого
=> fix(TokenInput): remove hardcoded dataTid

packages/retail-ui/scripts/publish/old-version/index.js
=> ci: correct publish old-version

packages/react-ui-screenshot-tests/gemini/input.js, packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/chromeFlat.png, packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/firefoxFlat.png, packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Input error and focus/focused/ie11Flat.png, packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/chrome.png, packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/chromeFlat.png, packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/firefox.png, packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/firefoxFlat.png, packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/ie11.png, packages/react-ui-screenshot-tests/gemini/screens/Input warning and focus/focused/ie11Flat.png, packages/retail-ui/components/Input/Input.flat.less, packages/retail-ui/components/Input/__stories__/Input.stories.tsx
=> [LTS] fix(Input): delete CSS class '.focus' for flat theme

packages/retail-ui/components/Radio/Radio.tsx
=> fix(Radio): fix long typechecking

packages/react-ui-testing/PromoSite/package.json, packages/react-ui-testing/PromoSite/yarn.lock
=> build(react-ui-testing): update deps

packages/retail-ui/components/Button/Button.mixins.ts, packages/retail-ui/components/Button/Button.styles.ts, packages/retail-ui/components/Button/Button.tsx, packages/retail-ui/components/variables.less, packages/retail-ui/lib/theming/themes/DefaultTheme.ts
Порефакторил js-стили, вернул миксины.
=> refactor(Button): mixins 

packages/retail-ui/components/TokenInput/TokenInput.tsx
=> refactor(TokenInput): remove unnecessary render return type

packages/react-ui-selenium/images/Switcher/errored/idle/chromeFlat/idle.png, packages/react-ui-selenium/tests/Switcher.ts
=> test(Switcher): skip flaky screenshot test

packages/retail-ui/components/Fias/Fias.tsx, packages/retail-ui/components/Fias/Form/FiasForm.tsx, packages/retail-ui/components/Fias/models/Address.ts, packages/retail-ui/components/Fias/models/AddressElement.ts, packages/retail-ui/components/Fias/models/__tests__/Address/Address-test.ts, packages/retail-ui/components/Fias/models/__tests__/Address/__fixtures__/getDiffFields.ts, packages/retail-ui/components/Fias/models/__tests__/AddressElement/AddressElement-test.ts, packages/retail-ui/components/Fias/models/__tests__/AddressElement/__fixtures__/isEqualTo.ts
=> feat(Fias): search streets through not only direct parent

packages/retail-ui/components/Select/Select.module.less, packages/retail-ui/components/Select/Select.styles.ts
=> fix(Select): prevent styles reset, caused by code-splitting

packages/retail-ui/components/Button/Button.module.less, packages/retail-ui/components/Button/Button.styles.ts, packages/retail-ui/components/ThemeProvider/Playground/darkTheme.ts, packages/retail-ui/components/variables.less, packages/retail-ui/lib/theming/themes/DefaultTheme.ts
=> fix(Button): add variables for disabled state

packages/retail-ui/components/Button/Button.adapter.ts, packages/retail-ui/components/ComboBox/ComboBox.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBoxReducer.tsx, packages/retail-ui/components/Select/Select.tsx
Работа isButton, если используются адаптеры.
=> fix: call keyDown handler in Select and Combobox

packages/react-ui-selenium/images/RadioGroup/disabled/all Radio disabled/chrome/all Radio disabled.png, packages/react-ui-selenium/images/RadioGroup/disabled/all Radio disabled/firefox/all Radio disabled.png, packages/react-ui-selenium/images/RadioGroup/disabled/all Radio disabled/ie11/all Radio disabled.png, packages/react-ui-selenium/tests/RadioGroup.ts, packages/retail-ui/components/Radio/Radio.tsx, packages/retail-ui/components/RadioGroup/__stories__/RadioGroup.stories.tsx
=> fix(Radio): show label as disabled if context.disabled is true

packages/retail-ui/components/CurrencyInput/CurrencyHelper.tsx, packages/retail-ui/components/CurrencyInput/__tests__/CurrencyHelper-test.tsx, packages/retail-ui/components/CurrencyLabel/CurrencyLabel.tsx, packages/retail-ui/package.json, yarn.lock
=> fix(CurrencyLabel): don't throw error if fractionDigits is zero/float

packages/retail-ui/components/Paging/Paging.tsx
Закрывает https://github.com/skbkontur/retail-ui/issues/1232
=> refactor(Paging): remove 'strings' prop

packages/retail-ui/components/Select/Select.tsx, packages/retail-ui/components/Select/__stories__/Select.stories.tsx
React.ReactNode для коммента в item, и пример использования
=> fix(Select): added comment type; added story

packages/retail-ui/components/RenderContainer/RenderContainerNative.tsx
При SSR из-за использования CreatePortal всё разваливается
=> fix: SSR safe usage CreatePortal

packages/react-ui-selenium/images/ZIndex/Toast and Loader/Toast covers Loader/chrome/Toast covers Loader.png, packages/react-ui-selenium/images/ZIndex/Toast and Loader/Toast covers Loader/firefox/Toast covers Loader.png, packages/react-ui-selenium/images/ZIndex/Toast and Loader/Toast covers Loader/ie11/Toast covers Loader.png, packages/react-ui-selenium/tests/ZIndex.ts, packages/retail-ui/components/Loader/__stories__/Loader.stories.tsx, packages/retail-ui/components/Toast/ToastView.tsx, packages/retail-ui/components/ZIndex/ZIndexStorage.ts, packages/retail-ui/components/ZIndex/__stories__/ZIndex.stories.tsx
Задал тосту наивысший приоритет
fix #1706
=> fix(Toast): show above Loader

packages/retail-ui/components/DropdownContainer/DropdownContainer.tsx, packages/retail-ui/components/MenuItem/MenuItem.module.less, packages/retail-ui/components/MenuItem/MenuItem.tsx, packages/retail-ui/components/Select/Select.tsx, packages/retail-ui/components/Select/__stories__/Select.stories.tsx
опционально обрезать айтем точками
=> feat(Select): overflow and nowrap item label

packages/react-ui-validations/src/ValidationWrapperInternal.tsx
=> fix(ValidationWrapperInternal): pass down focus event

packages/react-ui-validations/src/ValidationTooltip.tsx
detection radioGroup didn't work, fix that and add inline-block wrapper for fix size of wrapper of tooltip position
fix #1616, fix #1674
=> fix(ValidationTooltip): detection radiogroup, add inline-block wrapper

packages/retail-ui/components/Toggle/Toggle.styles.ts
=> fix(Toggle): checked and focused view

packages/retail-ui/.creevey/tests/Modal.ts, packages/retail-ui/components/Modal/Modal.module.less, packages/retail-ui/components/Modal/__stories__/Modal.stories.tsx
Правки из https://github.com/skbkontur/retail-ui/pull/1754
=> Modal header add word break

packages/react-ui-validations/src/ValidationTooltip.tsx, packages/retail-ui/components/ComboBox/ComboBox.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBox.tsx, packages/retail-ui/components/CustomComboBox/CustomComboBoxReducer.tsx
Дублировал в LTS:
1. b804b84 (#1640) close #1747
2. #1725
=> LTS 0.53.6

packages/retail-ui/components/SidePage/SidePageHeader.tsx
Доработка для фикса #1485 в заголовке сайдпейлда
=> fix(SidePageHeader): fix maximum update depth

.vscode/settings.json, packages/retail-ui/.creevey/images/Gapped/Wrap Elements/chrome.png, packages/retail-ui/.creevey/images/Gapped/Wrap Elements/firefox.png, packages/retail-ui/.creevey/images/Gapped/Wrap Elements/ie11.png, packages/retail-ui/.creevey/images/Modal/Modal without header/open modal/chrome/open modal.png, packages/retail-ui/.creevey/images/Modal/Modal without header/open modal/firefox/open modal.png, packages/retail-ui/.creevey/images/Modal/With alignTop/alignTop/chrome/alignTop.png, packages/retail-ui/.creevey/images/Modal/With alignTop/alignTop/firefox/alignTop.png, packages/retail-ui/.creevey/images/ZIndex/Big modal with Loader/Header covers Loader/chrome/Header covers Loader.png, packages/retail-ui/.creevey/images/ZIndex/Loader in Modal/Footer covers loader/chrome/Footer covers loader.png, packages/retail-ui/.creevey/images/ZIndex/Loader in Modal/Footer covers loader/firefox/Footer covers loader.png, packages/retail-ui/components/Gapped/Gapped.tsx, packages/retail-ui/components/Gapped/__stories__/Gapped.stories.tsx, packages/retail-ui/components/Modal/Modal.module.less, packages/retail-ui/components/Modal/ModalFooter.tsx, packages/retail-ui/typings/mocha/index.d.ts
Случайно сломал запуск скриншотных тестов на CI в #1820
=> test(creevey): fix broken tests run

packages/retail-ui/components/Tooltip/Tooltip.tsx, packages/retail-ui/components/Tooltip/__tests__/Tooltip-test.tsx
=> feat(Tooltip): add onOpen prop

packages/retail-ui/components/Logotype/ProductWidget.tsx
зарелизили виджет продуктов без jquery
https://yt.skbkontur.ru/issue/WS-42804
https://widget-product.kontur.ru/
=> rm jquery downloading

packages/retail-ui/components/Logotype/ProductWidget.tsx
Пересоздал PR #1844
зарелизили виджет продуктов без jquery
https://yt.skbkontur.ru/issue/WS-42804
https://widget-product.kontur.ru/
=> fix: remove jquery downloading

packages/retail-ui/.creevey/images/Loader/Wrapper with custom height and active loader/have children with same height while loader active/chrome/have children with same height while loader active.png, packages/retail-ui/.creevey/images/Loader/Wrapper with custom height and active loader/have children with same height while loader active/firefox/have children with same height while loader active.png, packages/retail-ui/.creevey/images/Loader/Wrapper with custom height and active loader/have children with same height while loader active/ie11/have children with same height while loader active.png, packages/retail-ui/.creevey/images/Loader/Wrapper with custom height and inactive loader/have children with same height while loader inactive/chrome/have children with same height while loader inactive.png, packages/retail-ui/.creevey/images/Loader/Wrapper with custom height and inactive loader/have children with same height while loader inactive/firefox/have children with same height while loader inactive.png, packages/retail-ui/.creevey/images/Loader/Wrapper with custom height and inactive loader/have children with same height while loader inactive/ie11/have children with same height while loader inactive.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/default theme bottom/chrome/default theme bottom.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/default theme bottom/firefox/default theme bottom.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/default theme bottom/ie11/default theme bottom.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/default theme top/chrome/default theme top.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/default theme top/firefox/default theme top.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/default theme top/ie11/default theme top.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/flat theme bottom/chrome/flat theme bottom.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/flat theme bottom/firefox/flat theme bottom.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/flat theme bottom/ie11/flat theme bottom.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/flat theme top/chrome/flat theme top.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/flat theme top/firefox/flat theme top.png, packages/retail-ui/.creevey/images/ThemeProvider/playground/flat theme top/ie11/flat theme top.png, packages/retail-ui/.creevey/images/TokenInput/disabled/idle/chrome/idle.png, packages/retail-ui/.creevey/images/TokenInput/disabled/idle/firefox/idle.png, packages/retail-ui/.creevey/images/TokenInput/disabled/idle/ie11/idle.png, packages/retail-ui/.creevey/tests/Loader.ts, packages/retail-ui/components/Loader/Loader.tsx, packages/retail-ui/components/Loader/__stories__/Loader.stories.tsx, packages/retail-ui/components/ThemeProvider/Playground/styles.module.less, packages/retail-ui/components/TokenInput/TokenInput.module.less, packages/retail-ui/components/TokenInput/TokenInput.styles.ts, packages/retail-ui/components/TokenInput/TokenInput.tsx
Добавил height: 100% для zIndex компонента Loader.
Closes #1855
=> fix(Loader): пофиксил высоту дочерних компонентов по родителю

packages/react-ui-validations/docs/Pages/Validator/Objects/Objects.md
=> docs(react-ui-validations): fix typo

packages/retail-ui/.creevey/tests/Toggle.ts, packages/retail-ui/.creevey/tests/TokenInput.ts, packages/retail-ui/.creevey/tests/Tooltip.ts, packages/retail-ui/components/Tooltip/Tooltip.tsx
<details><summary>было</summary>
</details>
<details><summary>стало</summary>
</details>
---
Добавил задержку перед открытием тултипа
fix #1867
=> refactor(Tooltip): change logic for trigger 'hover&focus'

packages/retail-ui/.creevey/images/SidePage/Simple/open side-page/chrome/open side-page.png, packages/retail-ui/.creevey/images/SidePage/Simple/open side-page/firefox/open side-page.png, packages/retail-ui/components/SidePage/SidePage.module.less, packages/retail-ui/components/SidePage/SidePage.tsx
=> refactor(SidePage): make non-blocking SidePage responsive

packages/retail-ui/components/TopBar/README.md, packages/retail-ui/components/TopBar/User.tsx, packages/retail-ui/components/TopBar/locale/locales/en.ts, packages/retail-ui/components/TopBar/locale/locales/ru.ts, packages/retail-ui/components/TopBar/locale/types.ts
=> fix(TopBar): align left caption in user dropdown

packages/retail-ui/components/TopBar/README.md, packages/retail-ui/components/TopBar/User.tsx, packages/retail-ui/components/TopBar/locale/locales/en.ts, packages/retail-ui/components/TopBar/locale/locales/ru.ts, packages/retail-ui/components/TopBar/locale/types.ts
=> feat(TopBar): remove header in user dropdown

packages/react-ui/components/TopBar/TopBarDropdown.tsx
=> fix(TopBar): add typings for topbar dropdown props

packages/retail-ui/components/TopBar/TopBarDropdown.tsx
Дубликат #1915 в master
fix #1497
=> fix(TopBar): add typings for topbar dropdown props (master)

packages/react-ui/package.json
=> build(react-ui): specify sideEffects

packages/retail-ui/components/DatePicker/DatePicker.tsx, packages/retail-ui/components/DatePicker/__stories__/DatePicker.stories.tsx, packages/retail-ui/components/DatePicker/__tests__/DatePicker-test.tsx
- Сделал фокус на поле при первой отрисовке если передан проп `autoFocus`
- Добавил unit-тест
- Добавил story
close #1943
=> fix(DatePicker): fix autoFocus behavior

packages/retail-ui/components/TokenInput/TokenInput.tsx
Добавил пропсу `maxMenuHeight` в компонент `TokenInput` для последующего прокидывания до `TokenInputMenu`.
close #1940
=> feat(TokenInput): new prop 'maxMenuHeight'

packages/retail-ui/components/Modal/Modal.tsx
Пересоздано #1968.
Дубль #1972 в LTS.
=> feat(Modal): add 'disableFocusLock' prop

packages/react-ui/.styleguide/components/IssueList/IssueList.tsx, packages/react-ui/.styleguide/components/Pathline/PathlineRenderer.tsx, packages/react-ui/.styleguide/config/root.config.js
Временно закомментил использование кастомных компонентов для stylegudist
=> docs: disable custom components for styleguide

packages/retail-ui/components/TokenInput/TokenInput.tsx, packages/retail-ui/components/TokenInput/TokenInputMenu.tsx, packages/retail-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
Добавил пропсы:
- `onInputChange`, чтобы контролировать введенное значение извне
- `renderAddButton`, чтобы кастомизировать пункт меню для добавления нового элемента
Добавил пример использования в стори
close #1954
=> Добавил возможность менять отображение пункта меню для добавления нового элемента

packages/retail-ui/components/TokenInput/TokenInput.tsx, packages/retail-ui/components/TokenInput/TokenInputReducer.ts, packages/retail-ui/components/TokenInput/__tests__/TokenInput.test.tsx
- Добавил в публичное api метод `reset`
- Добавил unit-test
close #1956
=> feat(TokenInput): new public api method 'reset'

packages/react-ui/.creevey/images/TokenInput/custom add button/addButton/chrome.png, packages/react-ui/.creevey/images/TokenInput/custom add button/addButton/chromeFlat.png, packages/react-ui/.creevey/images/TokenInput/custom add button/addButton/firefox.png, packages/react-ui/.creevey/images/TokenInput/custom add button/addButton/firefoxFlat.png, packages/react-ui/.creevey/images/TokenInput/custom add button/addButton/ie11.png, packages/react-ui/.creevey/images/TokenInput/custom add button/addButton/ie11Flat.png, packages/react-ui/components/TokenInput/TokenInput.tsx, packages/react-ui/components/TokenInput/TokenInputMenu.tsx, packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx, packages/react-ui/components/TokenInput/__tests__/TokenInput.test.tsx
Продублировано в мастер #1955 
close #1954
=> feat(TokenInput): add onInputValueChange and renderAddButton props

packages/retail-ui/CHANGELOG.md, packages/retail-ui/package.json
=> feat(TokenInput): add onInputValueChange and renderAddButton props 

packages/react-ui/.creevey/images/TopBar/TopBar New/chrome.png, packages/react-ui/.creevey/images/TopBar/TopBar New/firefox.png, packages/react-ui/.creevey/images/TopBar/TopBar New/ie11.png, packages/react-ui/.creevey/images/TopBar/TopBar Old/chrome.png, packages/react-ui/.creevey/images/TopBar/TopBar Old/firefox.png, packages/react-ui/.creevey/images/TopBar/TopBar Old/ie11.png, packages/react-ui/.creevey/images/TopBar/TopBar noShadow/chrome.png, packages/react-ui/.creevey/images/TopBar/TopBar noShadow/firefox.png, packages/react-ui/.creevey/images/TopBar/TopBar noShadow/ie11.png, packages/react-ui/components/TopBar/TopBar.styles.ts, packages/react-ui/components/TopBar/__stories__/TopBar.stories.tsx
Полечил странный стиль. Сделал TopBar шире на скриншотах.
fix #1997
=> fix(TopBar): fix noShadow prop

README.md, packages/react-ui/.styleguide/helpers.js, packages/react-ui/MIGRATION.md
Собрал информацию по всем проектам и пакетам.
\+ Пофиксил опечатку в гайде по миграции.
close #2006
=> docs: add ecosystem info

packages/react-ui/components/TokenInput/TokenInput.tsx, packages/react-ui/components/TokenInput/__tests__/TokenInput.test.tsx
=> feat(TokenInput): new parameter 'onAddItem' in 'renderAddButton' prop

packages/retail-ui/.creevey/images/SidePage/Simple/open side-page/chrome/open side-page.png, packages/retail-ui/.creevey/images/SidePage/Simple/open side-page/firefox/open side-page.png, packages/retail-ui/.creevey/tests/ZIndex.ts, packages/retail-ui/components/SidePage/SidePage.module.less, packages/retail-ui/components/SidePage/SidePage.styles.ts, packages/retail-ui/components/SidePage/SidePage.tsx
=> fix(SidePage): don't block the page 

packages/react-ui/components/Link/Link.tsx, packages/react-ui/components/Link/__tests__/Link-test.tsx, packages/react-ui/lib/utils.ts
Переcоздано #2007 
> Добавлено автоматическое проставление noopener и noreferrer
=> feat(Link): fill rel attr with 'noopener  noreferrer'

packages/react-ui/components/Checkbox/Checkbox.styles.ts, packages/react-ui/internal/themes/DefaultTheme.ts, packages/react-ui/internal/themes/FlatTheme.ts
| ![image](https://user-images.githubusercontent.com/2708211/80631696-95f3b080-8a6f-11ea-9e30-3d4e29c98c99.png) | ![image](https://user-images.githubusercontent.com/2708211/80631740-a441cc80-8a6f-11ea-9e6a-feed5ff1a05f.png) |
| --- | --- |
Fixes #1935
=> fix(Checkbox): return style for `checked-active` state

packages/react-ui/components/Modal/ModalContext.tsx, packages/react-ui/components/SidePage/SidePageContext.ts, packages/react-ui/components/Tabs/TabsContext.ts, packages/react-ui/internal/ZIndex/ZIndex.tsx, packages/react-ui/lib/locale/LocaleContext.ts, packages/react-ui/lib/theming/ThemeContext.md, packages/react-ui/lib/theming/ThemeContext.ts
Добавил displayName для всех контекстов, чтобы они корректно отображались в консоли
=> refactor: added display names for all contexts

packages/react-ui-testing/SeleniumTesting/ControlBase.cs, packages/react-ui-testing/SeleniumTesting/Controls/ComboBox.cs, packages/react-ui-testing/Tests/ComboBoxTests/ComboBoxTest.cs, packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx, packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
- Перенес отмену DebouncedSearch в CloseRequest, убрал из Blur
- Тестовая обвязка ждет появления выпадашки в комбобоксе
- Добавил Data-tid на Menu и MenuItem реальных данных и жду их в обвязке
change #2031
=> fix([combobox]): fix DebounsedSearch bug and several bugs in test wrap

packages/retail-ui/.creevey/images/Gapped/With Null Childs/chrome.png, packages/retail-ui/.creevey/images/Gapped/With Null Childs/firefox.png, packages/retail-ui/.creevey/images/Gapped/With Null Childs/ie11.png, packages/retail-ui/components/Gapped/Gapped.tsx, packages/retail-ui/components/Gapped/__stories__/Gapped.stories.tsx, packages/retail-ui/components/Gapped/__tests__/Gapped-test.tsx
Пересоздано из #2037 
fix #2036
=> fix(Gapped): fix left margin for single child

packages/react-ui/internal/InputLikeText/InputLikeText.styles.ts, packages/react-ui/internal/InputLikeText/InputLikeText.tsx
=> fix(DatePicker): increase default `width` for `large` size

packages/react-ui-codemod/react-ui-2.0/__tests__/addCloudProp.test.ts, packages/react-ui-codemod/react-ui-2.0/__tests__/moveToAddons.test.ts, packages/react-ui-codemod/react-ui-2.0/__tests__/transformImportsAndExports.test.ts, packages/react-ui-codemod/react-ui-2.0/__tests__/transformOnChange.test.ts, packages/react-ui-codemod/react-ui-2.0/addCloudProp.ts, packages/react-ui-codemod/react-ui-2.0/helpers.ts, packages/react-ui-codemod/react-ui-2.0/moveToAddons.ts, packages/react-ui-codemod/react-ui-2.0/transformImportsAndExports.ts, packages/react-ui-codemod/react-ui-2.0/transformOnChange.ts
Кодмоды теперь не будут перезаписывать файлы в который не было изменений.
=> fix(react-ui-codemod): don't change unmodified sources

packages/retail-ui/components/Kladr/KladrAPI.js
`cherry-pick` from #2065
Fixes https://yt.skbkontur.ru/issue/keforms-4079
=> fix(Kladr): add filter for "empty" addresses from backend

packages/retail-ui/components/Kladr/KladrAPI.js
`cherry-pick` from #2065
Fixes #2076
Fixes https://yt.skbkontur.ru/issue/keforms-4079
=> fix(Kladr): add filter for "empty" addresses from backend (3)

packages/retail-ui/components/MenuItem/MenuItem.tsx
The duplicate of #2102 for LTS
=> fix(MenuItem): pass state into custom component

packages/react-ui/.creevey/images/PasswordInput/CapsLock label/chrome.png, packages/react-ui/.creevey/images/PasswordInput/CapsLock label/firefox.png, packages/react-ui/.creevey/images/PasswordInput/CapsLock label/ie11.png, packages/react-ui/.creevey/images/PasswordInput/Plain/Plain/chrome/Plain.png, packages/react-ui/.creevey/images/PasswordInput/Plain/Plain/firefox/Plain.png, packages/react-ui/.creevey/images/PasswordInput/Plain/Plain/ie11/Plain.png, packages/react-ui/.creevey/images/PasswordInput/Plain/With typed password/chrome/With typed password.png, packages/react-ui/.creevey/images/PasswordInput/Plain/With typed password/firefox/With typed password.png, packages/react-ui/.creevey/images/PasswordInput/Plain/With typed password/ie11/With typed password.png, packages/react-ui/.creevey/images/PasswordInput/Plain/With visible password/chrome/With visible password.png, packages/react-ui/.creevey/images/PasswordInput/Plain/With visible password/firefox/With visible password.png, packages/react-ui/.creevey/images/PasswordInput/Plain/With visible password/ie11/With visible password.png, packages/react-ui/components/PasswordInput/PasswordInput.tsx, packages/react-ui/components/PasswordInput/__tests__/PasswordInput-test.tsx
Переставлены иконки EyeOpened и EyeClosed.
Изменены соответствующие тесты и обновлены скриншоты.
Fixes #2111
=> Passwordinput eyes 2111

packages/retail-ui/components/Fias/api/FiasAPI.ts
=> fix(Fias): add "version" param to all requests

packages/react-ui/internal/MaskedInput/MaskedInput.styles.ts, packages/react-ui/internal/MaskedInput/MaskedInput.tsx
Поправил положение текста инпута и маски при правом выравнивании.
Fixes #1379
=> fix(Input): fixed wrong right mask position

packages/react-ui-validations/.storybook/webpack.config.js, packages/react-ui-validations/package.json, packages/react-ui-validations/rollup.base.config.js, packages/react-ui-validations/src/ReactUiDetection.ts, packages/react-ui-validations/webpack.docs.config.js, yarn.lock
Заменил динамический require обычным. Валидации должны заработать в codesandbox.
close #2151 fix #2039
И завел отдельную задачу по типизации этого require #2157.
=> fix(validations): give up dynamic require, fix codesandbox compatibility

packages/react-ui/components/DatePicker/Picker.styles.ts
Вернул бордер на место.
fix #2168
IF-28
=> fix(DatePicker): return TodayLink's border

packages/react-ui/.creevey/images/Textarea/Autoresizable textarea/chrome.png, packages/react-ui/.creevey/images/Textarea/Autoresizable textarea/chromeFlat.png, packages/react-ui/.creevey/images/Textarea/Autoresizable textarea/firefox.png, packages/react-ui/.creevey/images/Textarea/Autoresizable textarea/firefoxFlat.png, packages/react-ui/.creevey/images/Textarea/Autoresizable textarea/ie11.png, packages/react-ui/.creevey/images/Textarea/Autoresizable textarea/ie11Flat.png, packages/react-ui/components/Textarea/Textarea.styles.ts, packages/react-ui/components/Textarea/TextareaHelpers.tsx, packages/react-ui/components/Textarea/__stories__/Textarea.stories.tsx, packages/react-ui/internal/ThemePlayground/constants.ts, packages/react-ui/internal/themes/DefaultTheme.ts, packages/react-ui/internal/themes/Theme8px.ts
#2120 
Убрал из подсчета минимальной высоты умножение высоты строки на 3, т.к. многострочное поле может состоять и из 1 строки
=> fix(Textarea): fix min height

packages/react-ui/components/Input/Input.styles.ts
Убрал вроде бы не нужное свойство, ломающее некоторые нативные функции.
fix #2192 fix #2054
=> fix(Input): allow to scroll and select text while disabled

packages/react-ui/.creevey/images/ComboBox/with left icon/chrome.png, packages/react-ui/.creevey/images/ComboBox/with left icon/firefox.png, packages/react-ui/.creevey/images/ComboBox/with left icon/ie11.png, packages/react-ui/components/ComboBox/ComboBox.tsx, packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx, packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
Дизайнер рисует так, красиво. Но комбобоксом или автокомплитом это не сделать.
Давайте начнём с leftIcon :)
=> feat(ComboBox): add leftIcon prop

packages/react-ui-testing/PromoSite/yarn.lock, packages/react-ui-testing/TestPages/yarn.lock
>build(deps): bump ini in /packages/react-ui-testing/PromoSite
> build(deps): bump ini in /packages/react-ui-testing/TestPages
by dependabot
=>  build(deps): bump ini from 1.3.5 to 1.3.7

packages/react-ui/.creevey/config.js
Временно прописал старые версии браузеров для скриншотных тестов, пока мы заезжаем на новые.
=> test(react-ui): temporarily use older browsers

packages/react-ui/.creevey/images/Modal/Align Center And No Close/chrome.png, packages/react-ui/.creevey/images/Modal/Align Center And No Close/firefox.png, packages/react-ui/.creevey/images/Modal/Align Center And No Close/ie11.png, packages/react-ui/components/Modal/Modal.styles.ts, packages/react-ui/components/Modal/ModalHeader.tsx, packages/react-ui/components/Modal/__stories__/Modal.stories.tsx
=> fix(Modal.Header): fix right padding with noClose

packages/react-ui-testing/PromoSite/yarn.lock, packages/react-ui-testing/TestPages/yarn.lock
=> build: dependabot updates

packages/react-ui/.creevey/images/Textarea/Textarea with disabled extra row/chrome.png, packages/react-ui/.creevey/images/Textarea/Textarea with disabled extra row/chromeFlat.png, packages/react-ui/.creevey/images/Textarea/Textarea with disabled extra row/firefox.png, packages/react-ui/.creevey/images/Textarea/Textarea with disabled extra row/firefoxFlat.png, packages/react-ui/.creevey/images/Textarea/Textarea with disabled extra row/ie11.png, packages/react-ui/.creevey/images/Textarea/Textarea with disabled extra row/ie11Flat.png, packages/react-ui/.creevey/images/Textarea/Textarea with single row/chrome.png, packages/react-ui/.creevey/images/Textarea/Textarea with single row/chromeFlat.png, packages/react-ui/.creevey/images/Textarea/Textarea with single row/firefox.png, packages/react-ui/.creevey/images/Textarea/Textarea with single row/firefoxFlat.png, packages/react-ui/.creevey/images/Textarea/Textarea with single row/ie11.png, packages/react-ui/.creevey/images/Textarea/Textarea with single row/ie11Flat.png, packages/react-ui/components/Textarea/Textarea.styles.ts, packages/react-ui/components/Textarea/Textarea.tsx, packages/react-ui/components/Textarea/TextareaHelpers.tsx, packages/react-ui/components/Textarea/__stories__/Textarea.stories.tsx
Closes #2120
1. Добавил опциональный проп `extraRow`, который регулирует добавление дополнительной строки. Значение по умолчанию - `true`.
2. Добавил опциональный проп `disableAnimations`, который отключает анимацию при авто-ресайзе.
3. Добавил две истории - одна для однострочной `textarea`, вторая - для многострочной с отключенной доп. строкой. Для каждой истории добавил скриншоты.
4. zhzz: добавил автоматическое отключение анимации вместе с `extraRow`
=> [Textarea]: Возможность быть однострочной. 

packages/react-ui/components/Modal/Modal.styles.ts, packages/react-ui/components/Modal/ModalClose.tsx, packages/react-ui/components/SidePage/SidePage.styles.ts, packages/react-ui/internal/themes/DefaultTheme.ts
Задача: [IF-46](https://yt.skbkontur.ru/agiles/101-1467/102-17779?query=Assignee:%20oi.gol%20&issue=IF-46)
- Позиционирование иконок в кнопках правильное
- _**С кликабельными областями иконок в инпуте решили повременить, т.к просто сделать не получится из-за разных отступов слева и справа от иконки**_
- Кликабельная область крестика тултипа правильная
- Кликабельная область крестика модалки теперь стала правильная и появилась переменная `modalCloseButtonClickArea`. По пути были удаленные лишние расчеты и переменные в `Modal.styles.ts` файле.
- Кликабельную область крестика сайдпейджа сделать прям как на макете не получится из-за особенностей позиционирования инлайном. Но была добавлена переменная `sidePageCloseButtonClickAreaX`, которая увеличивает кликабельную область крестика слева и …
=> Кликабельные области иконок

packages/react-ui-testing/Tests/TestEnvironment/Browser.cs, packages/react-ui/.creevey/config.js
Перешли на отдельную учётку на гридах.
=> test: change selenium grid url

packages/react-ui/.creevey/images/SidePage/Left SidePage With Right SidePage/chrome.png, packages/react-ui/.creevey/images/SidePage/Left SidePage With Right SidePage/chrome8px.png, packages/react-ui/.creevey/images/SidePage/Left SidePage With Right SidePage/firefox.png, packages/react-ui/.creevey/images/SidePage/Left SidePage With Right SidePage/firefox8px.png, packages/react-ui/.creevey/images/SidePage/Left SidePage With Right SidePage/ie11.png, packages/react-ui/.creevey/images/SidePage/Left SidePage With Right SidePage/ie118px.png, packages/react-ui/components/SidePage/SidePage.tsx, packages/react-ui/components/SidePage/__stories__/SidePage.stories.tsx
=> fix(SidePage): fix sidepage counting for adding margins and shadows

packages/retail-ui/components/CustomComboBox/CustomComboBoxReducer.tsx
Cherry-picked from b804b8446dd73566200cd8f4346c4937ecfe922c
=> fix(ComboBox): call `onInputKeyDown` handler [0.53.x]

packages/react-ui/lib/locale/decorators.tsx
Тестировал на Cromium Portable v35.0.1916.27 (262261).
Fix #2370
=> fix(locale): add check that 'name' field is configurable

packages/react-ui/.creevey/images/Hint/Set Manual And Opened Prop On Click/click on hint/chrome/click on hint.png, packages/react-ui/.creevey/images/Hint/Set Manual And Opened Prop On Click/click on hint/chrome8px/click on hint.png, packages/react-ui/.creevey/images/Hint/Set Manual And Opened Prop On Click/click on hint/firefox/click on hint.png, packages/react-ui/.creevey/images/Hint/Set Manual And Opened Prop On Click/click on hint/firefox8px/click on hint.png, packages/react-ui/.creevey/images/Hint/Set Manual And Opened Prop On Click/click on hint/ie11/click on hint.png, packages/react-ui/.creevey/images/Hint/Set Manual And Opened Prop On Click/click on hint/ie118px/click on hint.png, packages/react-ui/components/Hint/Hint.tsx, packages/react-ui/components/Hint/__stories__/Hint.stories.tsx
Сценарий такой:
Hint закрыт
Наводим мышкой - создается таймер открытия на 400мс
нажимаем на компонент раньше, чем прошло 400 мс
По клику устанавливаем пропы `manual=true` и `opened=false`
Ожидание:
Hint не откроется потому что выставлены пропсы `manual=true` и `opened=false`
Реальность:
Hint все равно открывается
=> fix(Hint): clear opening timer

packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/chrome/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/chrome8px/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/chromeFlat/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/chromeFlat8px/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/firefox/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/firefox8px/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/firefoxFlat/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/firefoxFlat8px/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/ie11/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/ie118px/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/ie11Flat/Focused by tab.png, packages/react-ui/.creevey/images/Textarea/Different states/FocusedByTab/ie11Flat8px/Focused by tab.png, packages/react-ui/components/Textarea/__stories__/Textarea.stories.tsx, packages/react-ui/internal/ResizeDetector/ResizeDetector.tsx
Фикс для https://github.com/skbkontur/retail-ui/issues/2400
=> [LTS] [Textarea] Fix textarea focus by tab

packages/react-ui/components/Checkbox/Checkbox.tsx
Fix https://github.com/skbkontur/retail-ui/issues/2309
=> [LTS] [Checkbox] Fix not triggered onFocus handler

packages/retail-ui/components/Logotype/Logotype.module.less, packages/retail-ui/components/Logotype/Logotype.styles.ts, packages/retail-ui/components/Logotype/Logotype.tsx, packages/retail-ui/components/Logotype/README.md, packages/retail-ui/components/TopBar/README.md, packages/retail-ui/components/TopBar/TopBar.styles.ts, packages/retail-ui/package.json, yarn.lock
https://yt.skbkontur.ru/issue/IF-111
Поддержка новых логотипов для конролов `1.x `
=> feat: add support new Kontur logos from @skbkontur/logos

packages/react-ui/components/Hint/Hint.tsx, packages/react-ui/internal/themes/DefaultTheme.ts
Can change the hint background using a theme
=> feat(hint): get background color by theme

yarn.lock
Поднял версию @emotion/cache, чтобы избежать проблем подобных #2284 с нашей стороны.
=> build(react-ui): update @emotion/cache

packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx
Дубль #2450 в ЛТС, с небольшим отличием - оставлен workaround для firefox ([подробнее](https://github.com/skbkontur/retail-ui/pull/2450#discussion_r657066017)).
=> fix(Modal, SidePage, HBVS): performance

packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
=> fix(CurrencyInput): fix selection in IE11 [LTS]

packages/react-ui/internal/ZIndex/__stories__/ZIndex.stories.tsx
Фикс мигающих скриншотов, вероятно из-за #2445.
=> test(Loader): add delay due async enabling

packages/react-ui/components/Loader/Loader.tsx
Скорректировал момент восстановления фокуса из #2494 после мерджа с #2445. Дело в том, что после 2445 активность лоадера стала зависеть не только от пропа active. Было введено минимальное время показа спиннера. Соответственно, появилась зависимость еще от одного флага: `isSpinnerVisible`.
=> fix(Loader): fix focus disabling

packages/react-ui/.creevey/images/DatePicker/Different Sizes/chrome.png, packages/react-ui/.creevey/images/DatePicker/Different Sizes/chrome8px.png, packages/react-ui/.creevey/images/DatePicker/Different Sizes/firefox.png, packages/react-ui/.creevey/images/DatePicker/Different Sizes/firefox8px.png, packages/react-ui/.creevey/images/DatePicker/Different Sizes/ie11.png, packages/react-ui/.creevey/images/DatePicker/Different Sizes/ie118px.png, packages/react-ui/components/DateInput/DateInput.tsx, packages/react-ui/components/DatePicker/DatePicker.tsx, packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx, packages/react-ui/internal/InputLikeText/InputLikeText.styles.ts, packages/react-ui/internal/InputLikeText/InputLikeText.tsx
Починка ширины DatePicker со всеми значениями size.
fix #2025
=> fix(DatePicker): adjust the width depending on the size 

packages/react-ui/internal/CommonWrapper/CommonWrapper.tsx
Добавил описание для пропов `style` и `className`.
=> docs(CommonProps): add description for style and className props

packages/react-ui/components/Center/Center.md, packages/react-ui/components/Center/Center.tsx
Улучшил документацию контрола `Center`, изменил пример и немного поправил типы.
=> docs(Center): enhance documentation

packages/react-ui/internal/RenderContainer/RenderContainer.tsx, packages/react-ui/lib/Upgrades.ts, packages/react-ui/lib/theming/Emotion.ts
a duplication of #2561 for lts
=> fix(Upgrades): abillity to customize classNames prefix

packages/react-ui/components/Select/Select.styles.ts, packages/react-ui/components/Select/Select.tsx, packages/react-ui/components/Select/selectTheme.ts, packages/react-ui/internal/themes/DefaultTheme.ts
Отдельные переменные для заблокированного селекта, [задача](https://yt.skbkontur.ru/issue/IF-257).
=> fix(Select): add vars for disabled state

packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/chrome/opened.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/chrome/scrolled.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/chrome8px/opened.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/chrome8px/scrolled.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/firefox/opened.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/firefox/scrolled.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/firefox8px/opened.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/firefox8px/scrolled.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/ie11/opened.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/ie11/scrolled.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/ie118px/opened.png, packages/react-ui/.creevey/images/Dropdown/Inside Scrollable Container/scrolled/ie118px/scrolled.png, packages/react-ui/components/Dropdown/__stories__/Dropdown.stories.tsx
Добавил тесты для сценария из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1635489250104400).
=> test(Dropdown): screenshot open and scrolled

packages/react-ui/.creevey/images/DateInput/With No Value/focused/chrome.png, packages/react-ui/.creevey/images/DateInput/With No Value/focused/chrome8px.png, packages/react-ui/.creevey/images/DateInput/With No Value/focused/firefox.png, packages/react-ui/.creevey/images/DateInput/With No Value/focused/firefox8px.png, packages/react-ui/.creevey/images/DateInput/With No Value/focused/ie11.png, packages/react-ui/.creevey/images/DateInput/With No Value/focused/ie118px.png, packages/react-ui/.creevey/images/DateInput/With No Value/idle/chrome.png, packages/react-ui/.creevey/images/DateInput/With No Value/idle/chrome8px.png, packages/react-ui/.creevey/images/DateInput/With No Value/idle/firefox.png, packages/react-ui/.creevey/images/DateInput/With No Value/idle/firefox8px.png, packages/react-ui/.creevey/images/DateInput/With No Value/idle/ie11.png, packages/react-ui/.creevey/images/DateInput/With No Value/idle/ie118px.png, packages/react-ui/components/DateInput/DateInput.styles.ts, packages/react-ui/components/DateInput/DateInput.tsx, packages/react-ui/components/DateInput/__stories__/DateInput.stories.tsx, packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
Фикс ширины DatePicker в состоянии без фокуса с пустым значением. https://github.com/skbkontur/retail-ui/issues/2025#issuecomment-957996981
=> fix(DatePicker): width for different sizes with empty value

packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
нет возможности получить выпадающее меню в e2e тестах, если элементы списка загружаются.
=> test(Combobox): Добавил data-tid для дополнительных состояний комбобокса

packages/react-ui/internal/Calendar/Calendar.tsx, packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
the duplication of #2620 and #2625 for lts
=> fix(Calendar,ComboBox): add some data-tids

packages/react-ui/components/Link/Link.tsx, packages/react-ui/components/Link/__tests__/Link-test.tsx
Отрефакторил тесты + добавил тесты для проверки отключенного состояния ссылки.
=> test(Link): disabled state tests

packages/react-ui/components/Checkbox/Checkbox.md, packages/react-ui/components/Checkbox/Checkbox.tsx
Улучшил документацию контрола `Checkbox`: удалил описание контрола, добавил описание для пропов и методов, добавил новые примеры и отрефакторил старые.
=> docs(Checkbox): enhance documentation

packages/react-ui/components/Hint/Hint.md, packages/react-ui/components/Hint/Hint.tsx
Улучшил документацию контрола `Hint`: добавил описание контрола,  добавил описание для пропов, добавил новые примеры.
=> docs(Hint): enhance documentation

packages/react-ui/components/TokenInput/TokenInputMenu.tsx, packages/react-ui/internal/Popup/Popup.tsx, packages/react-ui/internal/PopupMenu/PopupMenu.tsx
Хочется по месту оверрайдить нулём значение из переменных темы
=> fix(popup): receive zero margin from props

packages/react-ui/components/SidePage/SidePage.styles.ts, packages/react-ui/components/SidePage/SidePage.tsx
fix #2352 
Проп offset задает отступ от края экрана
=> [SidePage] Добавить проп offset 

packages/react-ui/components/Checkbox/Checkbox.styles.ts, packages/react-ui/components/Radio/Radio.styles.ts, packages/react-ui/components/Radio/Radio.tsx, packages/react-ui/components/Switcher/Switcher.md, packages/react-ui/components/Switcher/Switcher.styles.ts, packages/react-ui/components/Switcher/Switcher.tsx, packages/react-ui/components/Switcher/__stories__/Switcher.stories.tsx, packages/react-ui/internal/themes/DefaultTheme.ts, packages/react-ui/internal/themes/FlatTheme.ts, packages/react-ui/internal/themes/Theme8px.ts
fix #2196 
Переименовано в компонентах Radio, Checkbox, Switcher
Добавила [кодмод](https://github.com/skbkontur/retail-ui/pull/2633) для переименования переменных
=> [Customization] - переименовать label в caption

packages/react-ui/lib/__tests__/isNonNullable-test.ts
Думаю, что всё-таки стоит держать тесты для каждой из утилит в отдельном файле. Так их будет проще читать и поддерживать.
=> test(utils): move utils tests to a separate file

packages/react-ui/internal/Popup/Popup.tsx
При закрытии попапа добавил сброс его местоположения.
Fix #2700
=> fix(Popup): add set DUMMY location after closing

packages/react-ui/MIGRATION.md
=> docs(react-ui): add migration for 4.0

packages/react-ui/.creevey/images/Spinner/With Custom Color/chrome.png, packages/react-ui/.creevey/images/Spinner/With Custom Color/chrome8px.png, packages/react-ui/.creevey/images/Spinner/With Custom Color/firefox.png, packages/react-ui/.creevey/images/Spinner/With Custom Color/firefox8px.png, packages/react-ui/.creevey/images/Spinner/With Custom Color/ie11.png, packages/react-ui/.creevey/images/Spinner/With Custom Color/ie118px.png, packages/react-ui/.creevey/images/Spinner/With Custom Width/chrome.png, packages/react-ui/.creevey/images/Spinner/With Custom Width/chrome8px.png, packages/react-ui/.creevey/images/Spinner/With Custom Width/firefox.png, packages/react-ui/.creevey/images/Spinner/With Custom Width/firefox8px.png, packages/react-ui/.creevey/images/Spinner/With Custom Width/ie11.png, packages/react-ui/.creevey/images/Spinner/With Custom Width/ie118px.png, packages/react-ui/components/Spinner/Spinner.md, packages/react-ui/components/Spinner/Spinner.styles.ts, packages/react-ui/components/Spinner/Spinner.tsx, packages/react-ui/components/Spinner/__stories__/Spinner.stories.tsx, packages/react-ui/internal/icons/SpinnerIcon.tsx
fix [IF-282](https://yt.skbkontur.ru/issue/IF-282)
Для кастомизации Spinner были добавлены пропы `width` и `color`
=> Добавление пропа ширины и цвета для Spinner

packages/react-ui/.creevey/images/Switcher/errored/chrome.png, packages/react-ui/.creevey/images/Switcher/errored/chrome8px.png, packages/react-ui/.creevey/images/Switcher/errored/firefox.png, packages/react-ui/.creevey/images/Switcher/errored/firefox8px.png, packages/react-ui/.creevey/images/Switcher/errored/firefoxFlat.png, packages/react-ui/.creevey/images/Switcher/errored/firefoxFlat8px.png, packages/react-ui/.creevey/images/Switcher/errored/ie11.png, packages/react-ui/.creevey/images/Switcher/errored/ie118px.png, packages/react-ui/.creevey/images/Switcher/errored/ie11Flat.png, packages/react-ui/.creevey/images/Switcher/errored/ie11Flat8px.png, packages/react-ui/components/Button/Button.styles.ts, packages/react-ui/components/Button/Button.tsx, packages/react-ui/components/Switcher/Switcher.styles.ts
1. Не отображается синяя обводка фокуса на выбранном пункте у switcher — должна быть при работе с клавиатурой. У невыбранных пунктов есть.
2. Не отображается синяя обводка фокуса у switcher в состоянии ошибки. Фокус должен перебивать ошибку и предупреждения, как это работает в кнопке.
Согласно [гайдам](https://guides.kontur.ru/components/switcher/#Fokus_i_rabota_s_klaviaturoi), выбранный элемент переключателя должен отображать синюю обводку фокуса при работе с клавиатуры, также как и невыбранные элементы. 
1. В кнопке убрала условие, при котором выбранная кнопка не отображает фокус.
2. В состоянии ошибки красная обводка переключателя была на пиксель выше синей обводки фокуса, я ее немного сдвинула внутрь
| Было | Стало |
|------|--------|
| …
=> Switcher - проблема с фокусом

packages/react-ui/index.ts, packages/react-ui/lib/theming/useTheme.ts
Создал хук для более удобной работы с темами.
Хук инкапсулирует логику взаимодействия с темами. В перспективе это помимо более удобного способа доставки инструментов для работы с темами позволит изменять внутреннюю реализацию механизма темизации без ломающих изменений для пользователей.
Сравнение предыдущей и текущей реализаций:
```tsx
// Раньше
import { useContext } from 'react';
import { ThemeContext } from '../../lib/theming/ThemeContext';
const theme = useContext(ThemeContext);
// Теперь
import { useTheme } from '../../lib/theming/useTheme';
const { theme } = useTheme()
```
=> :fire: feat(useTheme): hook for using theme

packages/react-ui/.eslintrc, packages/react-ui/components/Button/__stories__/Button.stories.tsx, packages/react-ui/components/Hint/__stories__/Hint.stories.tsx, packages/react-ui/package.json, yarn.lock
Добавил в `eslint` конфиг для `react-ui` плагин для написания историй.
Пофиксил ошибки, которые нашёл этот плагин.
=> chore(eslint): add plugin for storybook

packages/react-ui/components/ResponsiveLayout/ResponsiveLayoutEvents.ts
Попробовал бета версию в сервисе и... обнаружил что ie11 отвалился
Пока отваливается на `TypeError "matchMedia(...) .addEventListener is not a function"`, добавил фоллбек на addListener
=> fix(ResponsiveLayout): fallback for ie11

packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
Детали тут https://github.com/skbkontur/retail-ui/pull/2705
Тестов нет, т.к. ещё в исходном ПРе не удалось найти стабильное решение для масштабирования стори.
| Тесты локально |
| --- |
| ![image](https://user-images.githubusercontent.com/2708211/154440201-c98ef086-9c07-4f18-845f-399019082415.png) |
=> fix(ScrollContainer): Исправили проблемы с масштабированием в Хроме

packages/react-ui/components/Modal/Modal.tsx
Пофиксил импорт несуществующей зависимости, случайно добавленный в #2682.
=> fix(Modal): fix lodash import

packages/react-ui-validations/package.json
Добавил `index.js.map` в список публикуемых в пакет файлов. Фикс проблемы из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1632747015225500).
=> fix(react-ui-validations): publish source maps

packages/react-ui/components/DatePicker/DatePicker.tsx
=> IF-415: fix scroll to date in DatePicker

packages/react-ui/components/SidePage/SidePage.styles.ts
=> fix(SidePage): fix animation styles

packages/react-ui-smoke-test/react-ui-ssr/yarn.lock, packages/react-ui-testing/TestPages/yarn.lock
updates from dependabot
#2855 #2859
=> build: updates from dependabot

packages/react-ui-smoke-test/react-ui-ssr/yarn.lock, packages/react-ui-testing/TestPages/yarn.lock, yarn.lock
=> build: update from dependabot

packages/react-ui/components/Button/Button.styles.ts, packages/react-ui/internal/themes/DefaultTheme.ts
Добавил недостающую переменную в кнопку. 
[IF-451](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-451)
=> fix(Button): add btnLinkActiveColor theme var

packages/react-ui/components/SidePage/SidePage.tsx
This reverts commit 47dfb5ac895c26655edef2e08cf1f86f5b246390.
---
так решили в [#2821](https://github.com/skbkontur/retail-ui/pull/2821#discussion_r855999876)
=> Revert fix(SidePage): change scroll behavior according to Guides (#2756)

packages/react-ui/internal/Popup/Popup.tsx
https://github.com/skbkontur/retail-ui/issues/2876
=> [Tooltip] Ошибка отображения в мобильной верстке

packages/react-ui/internal/Popup/Popup.tsx
Пересоздано из #2877 для прогона тестов.
=> fix(Tooltip): don't render without content on mobiles  (#2877)

packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/chrome/sticky header, open and close internal side-page.png, packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/chrome8px/sticky header, open and close internal side-page.png, packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/firefox/sticky header, open and close internal side-page.png, packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/firefox8px/sticky header, open and close internal side-page.png, packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/ie11/sticky header, open and close internal side-page.png, packages/react-ui/.creevey/images/SidePage/Sticky SidePageHeader when another SidePage/sticky header, open and close internal side-page/ie118px/sticky header, open and close internal side-page.png, packages/react-ui/components/SidePage/SidePage.tsx, packages/react-ui/components/SidePage/SidePageContext.ts, packages/react-ui/components/SidePage/SidePageHeader.tsx, packages/react-ui/components/SidePage/__stories__/SidePage.stories.tsx, packages/react-ui/components/Sticky/Sticky.tsx
Дубликат #2763 в 3.9.3 по запросу из чата. Будет выпущена как `3.9.3-sidepagefix`.
=> fix(SidePage): copy fixes to 3.9.3

packages/react-ui/README.md
fixes [IF-486](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-486), #2854
Поправил ссылку на страницу `MOBILES.md` в доках
=> docs(README): fix MOBILES.md link

.teamcity/settings.kts
IF-555
Починил запуск тестов в валидациях для LTS. Аналогично правки в мастер 8fd7c3534bfe3.
=> build: fix launch of validation's tests for lts

packages/react-ui/scripts/package/index.js
Styleguide не запускается когда npm недоступен. 
Данные из npm нужны для сборки доки при релизе. При локальном запуске доке они не нужны. Поэтому, можно обработать падающий запрос в npm и замокать данные, которые запрашиваются из него.
IF-648
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR …
=> build(styleguide): fix styleguide building when npm isnt reachable

packages/react-ui/components/DateInput/DateInput.styles.ts
Cherry-picked 8339c75a54ae30ae8814551907e1df4089084dc0
Closes https://github.com/skbkontur/retail-ui/issues/2869
=> fix(DatePicker): fix focus and fragments selection

packages/react-ui/components/FileUploader/FileUploader.md
- В документации не указано, что `FileUploader` работает с нативным атрибутом `accept`
- Пример с валидацией файла из списка не работает
- Добавил пример с `accept`
- Применил правильный проп для валидации
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает суть изменений …
=> docs(FileUploader): fix demo validation and add demo with `accept`

packages/react-ui/.creevey/images/HideBodyVerticalScroll/Multiple With Scrollable Content/scroll, lock, unlock/chrome/locked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Multiple With Scrollable Content/scroll, lock, unlock/chrome/scrolled.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Multiple With Scrollable Content/scroll, lock, unlock/chrome/unlocked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Sample/scroll, lock, unlock/chrome/locked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Sample/scroll, lock, unlock/chrome/scrolled.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Sample/scroll, lock, unlock/chrome/unlocked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/With Scrollable Content/scroll, lock, unlock/chrome/locked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/With Scrollable Content/scroll, lock, unlock/chrome/scrolled.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/With Scrollable Content/scroll, lock, unlock/chrome/unlocked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/With html.overflowY=scroll/scroll, lock, unlock/chrome/locked.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/With html.overflowY=scroll/scroll, lock, unlock/chrome/scrolled.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/With html.overflowY=scroll/scroll, lock, unlock/chrome/unlocked.png, packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx, packages/react-ui/internal/HideBodyVerticalScroll/__stories__/HideBodyVerticalScroll.stories.tsx
Компонент не учитывает стиль `overflow-y: scroll` у `html`. Из-за чего при появлении `Modal`/`SidePage` контент "скачет", т.к. `HBVS` думает, что скролла нет, и не добавляет компенсацию.
- Добавил условие для добавления компенсации.
- Заменил старые стори на новые.
- Добавил скриншотные тесты т.к. юнит тестами такое сложно протестировать. Добавил тесты только для дефолтной темы в `chrome`, т.к. темы не влияют на логику и стили в `HBVS`.
⬜ нерелевантно
✅ комментарии для неочевидных мест в коде
⬜ …
=> fix(HideBodyVerticalScroll): add support `html.overflow-y=scroll`

packages/react-ui-validations/prod.tsconfig.json
В файле `tsconfig.json` подключаются типы из контролов. В редких случаях при сборке `rollup` пытается подтянуть некоторые типы, из-за чего может развалиться бандлинг типов.
Чуть подробнее можно почитать тут https://github.com/skbkontur/retail-ui/pull/2969. Там же один из прецендентов.
Другой прецедент https://github.com/skbkontur/retail-ui/pull/2940/commits/fafd72d66504c84c2a5dc3f07e329f265f25d36a#diff-73ba9ba6852aa4a443482c8f2e2db7c574194df1353afa7dafc2d497c280463e
Т.к. непосредственно контролы используются только в сторисах и документации, я решил убрал типы контролов из `prod.tsconfig.json`. 
Бандл типов `index.d.ts` никак не изменился.
✅ нерелевантно
2. Добавлена (обновлена) …
=> build(validations): don't include the `react-ui` typings

packages/react-ui-testing/Tests/TestEnvironment/BrowserSetUp.cs
Начали падать селениумные тесты
Оказалось что в балансировщике удалили домен для резолвинга ip.
Обновил домен для резолвинга
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> test(SeleniumTesting): set correct fakeip url

packages/react-ui/index.ts, packages/react-ui/lib/theming/ThemeContext.md
В [документации](https://tech.skbkontur.ru/react-ui/#/Customization/ThemeContext) советуется использовать функции ColorFunctions, DimensionFunctions, но их нет в публичном экспорте
Добавила экспорт ColorFunctions, DimensionFunctions из index.ts
fix IF-841
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ …
=> chore: add public export ColorFunctions DimensionFunctions

packages/react-ui/.creevey/images/Button/Arrow Left/chrome.png, packages/react-ui/.creevey/images/Button/Arrow Left/chrome8px.png, packages/react-ui/.creevey/images/Button/Arrow Left/chromeDark.png, packages/react-ui/.creevey/images/Button/Arrow Left/chromeFlat8px.png, packages/react-ui/.creevey/images/Button/Arrow Left/firefox.png, packages/react-ui/.creevey/images/Button/Arrow Left/firefox8px.png, packages/react-ui/.creevey/images/Button/Arrow Left/firefoxDark.png, packages/react-ui/.creevey/images/Button/Arrow Left/firefoxFlat8px.png, packages/react-ui/.creevey/images/Button/Arrow Left/ie11.png, packages/react-ui/.creevey/images/Button/Arrow Left/ie118px.png, packages/react-ui/.creevey/images/Button/Arrow Left/ie11Dark.png, packages/react-ui/.creevey/images/Button/Arrow Left/ie11Flat8px.png, packages/react-ui/components/Button/__stories__/Button.stories.tsx
В сторибуке Button проверяло 2 раза один и тот же вариант состояния кнопки arrow.
Исправила один из сторей на arrow left, как и предполагалось
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> Tests: fix arrow left tests, screenshots

packages/react-ui/components/ResponsiveLayout/ResponsiveLayoutEvents.ts, packages/react-ui/lib/SSRSafe.ts
При использовании `ResponsiveLayout` нельзя использовать `SSR`, так как `ResponsiveLayout` под капотом использует `window.matchMedia`
Добавил проверку на наличие `window` в тех местах, где используется `window.matchMedia`
IF-872
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее …
=> fix(ResponsiveLayout): configure to work with SSR

scripts/update-package-registry.js
Скрипт `update-package-registry.js` заменяет URL реестра пакета на тот, что в файле `.env`.
Исходный URL определяется командой:
```console
$ yarn config get registry
```
Скрипт работает только с `yarn.lock` который в корне. В репе есть ещё два lock-файла:
- `packages/react-ui-testing/TestPages/yarn.lock`
- `packages/react-ui-smoke-test/react-ui-ssr/yarn.lock`
Команда `yarn config get registry` возвращает то, что указано в файле `.yarnrc`.
Но фактически в lock-файлах есть ссылки на разные реестры: `npmjs`, `yarnpkg`.
Если команда `yarn install` разваливается по каким-либо причинам, то скрипт не вызывается и правки лок-файла не откатываются.
Добавил список всех lock-файлов и обработку для каждого.
Добавил массив URL'ов реестров. Во время замены урлов, сохраняю оригинальный урл в специальный …
=> refactor(update-package-registry): add other registries and lock files

packages/react-ui/components/Sticky/Sticky.tsx
Заметила, что в Sticky указан неправильный data-tid
исправила на корректный
fix IF-1054
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> chore(Sticky): fix incorrect `data-tid`

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/react-ui/internal/InputLikeText/InputLikeText.tsx
После влития ПРа #3094 стал ругаться линтер.
На форках не запускаются ТС тесты, а при проверке вручную упустили эту проблему.
Прогнал фиксер. Выдал прав контребьютору.
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> lint: fix after merging

packages/react-ui/components/Token/Token.tsx, packages/react-ui/components/Token/__tests__/Token-test.tsx
Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL
Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …
=> test(token): remove using enzyme 

packages/react-ui/components/DropdownMenu/__tests__/DropdownMenu-test.tsx
Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL
Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …
=> test(dropdownMenu): remove using enzyme

packages/react-ui/components/MenuItem/__tests__/MenuItem-test.tsx
Перевод тестов с enzyme на react testing library
Переписаны unit тесты с enzyme на react testing library
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> test(MenuItem): remove using enzyme

.github/workflows/release.yml, package.json
Релизим бэты.
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> ci: release betas

packages/react-ui/components/Paging/__tests__/Paging-test.tsx
Перевод тестов с enzyme на react testing library
Переписаны unit тесты с enzyme на react testing library
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> test(Paging): remove using enzyme

packages/react-ui/.creevey/images/ComboBox/toogle error/plain again/chrome2022/plain again.png, packages/react-ui/.creevey/images/ComboBox/toogle error/plain again/chrome2022Dark/plain again.png, packages/react-ui/.creevey/images/ComboBox/toogle error/with error/chrome2022/with error.png, packages/react-ui/.creevey/images/ComboBox/toogle error/with error/chrome2022Dark/with error.png, packages/react-ui/.creevey/images/Select/with search/and various width/chrome2022/w100prc.png, packages/react-ui/.creevey/images/Select/with search/and various width/chrome2022/w100px.png, packages/react-ui/.creevey/images/Select/with search/and various width/chrome2022/w300px.png, packages/react-ui/.creevey/images/Select/with search/and various width/chrome2022Dark/w100prc.png, packages/react-ui/.creevey/images/Select/with search/and various width/chrome2022Dark/w100px.png, packages/react-ui/.creevey/images/Select/with search/and various width/chrome2022Dark/w300px.png, packages/react-ui/.creevey/images/Toggle/plain/clicked/chrome2022/clicked.png, packages/react-ui/.creevey/images/Toggle/plain/clicked/chrome2022Dark/clicked.png, packages/react-ui/.creevey/images/Toggle/with long description/clicked/chrome2022/clicked.png, packages/react-ui/.creevey/images/Toggle/with long description/clicked/chrome2022Dark/clicked.png, packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx, packages/react-ui/components/Select/__stories__/Select.stories.tsx, packages/react-ui/components/Toggle/__stories__/Toggle.stories.tsx
В мастере стали мигать некоторые тесты. В основном в `chrome2022` и `chrome2022Dark`.
В данный момент нет времени расследовать причины.
Тестов мигает мало, поэтому посчитал что пока можно просто заскипать их.
`IF-1230`
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает …
=> test: skip flaky tests

packages/react-ui/typings/html.d.ts
В `html.d.ts` дублировался тип для `div`, что мешало сборке одного из проектов
Удалил дубль типа `div`
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> chore(html): get rid of type duplication

packages/react-ui/.creevey/config.js
Принято решение отказаться от поддержки браузеров IE, первый шаг перестать гонять тесты скриншотные для этих браузеров. 
Закомментила IE браузеры в конфиге криви
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> Refactor: delete IE from config in creevey

packages/react-ui/.creevey/config.js
В PR https://github.com/skbkontur/retail-ui/pull/3205/files случайно закомментили и chromeMobile тоже 
Вернула chromeMobile в конфиг, чтобы тесты гонялись и на этом браузере 
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> test: return chromeMobile in tests

packages/react-ui/.creevey/images/Select/Mobile With Long Item/chromeMobile.png, packages/react-ui/components/Select/Select.styles.ts, packages/react-ui/components/Select/__stories__/Select.stories.tsx, packages/react-ui/internal/themes/DefaultTheme.ts
При большой ширине контента выбранного пункта, Select мог вылезать за границу родительского блока.
Ограничить максимальную ширину Select'a через max-width, значение max-width вынести в переменную.
fix IF-820
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅  в коде нет лишних изменений
✅ заголовок PR кратко и доступно отражает суть …
=> fix(Select): add max-width on mobile

packages/react-ui/components/Loader/__tests__/Loader-test.tsx
Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL
Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …
=> test(Loader): remove uning enzyme #3212

packages/react-ui/lib/rootNode/rootNodeDecorator.tsx
Добавлено прокидывание свойства __KONTUR_REACT_UI__ в декоратор из оборачиваемого объекта
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> fix(): fix rootNodeDecorator

packages/react-ui/.creevey/images/Paging/Disabled Paging/chrome2022.png, packages/react-ui/.creevey/images/Paging/Disabled Paging/chrome2022Dark.png, packages/react-ui/.creevey/images/Paging/Paging Disabled Forward Link/chrome.png, packages/react-ui/.creevey/images/Paging/Paging Disabled Forward Link/chrome2022.png, packages/react-ui/.creevey/images/Paging/Paging Disabled Forward Link/chrome2022Dark.png, packages/react-ui/.creevey/images/Paging/Paging Disabled Forward Link/chromeDark.png, packages/react-ui/components/Paging/Paging.styles.ts, packages/react-ui/components/Paging/Paging.tsx, packages/react-ui/components/Paging/__stories__/Paging.stories.tsx
В 2022-ой теме при переходе на последнюю доступную страницу кнопка «Дальше» не отключалась
- Исправил ошибку в логике, из-за которой не работало поведение
- Добавил стиль `pointer-events: none`, чтобы вокруг кнопки не появлялась обводка, когда кнопка отключена
- Добавил скриншотны для теста логики
IF-1453
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ все тесты и линтеры …
=> fix(Paging): disable forward button when current page is last

packages/react-ui/components/Loader/__tests__/Loader-test.tsx, packages/react-ui/components/Spinner/Spinner.tsx, packages/react-ui/components/Spinner/__tests__/Spinner-test.tsx, packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md, packages/react-ui/lib/featureFlagsContext/ReactUIFeatureFlagsContext.tsx
По гайдам нельзя использовать подпись "Загрузка" в спиннере, но в библиотеке по дефолту она есть.
Убрать дефолтную подпись под фиче-флаг.
Closes [IF-1155](https://yt.skbkontur.ru/issue/IF-1155)
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
✅  все тесты и линтеры на CI проходят
✅ заголовок PR кратко и доступно отражает суть изменений (он …
=> feat(Spinner): hide default caption under a feature flag

packages/react-ui/components/Tooltip/Tooltip.md, packages/react-ui/components/Tooltip/Tooltip.tsx, packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
Надо было дотащить ПР, внеся правки по необходимости.
Втащил ПР, добавив тесты на новую логику.
Ссылка на оригинальный [ПР](https://github.com/skbkontur/retail-ui/pull/3349)
Close [IF-1618](https://yt.skbkontur.ru/issue/IF-1618)
⬜ нерелевантно
✅ прочие инструкции (`README.md`, `contributing.md` и др.)
⬜ нерелевантно
✅ нерелевантно
4. Прочее …
=> feat(Tooltip): new prop 'showDelay'

packages/react-ui-testing/package.json
Каждый раз при установке зависимостей в проекте дополнительно запускается установка зависимостей в подпроекте `packages/react-ui-testing/TestPages`. Этот подпроект уже давно не обновлялся, и некоторые его зависимости кидают
ошибку во время установки в определенных окружениях (win, node 16.15.1, yarn 1). Это приводит к тому, установка зависимостей во всем проекте прерывается. Скрипт `postinstall` в корне не выполняется.
Так как этот подпроект нужен  только для тестов в пакете react-ui-testing, перенес установку его зависимостей в фазу его сборки.
✅ нерелевантно
⬜ jsdoc для утилит и …
=> build(react-ui-testing): don't install test deps on every install

packages/react-ui/internal/MaskedInputElement/MaskedInputElement.tsx, packages/react-ui/package.json, yarn.lock
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> build: remove unnecessary package

.teamcity/settings.kts
Сеть на агентах перестанет резолвить дефолтный url `api.nuget.org`.
Добавил корректный прокси в настройках Тимсити, и заюзал в виде переменной, чтобы не светить.
`IF-1665`
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> ci: update the NuGet source URL

packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
Не работал пример в документации.
Исправил пример.
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
=> docs: fix combobox feature flag example

.husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push
https://github.com/git-lfs/git-lfs/commit/86a8d7369c9820caa378f51468de919ef3d4e5e2
Обновить файлы, и версии git lfs до >= 3.4
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> New lfs messages

packages/react-ui/.creevey/images/Button/Icon And Text Hover Color/hover/firefox/hover.png, packages/react-ui/.creevey/images/Button/Icon And Text Hover Color/hover/firefox2022/hover.png, packages/react-ui/.creevey/images/Button/Icon Color/chrome.png, packages/react-ui/.creevey/images/Button/Icon Color/chrome2022.png, packages/react-ui/.creevey/images/Button/Icon Color/chrome2022Dark.png, packages/react-ui/.creevey/images/Button/Icon Color/chrome8px.png, packages/react-ui/.creevey/images/Button/Icon Color/chromeDark.png, packages/react-ui/.creevey/images/Button/Icon Color/chromeFlat8px.png, packages/react-ui/.creevey/images/Button/Icon Color/firefox.png, packages/react-ui/.creevey/images/Button/Icon Color/firefox2022.png, packages/react-ui/.creevey/images/Button/Icon Color/firefox2022Dark.png, packages/react-ui/.creevey/images/Button/Icon Color/firefox8px.png, packages/react-ui/.creevey/images/Button/Icon Color/firefoxDark.png, packages/react-ui/.creevey/images/Button/Icon Color/firefoxFlat8px.png, packages/react-ui/components/Button/Button.mixins.ts, packages/react-ui/components/Button/Button.styles.ts, packages/react-ui/components/Button/ButtonIcon.tsx, packages/react-ui/components/Button/__stories__/Button.stories.tsx
Сейчас в кнопке прописан очень специфичный селектор и его сложно перебить. Переменные `btnIconColor`, `btnIconHoverColor` работают не так, как ожидается.
Убрал специфичный селектор.
Fix [IF-1658](https://yt.skbkontur.ru/issue/IF-1658)
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и …
=> fix(Button): fix icon color customization

packages/react-ui/.creevey/images/Kebab/14px/escapePress/chrome/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/chrome2022/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/chrome2022Dark/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/chrome8px/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/chromeDark/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/firefox/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/firefox2022/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/firefox2022Dark/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/firefox8px/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/firefoxDark/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/ie11/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/ie112022/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/ie112022Dark/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/ie118px/escapePress.png, packages/react-ui/.creevey/images/Kebab/14px/escapePress/ie11Dark/escapePress.png, packages/react-ui/components/Input/__stories__/Input.creevey.stories.tsx, packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx, packages/react-ui/components/Kebab/__tests__/Kebab-test.tsx, packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx, packages/react-ui/internal/ZIndex/__stories__/ZIndex.stories.tsx
У нас есть мигающие тесты сейчас.
Просмотрел падающие тесты примерно за неделю, нашёл часто мигающие тесты, что-то заскипал, что-то переписал на RTL.
Fix [IF-1726](https://yt.skbkontur.ru/issue/IF-1726
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает суть изменений (он …
=> chore: fix flaky screenshot tests

packages/react-ui/components/Calendar/DayCellView.tsx, packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/react-ui/components/DropdownMenu/__tests__/DropdownMenu-test.tsx, packages/react-ui/components/MenuItem/MenuItem.tsx, packages/react-ui/components/Paging/Paging.tsx, packages/react-ui/components/Select/Select.tsx, packages/react-ui/components/Select/__tests__/Select-test.tsx, packages/react-ui/components/Tabs/Tab.tsx, packages/react-ui/internal/CommonWrapper/CommonWrapper.tsx, packages/react-ui/internal/CommonWrapper/__tests__/getCommonVisualStateDataAttributes.test.ts, packages/react-ui/internal/CommonWrapper/__tests__/getVisualStateDataAttributes.test.ts, packages/react-ui/internal/CommonWrapper/extractCommonProps.ts, packages/react-ui/internal/CommonWrapper/getCommonVisualStateDataAttributes.ts, packages/react-ui/internal/CommonWrapper/getVisualStateDataAttributes.ts, packages/react-ui/internal/CommonWrapper/index.tsx, packages/react-ui/internal/CommonWrapper/types.ts, packages/react-ui/lib/__tests__/toKebabCase.test.ts, packages/react-ui/lib/toKebabCase.ts
Пересобрал ветку https://github.com/skbkontur/retail-ui/pull/3392 под master
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> Атрибуты для тестов

package.json, packages/react-ui-validations/docs/Common/SpaceFiller.ts, packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/ControlsWithValidations.ts, packages/react-ui-validations/docs/index.html, packages/react-ui-validations/docs/styles/variables.less, packages/react-ui-validations/src/Validations/ValidationReader.ts, packages/react-ui/.styleguide/components/Preview/Preview.tsx, packages/react-ui/components/Button/Button.mixins.ts, packages/react-ui/components/Button/Button.styles.ts, packages/react-ui/components/Checkbox/Checkbox.styles.ts, packages/react-ui/components/FileUploader/FileUploader.styles.ts, packages/react-ui/components/GlobalLoader/GlobalLoaderView.styles.ts, packages/react-ui/components/Input/Input.tsx, packages/react-ui/components/Loader/Loader.tsx, packages/react-ui/components/ResponsiveLayout/types.ts, packages/react-ui/components/ScrollContainer/ScrollContainer.styles.ts, packages/react-ui/components/SidePage/SidePage.styles.ts, packages/react-ui/components/SidePage/__stories__/SidePage.stories.tsx, packages/react-ui/components/Spinner/Spinner.tsx, packages/react-ui/components/Spinner/SpinnerFallbackAnimation.ts, packages/react-ui/components/Switcher/Switcher.styles.ts, packages/react-ui/components/Textarea/Textarea.styles.ts, packages/react-ui/components/Toggle/Toggle.styles.ts, packages/react-ui/components/Token/Token.styles.ts, packages/react-ui/internal/ComponentCombinator.tsx, packages/react-ui/internal/Popup/Popup.styles.ts, packages/react-ui/internal/Popup/Popup.tsx, packages/react-ui/internal/icons2022/iconConstants.ts, packages/react-ui/typings/utility-types.d.ts, yarn.lock
Обновление общих инструментов разработки
| Пакет | Было | Стало | latest |
| ------ | ----- | ----- | ---- |
| [@commitlint/cli](https://www.npmjs.com/package/@commitlint/cli) | `^12.1.1` | `^19.2.1` | ✅ `19.2.1` |
| [@commitlint/config-conventional](https://www.npmjs.com/package/@commitlint/config-conventional) | `^12.1.1` | `^19.1.0` | ✅ `19.1.0` |
| [commitizen](https://www.npmjs.com/package/commitizen) | `^4.2.3` | `^4.3.0` | ✅ `4.3.0` |
| [cz-conventional-changelog](https://www.npmjs.com/package/cz-conventional-changelog) | `^3.3.0` | `^3.3.0` | ✅ `3.3.0` |
| [env-cmd](https://www.npmjs.com/package/env-cmd) | `^10.1.0` | `^10.1.0` | ✅ `10.1.0` |
| [husky](https://www.npmjs.com/package/husky) | `^6.0.0` | `^9.0.11` | ✅ `9.0.11` |
| [lerna](https://www.npmjs.com/package/lerna) | …
=> feat(retail-ui): update dev dependencies

packages/react-ui/.creevey/images/Button/Hover Text Color/hover/firefox/hover.png, packages/react-ui/.creevey/images/Button/Hover Text Color/hover/firefox2022/hover.png, packages/react-ui/components/Button/__stories__/Button.stories.tsx
В [ПР](https://github.com/skbkontur/retail-ui/pull/3365) не было теста на поведение.
Добавил недостающий тест.
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> test(Button): add missing screenshot tests

packages/react-ui/components/Token/Token.tsx
Описание будет позже.
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> fix(Token): suppress a11y issue

.teamcity/settings.kts
На агентах тимсити падает сборка с ошибкой 
"error: option `--cwd <cwd>' argument missing"
yarn 1.22.22, локально воспроизводится
Переместил параметр --cwd
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> Конфигурация yarn pack для работы с yarn 1.22.22

packages/react-ui-smoke-test/.babelrc.js, packages/react-ui-smoke-test/react-ui-ssr/package.json, packages/react-ui-smoke-test/react-ui-ssr/yarn.lock, packages/react-ui-validations/package.json, packages/react-ui/.babelrc.js, packages/react-ui/jest.config.js, packages/react-ui/package.json
https://babeljs.io/docs/babel-plugin-transform-runtime#useesmodules
Не запускаются юнит тесты в ide
Поправить конфиг, чтобы модульная система автоматически определялась
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> Конфигурация модульной системы при запуске юнит тестов

packages/react-ui-smoke-test/cra-template-react-ui/template.json
Стали падать smoke-тесты из-за выхода [сломанной версии](https://www.npmjs.com/package/react-focus-lock/v/2.12.0) пакета `react-focus-lock`. В тестах устанавливаются последние допустимые версии зависимостей, поэтому тестовый проект перестал запускаться.
Временно зафиксировал версию react-focus-lock в smoke-тестах.
[Issue](https://github.com/theKashey/react-focus-lock/issues/301) в react-focus-lock.
✅ нерелевантно
✅ нерелевантно
3. Изменения корректно …
=> test(smoke): temp fix for broken react-focus-lock@2.12.0

packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
Фонит тест "should hide in start->done->start->done scenario", скорее всего изза того что реакт не успевает перерендерить состояние, падает примерно 3 из 100 раз
Сделал экспект асинхронным через waitFor (проверил на 1000 прогонах -- зеленый)
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR …
=> test: stabilize test for global loader

packages/react-ui/components/Kebab/Kebab.tsx, packages/react-ui/components/Link/Link.tsx, packages/react-ui/components/Paging/Paging.tsx
По запросу https://yt.skbkontur.ru/issue/IF-1751
Добавил несколько недостающих атрибутов
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> feat: add visual state disabled

packages/react-ui-validations/check-dts.tsconfig.json, packages/react-ui-validations/package.json, packages/react-ui-validations/src/utils/featureFlagsContext/ValidationsFeatureFlagsContext.tsx
https://yt.skbkontur.ru/issue/IF-1765
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> fix(Validation): correct types in build declaration

packages/react-ui-smoke-test/cra-template-react-ui/template.json, packages/react-ui-smoke-test/cra-template-react-ui/template/src/App.tsx, packages/react-ui-smoke-test/cra-template-react-ui/template/src/index.tsx, packages/react-ui-smoke-test/package.json, yarn.lock
Падает smoke тест из-за конфликта версий. Обновила зависимости в react-ui-smoke-test
template 
| Пакет | Было | Стало | latest | Комментарий |
| ------ | ----- | ----- | ---- | ---- |
| [react](https://www.npmjs.com/package/react) | `^17.0.0` | `^18.2.0` | ✅`18.2.0` |  |
| [react-dom](https://www.npmjs.com/package/react-dom) | `^17.0.0` | `^18.2.0` | ✅`18.2.0` |  |
| [@types/react](https://www.npmjs.com/package/@types/react) | `^17.0.0` | `^18.2.79` | ✅`18.2.79` |  |
| [@types/react-dom](https://www.npmjs.com/package/@types/react-dom) | `^17.0.0` | `^18.2.25` | ✅`18.2.25` |  |
| [typescript](https://www.npmjs.com/package/typescript) | `4.2.4` | `4.9.4` | ✅`4.9.4` |  |
| [@skbkontur/react-icons](https://www.npmjs.com/package/@skbkontur/react-icons) | `^3.2.0` | `^5.2.9` | ✅`5.2.9` |  |
| …
=> feat: update dependenciess in  Smoke test

packages/react-ui-codemod/package.json, packages/react-ui-codemod/react-ui-2.0/addCloudProp.ts, packages/react-ui-codemod/react-ui-2.0/helpers.ts, packages/react-ui-codemod/react-ui-2.0/moveToAddons.ts, packages/react-ui-codemod/react-ui-2.0/transformImportsAndExports.ts, packages/react-ui/package.json, yarn.lock
Обновление пакета codemod
| Пакет | Было | Стало | latest | Комментарий |
| ------ | ----- | ----- | ---- | ---- |
| [ast-types](https://www.npmjs.com/package/ast-types) | `0.13.2` | `0.14.2` | ✅ `0.14.2` |  |
| [jest](https://www.npmjs.com/package/jest) | `^24.9.0` | `^29.7.0` | ✅ `29.7.0` |  |
| [jscodeshift](https://www.npmjs.com/package/jscodeshift) | `^0.7.0` | `^0.15.2` | ✅ `0.15.2` |  |
| [@babel/core](https://www.npmjs.com/package/@babel/core) | `^7.12.8` | `^7.24.5` | ✅ `7.24.5` |  |
| [@babel/preset-env](https://www.npmjs.com/package/@babel/preset-env) | `^7.12.7` | `^7.24.5` | ✅ `7.24.5` |  |
| [@babel/preset-typescript](https://www.npmjs.com/package/@babel/preset-typescript) | `^7.12.7` | `^7.24.1` | ✅ `7.24.1` |  |
| …
=> feat: update codemod

packages/react-ui/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx, packages/react-ui/components/DropdownMenu/__tests__/DropdownMenu-test.tsx, packages/react-ui/components/MenuItem/MenuItem.tsx, packages/react-ui/components/Select/Select.tsx, packages/react-ui/components/TokenInput/TokenInput.tsx, packages/react-ui/internal/Menu/Menu.tsx, packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md, packages/react-ui/lib/featureFlagsContext/ReactUIFeatureFlagsContext.tsx
Удаление menuItemsAtAnyLevel фиче-флага
Удалила фиче-флаг. Теперь можно использовать различные обертки для пунктов меню
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> feat: remove menuItemsAtAnyLevel feature flag

packages/react-ui/components/Group/__stories__/Group.stories.tsx
в историях при нажатии на кнопку Clear - инпут не очищается
Исправлено
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
=> docs(Group): update stories group with input and multiple buttons

packages/react-ui-validations/.storybook/main.ts, packages/react-ui-validations/.storybook/preview.tsx, packages/react-ui/.storybook/main.ts, packages/react-ui/.storybook/preview.tsx
Подгружается стартовая страница с button, появляется уведомление о предложении обновить сторибук до новой версии
Стартовая страница изменена на страницу с Versions.mdx. Убрано всплывающее окошко с обновлением сторибука.
[YouTrack](https://yt.skbkontur.ru/issue/IF-1912)
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
✅ в коде нет лишних …
=> docs(versions, notifications): storybook config

packages/react-ui/components/Paging/__stories__/Paging.stories.tsx
Paging, изначально показывает, что есть от 6 страницы и больше. Если нажать на шестую страницу, то попадаем на 5 и дальше нет страниц
Исправил, чтобы было больше 7 страниц
[YouTrack](https://yt.skbkontur.ru/issue/IF-1918/Dopolneniya-dlya-perehoda-na-novuyu-dokumentaciyu)
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ в коде нет лишних …
=> docs(Paging): update story example

packages/react-ui/.styleguide/components/Preview/Preview.tsx
Хотим знать, как часто пользователи пользуются возможностью редактировать примеры (live code)
Пока добавил только факт самого редактирования кода. Нет информации в каком примере это было.
Возможно в будущем попробуем вытащить эту информацию или перейдем на новый движок.
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ в коде нет лишних …
=> add live code metrics

packages/react-ui/.storybook/docsPages/versioning/Versions.tsx, packages/react-ui/.storybook/docsPages/versioning/oldVersions.json
✅ нерелевантно
✅ прочие инструкции (`README.md`, `contributing.md` и др.)
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> chore(): create versions page

packages/react-ui/.storybook/preview-head.html, packages/react-ui/components/Calendar/CalendarDay.md, packages/react-ui/components/Calendar/__docs__/CalendarDay.docs.stories.tsx, packages/react-ui/components/ComboBox/ComboBox.md, packages/react-ui/components/ComboBox/__docs__/ComboBox.docs.stories.tsx, packages/react-ui/components/DatePicker/DatePicker.md, packages/react-ui/components/DatePicker/__docs__/DatePicker.docs.stories.tsx, packages/react-ui/components/Input/Input.md, packages/react-ui/components/Input/Input.tsx, packages/react-ui/components/Input/__docs__/Input.docs.stories.tsx
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> chore(): fix docs examples

packages/react-ui/components/Button/Button.mixins.ts, packages/react-ui/components/Button/Button.styles.ts, packages/react-ui/internal/themes/BasicLightTheme.ts
После удаления старых тем ещё остались старые стили и переменные в кнопке.
Удалил переменные и стили, которые использовались для отрисовки бордера в [старой](https://ui.gitlab-pages.kontur.host/docs/storybook/react-ui/master/?path=/story/button--playground-default&globals=theme:DEFAULT_THEME_8PX_OLD) выпуклой теме.
- Все переменные `btn[use]BorderBottomColor` и `btn[use]BorderTopColor` и их `hover` и `active` версии.
- Стили для отрисовки теней.
✅ нерелевантно
⬜ прочие инструкции (`README.md`, `contributing.md` и …
=> refactor(Button): remove old styles and vars for border bottom/top

.teamcity/settings.kts
Текущий ключ для публикации `Kontur.ReactUI.SeleniumTesting` устаревает 
Обновил ключ
`IF-2002`
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> ci: update and hide nuget apikey

packages/react-ui-validations/docs/Pages/Examples/Editors/Editors.demo.tsx, packages/react-ui-validations/docs/index.tsx, packages/react-ui-validations/package.json, yarn.lock
В документации не работает роутинг и страница editors не открывается.
https://yt.skbkontur.ru/issue/IF-2003/Validacii.-Slomalsya-routing-v-tekushej-dokumentacii
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> fix(docs): change router type

packages/react-ui/components/Calendar/Calendar.md
После обновления до 5.0 сломался пример с календарем
Заменил `calendarCellSize` на `calendarCellWidth` и `calendarCellHeight`
✅ нерелевантно
⬜ нерелевантно
✅ нерелевантно
4. Прочее
=> docs(Calendar): fix deprecated `calendarCellSize` token

packages/react-ui-validations/.storybook/Meta.tsx, packages/react-ui/.storybook/Meta.tsx
- Починил ссылки в тулбаре
- Написал с большой буквы RU/EN
https://yt.skbkontur.ru/issue/IF-2063
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> docs(): fix toolbar links

packages/react-ui/components/Button/Button.tsx
Неиспользуемые игнорируемые правила ESLint `// eslint-disable-next-line react-hooks/rules-of-hooks`
`cd ./packages/react-ui && yarn fix`
прогнал — строчка с игнором удалилась
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> chore(Button): remove unused ESLint ignore

packages/react-ui/lib/__tests__/taskWithDelayAndMinimalDuration.test.ts, packages/react-ui/lib/taskWithDelayAndMinimalDuration.ts
В некоторых ситуациях лоадер крутится даже если передан проп active=false
Не ставить таймер на включение задачи если она уже была включена и находится в процессе длинного цикла выполнения.
https://yt.skbkontur.ru/issue/IF-2104
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …
=> fix(Loader): order of async operations

packages/react-ui-validations/.storybook/Meta.tsx, packages/react-ui/.storybook/Meta.tsx
⬜ нерелевантно
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> fix: duplicate stories

contributing.md
В contributing.md остались ссылки на слак.
Поменял ссылку канала на маттермост и убрал строку про написать на почту для людей не из контура, т.к. в маттермосте нельзя писать на почту канала, судя по всему.
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
✅ заголовок PR кратко и доступно отражает суть изменений …
=> docs: change slack links to mattermost

packages/react-ui/lib/__tests__/taskWithDelayAndMinimalDuration.test.ts, packages/react-ui/lib/taskWithDelayAndMinimalDuration.ts
Пофиксили проблему в next, но решили бэкпортнуть в предыдущий мажор.
Пофиксили проблему в next, но решили бэкпортнуть в предыдущий мажор.
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> fix(Loader): prevent unwanted activation

packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/hide.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/idle.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/resize.png, packages/react-ui/.creevey/images/HideBodyVerticalScroll/Disorderly Unmount And Resize/idle, hide, show, resize/chrome2022/show.png, packages/react-ui/internal/FocusControlWrapper/FocusControlWrapper.stories.tsx, packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx, packages/react-ui/internal/HideBodyVerticalScroll/__stories__/HideBodyVerticalScroll.stories.tsx
Пофиксили проблему в next, но решили бэкпортнуть в предыдущий мажор.
Пофиксили проблему в next, но решили бэкпортнуть в предыдущий мажор.
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> fix(HideBodyVerticalScroll): fix disorderly unmount and resize

packages/react-ui/components/Calendar/DayCellView.tsx, packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
Пофиксили проблему в next, но решили бэкпортнуть в предыдущий мажор.
Пофиксили проблему в next, но решили бэкпортнуть в предыдущий мажор.
⬜ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> fix(Calendar, DatePicker): fix click on disabled dates

packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx, packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
После последовательного влития #3600 и #3602 без подтягивания изменений и перезапуска тестов сломалась пара тестов, добавленных в первом ПР из-за правок во втором.
Поправил селекторы.
✅ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее …
=> test(ComboBox,DatePicker): fix textbox queries

packages/react-ui/.creevey/images/Modal/Cross Focused By Tab/idle/chrome2022.png, packages/react-ui/.creevey/images/Modal/Cross Focused By Tab/idle/chrome2022Dark.png, packages/react-ui/.creevey/images/Modal/Cross Focused By Tab/idle/firefox2022.png, packages/react-ui/.creevey/images/Modal/Cross Focused By Tab/idle/firefox2022Dark.png, packages/react-ui/components/Modal/Modal.styles.ts
Поправил кликабельную область в https://github.com/skbkontur/retail-ui/pull/3573
| [Было](https://ui.gitlab-pages.kontur.host/docs/storybook/react-ui/cross-clickable-area-in-modal-and-sidepage/?path=/docs/overlay-modal-modal--docs) | [Стало](https://ui.gitlab-pages.kontur.host/docs/storybook/react-ui/cross-clickable-focus/?path=/docs/overlay-modal-modal--docs) |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/a357d7bb-2015-435b-9087-45382e0ce3db) | ![image](https://github.com/user-attachments/assets/6503c75c-84dc-4440-b50e-904096a0f85a) | 
✅ нерелевантно
⬜ …
=> chore(ModalClose): reduce focus area

packages/react-ui-validations/docs/Common/Notification.tsx, packages/react-ui/.styleguide/components/Notification/Notification.styles.ts, packages/react-ui/.styleguide/components/Notification/Notification.tsx, packages/react-ui/.styleguide/components/StyleGuideWrapper/StyleGuideWrapper.styles.ts
- Поставил плашку про окончание поддержки старой документации и переезд на новую
- Поправил адаптивность
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> docs: update new docs banner

packages/react-ui-testing/TestPages/src/components/TestPages/InputTestPage.jsx, packages/react-ui-testing/Tests/TestEnvironment/Browser.cs, packages/react-ui-testing/Tests/Tests.csproj
Дубли #3624  и #3626 в мастер.
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> build: fix selenium tests in master

packages/react-ui/components/FileUploader/FileUploader.tsx, packages/react-ui/components/FileUploader/__docs__/FileUploader.docs.stories.tsx, packages/react-ui/components/FileUploader/__tests__/FileUploader-test.tsx
В мастере нет новой доки.
Сделал версию [#3625](https://github.com/skbkontur/retail-ui/pull/3625) для `next` с новой докой вместо старой.
⬜ нерелевантно
✅ jsdoc для утилит и хелперов
⬜ нерелевантно
⬜ нерелевантно
4. Прочее
=> fix(FileUploader): add ability to remove hidden files

.teamcity/settings.kts
Редактирование конфиги для прогона тестов в различных окружениях.
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> ci: edit project for react version tests

.teamcity/settings.kts
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> ci: delete eql symbol from test project id

.teamcity/settings.kts
✅ нерелевантно
✅ нерелевантно
✅ нерелевантно
4. Прочее
=> ci: delete from id param special characters in versions test config

packages/react-ui/components/Toggle/Toggle.tsx, packages/react-ui/components/Toggle/__tests__/Toggle-test.tsx
Toggle: нельзя проставить проп name во внутренний input
Прокинуть атрибут
https://yt.skbkontur.ru/issue/IF-2186
⬜ нерелевантно
✅ нерелевантно
⬜ нерелевантно
4. Прочее
=> fix(Toggle): pass name attribute
